### ISSUE TITLE
Standard plots for the Moran process

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#1048]
We should have plots for the output, like the population distribution per round over time.

Perhaps we could consider one for fixation probabilities (time consuming for some parameters perhaps).

**Comment by drvinceknight** [comment]
> We should have plots for the output, like the population distribution per round over time.

Sounds good.  Perhaps:

```
>>> populations = mp.play()
>>> plot.MoranPlot(populations)
>>> plot.population_distribution()
```

> 
> Perhaps we could consider one for fixation probabilities (time consuming for some parameters perhaps).

Perhaps:

```
>>> repeated_populations = [mp.play() for _ in range(repetitions)]
>>> plot.MoranPlot(*repeated_populations)
>>> plot.population_distribution()
```

So it's essentially the same plot in both cases just that if only one population is passed to it, it will plot the mean distribution over 1 repetition...

I can't think of anything else we'd plot than a population distribution though so perhaps we don't need a `MoranPlot` class but simply an `axelrod.plot.population_distribution` function?

**Comment by marcharper** [comment]
Let's start with a population plot for a single match, could be as simple as
```
>>> populations = mp.play()
>>> mp.plot()
```
or as you suggested above. Maybe a function to compute the fixation probability of a given set of match parameters would also be nice (but not sure if we need a plot).

**Comment by drvinceknight** [comment]
Hmmm... For better or worse what I'm not sure I like about that is that it
is different to how we plot tournament results which is not ideal from a
user's pov. I think I'd prefer to pass the output of the `mp.play` to a
thing that plots (to be in line with the tournament...).

**Comment by drvinceknight** [comment]
> I think I'd prefer to pass the output of the `mp.play` to a
> thing that plots (to be in line with the tournament...).

Perhaps a better way of thinking about this is that a Moran process is closer to a match than a tournament and that the plot of the population distribution would be similar to the sparklines...

```
mp.populations_plot()
```

?

**Comment by marcharper** [comment]
I'm not fussed about the API. IMO the existing plot class is already over-engineered -- I just want a function that makes the plot of interest and returns a matplotlib handle of some kind. So whatever your preference for the API is fine with me.

I do think that a Moran process object is more like a Match than a tournament (I can imagine a tournament of Moran processes) but that's debatable.

**Comment by drvinceknight** [comment]
> So whatever your preference for the API is fine with me.

Cool, let's go for `mp.populations_plot`, which would be the "graphical" version of `mp.populations`.
