### ISSUE TITLE
SlowTitForTwoTats duplicate of TitFor2Tats

### ISSUE THREAD

**Issue by Chadys** [Axelrod-Python/Axelrod#1073]
After poking around titfortat strategies, I found out that `TitFor2Tats` and `SlowTitForTwoTats` do the exact same thing although coded differently. Shouldn't we get rid of `SlowTitForTwoTats` ? And, in that case, should we rename `SlowTitForTwoTats2` ?

> strategies.tifortat : TitFor2Tats : l.68
```python
    @staticmethod
    def strategy(opponent: Player) -> Action:
        return D if opponent.history[-2:] == [D, D] else C
```

> strategies.tifortat : SlowTitForTwoTats : l.517
```python
    def strategy(self, opponent: Player) -> Action:

        # Start with two cooperations
        if len(self.history) < 2:
            return C

        # Mimic if opponent plays the same move twice
        if opponent.history[-2] == opponent.history[-1]:
            return opponent.history[-1]

        # Otherwise cooperate
        return C
```

**Comment by drvinceknight** [comment]
I've taken a quick look (running through an airport) and think I agree. The
fingerprints (https://github.com/Axelrod-Python/Axelrod-fingerprint) look
quasi identical, could you also perhaps just confirm that all the tests
written for one pass for the other?

In terms of renaming, I think we get rid of `SlowTitForTats` (moving it's
name to the list of names in `TitFor2Tats` docstring) and I'd suggest
leaving `SlowTitForTats2` as it is (it has a source with that name).

:+1:

**Comment by Chadys** [comment]
I switched the code of `test_strategy` for the two and yes, tests are passing. I can make the needed changes in the pull request I'll make after adding NTitsForMTats.

**Comment by marcharper** [comment]
Great, let's remove the redundant strategy. Nice catch :)
