### ISSUE TITLE
Specific strategy: Tideman and Chieruzzi

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#1105]
This is one of the remaining strategies from the first tournament and is described here: http://axelrod.readthedocs.io/en/stable/reference/overview_of_strategies.html#tideman-and-chieruzzi:

This strategy begins by playing Tit For Tat and then things get slightly complicated:

1. Every run of defections played by the opponent increases the number of defections that this strategy retaliates with by 1.
2. The opponent is given a ‘fresh start’ if:
        - it is 10 points behind this strategy
        - and it has not just started a run of defections
        - and it has been at least 20 rounds since the last ‘fresh start’
        - and there are more than 10 rounds remaining in the tournament
        - and the total number of defections differs from a 50-50 random sample by at least 3.0 standard deviations.

A ‘fresh start’ is a sequence of two cooperations followed by an assumption that the game has just started (everything is forgotten).

**Comment by dmanc** [comment]
I would like to implement this strategy but I have a couple of questions.

1. Would one defection count as a run of defections?
2. What is the 50-50 random sample?

**Comment by drvinceknight** [comment]
> Would one defection count as a run of defections?

I believe so.

> What is the 50-50 random sample?

My assumption would be that this models the C/D as a draw from the binomial distribution (a coin flip). The probability is .5 (`p`) and the number of samples would be the current turn length (`N`). Using known formulae for the standard deviation we would then have:

```
std_deviation = math.sqrt( N * p * ( 1 - p ) )
```

So I understand this to mean that let's say we have a count of C/D to be 76/74. The total number of turns is 150 thus the standard_deviation is approximately: 6.124. A 50/50 split would imply 75 defections. Thus the unacceptable range would be [75 - 3 * 6.125, 75 + 3 * 6.125]. 

Let me know if I can clarify that further :)

Thanks for picking this up :+1:

**Comment by drvinceknight** [comment]
This seems like a sensible link on the Binomial distribution: http://stattrek.com/probability-distributions/binomial.aspx

**Comment by dmanc** [comment]
Ah that makes sense, thank you.
 I've started working on the strategy and I have come up with some more questions.
1. "and it has not just started a run of defections", would this mean that if there is a run of defections [D, D, D] I will be able to give it a fresh start on the 2nd and 3rd defection given that the rest of the conditions hold?
2. Does a retaliation only occur when this strategy plays C and the opponent plays D?

**Comment by drvinceknight** [comment]
> "and it has not just started a run of defections", would this mean that if there is a run of defections [D, D, D] I will be able to give it a fresh start on the 2nd and 3rd defection given that the rest of the conditions hold?

No my understanding is that "it has not just started a run of defections" means it has just cooperated.

> Does a retaliation only occur when this strategy plays C and the opponent plays D?

Or if both players played D.
