### ISSUE TITLE
Specific strategy: Graaskamp

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#1109]
This strategy is one of the strategies from Axelrod's first tournament. It is described here http://axelrod.readthedocs.io/en/stable/reference/overview_of_strategies.html#graaskamp as:

1. Play Tit For Tat for the first 50 rounds;
2. Defects on round 51;
3. Plays 5 further rounds of Tit For Tat;
4. A check is then made to see if the opponent is playing randomly in which case it defects for the rest of the game;
5. The strategy also checks to see if the opponent is playing Tit For Tat or another strategy from a preliminary tournament called ‘Analogy’. If so it plays Tit For Tat. If not it cooperates and randomly defects every 5 to 15 moves.

Step 4 can be implemented using a chi squared test similarly to the Stein and Rapaport strategy which is implemented here: https://github.com/Axelrod-Python/Axelrod/blob/master/axelrod/strategies/axelrod_first.py#L496

Step 5 is a bit tricky as it refers to a strategy called "Analogy". I have not been able to find any information describing this strategy. I suggest that anyone who tries to work on this does their best to find that information but if there is non available let us simply ignore that part of the check but clearly point that out in the documentation of the strategy.

(Other strategies that we'd like to implement are available here: #379)

Note that this issue was originally at #1051 however that now corresponds to an implementation of a different strategy written by Graaskamp (for Axelrod's second tournament).

**Comment by souravsingh** [comment]
@drvinceknight I am interested in working on the issue.

**Comment by drvinceknight** [comment]
That would be great @souravsingh :+1:

**Comment by souravsingh** [comment]
@drvinceknight I have a question- Is this strategy related to the PR at #1115

**Comment by drvinceknight** [comment]
> @drvinceknight I have a question- Is this strategy related to the PR at #1115

No.

That's related to:

> Note that this issue was originally at #1051 however that now corresponds to an implementation of a different strategy written by Graaskamp (for Axelrod's second tournament).

**Comment by souravsingh** [comment]
The description of the strategy looks very similar to what is written here- https://github.com/Axelrod-Python/Axelrod/issues/1051

**Comment by drvinceknight** [comment]
#1051 started out as this strategy but has since changed to be about a completely different strategy. That is why this issue has been opened.

> Note that this issue was originally at #1051 however that now corresponds to an implementation of a different strategy written by Graaskamp (for Axelrod's second tournament).

**Comment by drvinceknight** [comment]
I think we should implement (and clearly document in the docstring) the following change to rule 5:

> The strategy also checks to see if the opponent is playing Tit For Tat. If so it plays Tit For Tat. If not it cooperates and randomly defects every 5 to 15 moves.

IE it only checks if the opponent is playing TfT. In which case it responds by paying TfT otherwise it cooperates and randomly defects every 5 to 15 moves. I suggest that this late part is implemented as:

> For the 10 moves that happen every 5 to 15 moves the strategy plays randomly.

**Comment by yashaslokesh** [comment]
I've started working on this strategy, this would be my first contribution to OSS.
