### ISSUE TITLE
test_repeat_tournament_stochastic is nondeterministic

### ISSUE THREAD

**Issue by SplitInfinity** [Axelrod-Python/Axelrod#1116]
`test_repeat_tournament_stochastic` in `tests/integration/test_tournament.py` is non-deterministic. It passes sometimes and fails sometimes. While running all of the tests before submitting a PR (#1115), this test failed with the following error message:

```
======================================================================
FAIL: test_repeat_tournament_stochastic (axelrod.tests.integration.test_tournament.TestTournament)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Desktop/Axelrod/axelrod/tests/integration/test_tournament.py", line 96, in test_repeat_tournament_stochastic
    self.assertTrue(filecmp.cmp(files[0], files[1]))
AssertionError: False is not true
```

I ran only this test again and it passed. I don't think my changes should have caused it.

**Comment by drvinceknight** [comment]
> I don't think my changes should have caused it.

This test failed because you don't have a `reset` method in your strategy thus it is conserving state across the matches.
