### ISSUE TITLE
Minor refactor of __init__ and reset

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#1119]
Often we set and clear `Player` attributes in our `__init__` and `reset` methods, resulting in duplicate code and sometimes subtle bugs when we miss something in the `reset` method (or leave it out altogether).

I think it makes sense to have either a special method called something like `set_default_attributes` that handle all the attribute initialization and clearing that is called by the default `reset` method, or that we alter `Player.__init__` to call `reset` by default and set all the variables in the reset method. I prefer the former.

Thoughts?

**Comment by drvinceknight** [comment]
> I prefer the former.
> 
> Thoughts?

This sounds like a good idea to me. I'm happy with either, `set_default_attributes` sounds good.

**Comment by drvinceknight** [comment]
I think there's actually a better way to do this. I've just experimented with modifier the base `axl.Player` class's reset method to:

```python
  244     def reset(self):                                                                                                                            
  245         """Resets a player to its initial state                                                                                                 
  246                                                                                                                                                 
  247         This method is called at the beginning of each match (between a pair                                                                    
  248         of players) to reset a player's state to its initial starting point.                                                                    
  249         It ensures that no 'memory' of previous matches is carried forward.                                                                     
  250                                                                                                                                                 
  251         The default method resets a player's history, cooperations, defections                                                                  
  252         and state_distribution. Players which have further attributes need to                                                                   
  253         override this method and ensure those additional attributes are also                                                                    
  254         reset.                                                                                                                                  
  255         """                                                                                                                                     
  256         self.history = []                                                                                                                       
  257         self.cooperations = 0                                                                                                                   
  258         self.defections = 0                                                                                                                     
  259         self.state_distribution = defaultdict(int)                                                                                              
+ 260         self.__init__(**self.init_kwargs)   
```

Essentially using `self.__init__` as the `set_default_attributes` that you suggested. This has thrown up a couple of failures which I believe are reset bugs (for example `KnowledgeableWorseAndWorse` has no `reset` method). I'll look through the others and open a PR but essentially using this approach (unless people wanted to overwrite) there would be no more need to write a `reset` method on a strategy by strategy basis.

**Comment by marcharper** [comment]
Sounds good to me, as long as we impose a rule that no new attributes can be created outside of `__init__`. [Here's an example](https://stackoverflow.com/questions/3603502/prevent-creating-new-attributes-outside-init).

**Comment by drvinceknight** [comment]
Any particular reason why you think we need this?

**Comment by drvinceknight** [comment]
> as long as we impose a rule that no new attributes can be created outside of __init__.

I've had a quick try and this doesn't immediately work (there are a number of areas where we take advantage of the mutability of Python classes, for example `set_match_attributes` and of course :roll_eyes: our cheating players). I also don't think it's necessary: we have tests for the reset method (in the base `Player` class) specifically for this.

I've opened #1121 which implements a parent `reset` method that works, if we want to go down the line of freezing attributes I suggest that's a separate piece of work (although I don't currently see the problem that it solves). 

Using the `init` in a parent `reset` method is not really changing anything that's not already there, essentially it's what people were having to do anyway when writing a reset method (because of the `reset` tests).

**Comment by marcharper** [comment]
Ideally we don't create new attributes outside of `__init__` so we don't have the same issues with missing or incomplete resets, where an attributes is created and maintains state across resets. If the approach and tests guarantee that won't happen then we don't need to freeze attributes.

Another possibility would be for `reset` to simply use `clone` and make a new instance. It's not as efficient but it would guarantee that no state persisted.

**Comment by drvinceknight** [comment]
Yeah the approach implemented in #1121 ensures nothing persists (it does no worse than what we had before). A little while back when I re wrote the tests for reset a couple of bug of this genre got pointed out but they're not there anymore.

I suggest that goes in and then we can close this issue.

**Comment by drvinceknight** [comment]
I've just tried to quickly use `clone` and as I mentioned above have already tried freezing attributes: they both don't work immediately and require further work.

Whilst I don't believe they're needed (because they haven't been needed until now), I agree that freezing them would be a further way to lock down the reset method **but** I'm not planning on doing that right now. 

Let's merge #1121 because it's a big improvement over the status quo and implements what this issue was about. Then if we want, let's open an issue to freeze attributes so they're only creatable in `__init__` (as I mentioned: that requires more work because of various things we do elsewhere). This feels like the nicer way of doing things.

**Comment by marcharper** [comment]
> Let's review and merge #1121 because it's a big improvement over the status quo and implements what this issue was about. Then if we want, let's open an issue to freeze attributes so they're only creatable in __init__ (as I mentioned: that requires more work because of various things we do elsewhere). This feels like the nicer way of doing things.

Sure. I'm very curious to hear why `clone` doesn't work though -- I would have expected otherwise, and suggests I'm missing something important.

**Comment by drvinceknight** [comment]
> Sure. I'm very curious to hear why clone doesn't work though -- I would have expected otherwise, and suggests I'm missing something important.

I'm taking a quick look, I think what I implemented was stupid (either way it's a nice thing to do on top of #1121).

**Comment by drvinceknight** [comment]
Hmmm... I think it's not a big deal but just plugging it in trips a bunch of tests. At some point I might chase them down.
