### ISSUE TITLE
Add test for memory depth to TestPlayer

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#1156]
All players have a `.classifier["memory_depth"]` attribute that defines their memory depth. 

It would be good to test that this given number is indeed a lower bound on the memory depth of players. I suggest that one way to do this would be to add a method to `TestPlayer` that takes some selection of strategies, and creates a match (seeded it stochastic) and then plays the same match but truncate the opponent and player's memories to `opponent.memory[-memory_depth:]` at each step and verifies that the result is the same.

Something like the following (the `assert` would need to be changed to the corresponding unittest call etc...):

```
def test_memory(player, opponent, seed=None, turns=10):
    
    if seed is not None:
        axl.seed(seed)
    match = axl.Match((player, opponent), turns=turns)
    expected_results = match.play()
    
    player.reset()
    opponent.reset()
    memory = player.classifier["memory_depth"]
    
    results = []
    for _ in range(turns):
        player.history = player.history[-memory:]
        opponent.history = opponent.history[-memory:]
        player.play(opponent)
        results.append(player.history[-1])
    assert results == [interactions[0] for interactions in expected_results], (results, opponent)
```

The opponent could be picked using hypothesis perhaps (but for each strategy this should only pick a small number of opponents?).

Some examples:

```
>>> test_memory(player=axl.TitForTat(), opponent=axl.Alternator())
>>> test_memory(player=axl.TitFor2Tats(), opponent=axl.Alternator())
>>> test_memory(player=axl.Defector(), opponent=axl.Alternator())
```
Note that this would not verify that we have the lowest memory depth: if we declare that the memory depth of a strategy is 5 it might pass this test even though it in fact only needs 2 turns of memory.

I would be impressed if after implementing this test all our strategies pass. I wouldn't be surprised if we have one or two that don't have the correct memory depth. This test would help find them :)

(From discussion on #1155)

**Comment by drvinceknight** [comment]
Have opened #1157.

**Comment by marcharper** [comment]
Nice idea.

In the literature a strategy is memory-N if it only requires the last N rounds of history to work. Ideally this would be independent of the implementation; hopefully the test will catch any such errors. However if IIUC the test won't catch if the memory depth is too large, which is a lesser concern but still a concern I guess. I wonder if we can systematically test (in a one-off notebook perhaps) all the strategies for the "most likely memory depth". Once upon a time I did this for just the memory one strategies and I think your idea here would work -- increment the amount of history until there's no change in behavior for a large number of cases.

There are some weird corner cases I'm sure but hopefully it would catch anything really off.

**Comment by drvinceknight** [comment]
> In the literature a strategy is memory-N if it only requires the last N rounds of history to work.

Yeah although I think we're also talking about wanting the smallest N that gives this condition right? Which, indeed my test doesn't capture...

> Once upon a time I did this for just the memory one strategies and I think your idea here would work -- increment the amount of history until there's no change in behavior for a large number of cases.

This would be great: a nice thing to have in the notebooks repo. Note my test also doesn't necessarily capture the possibility of some internal variables persisting.
