### ISSUE TITLE
Double check axl.Black's rank in docstring

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#1160]
Currently docstring says 14th, however https://github.com/Axelrod-Python/axelrod-fortran/blob/master/src/axelrod_fortran/strategies.py#L278 has it listed at 15.

**Comment by gaffney2010** [comment]
It should say 15; I'll fix it.

**Comment by drvinceknight** [comment]
> It should say 15; I'll fix it.

Thanks for checking, took me 5 secs so I've opened https://github.com/Axelrod-Python/Axelrod/pull/1161 :+1:
