### ISSUE TITLE
`MemoryOnePlayer` default player

### ISSUE THREAD

**Issue by Nikoleta-v3** [Axelrod-Python/Axelrod#1169]
**Question:**

In the generic `MemoryOnePlayer` the following is stated:  https://github.com/Axelrod-Python/Axelrod/blob/47abcc5f33da0cb91d0ce64e0616162f758e8e7f/axelrod/strategies/memoryone.py#L17
Does that mean that the class was suppose to initialise a `four_vector` of (1, 0, 0, 1) if `four_vector` was not given?  

If yes, then this is not implemented. It's an easy fix  **BUT** I am not sure I am interpreting the sentence correctly.

**Comment by drvinceknight** [comment]
I believe you're interpreting that sentence correctly and you've identified a small bug.

The init won't fail if a `four_vector` is not passed but it will not create a valid player: https://github.com/Axelrod-Python/Axelrod/blob/47abcc5f33da0cb91d0ce64e0616162f758e8e7f/axelrod/strategies/memoryone.py#L63

```python
>>> import axelrod as axl
>>> player = axl.MemoryOnePlayer()
>>> player
Generic Memory One Player: C
>>> opponent = axl.TitForTat()
>>> match = axl.Match((player, opponent), turns=10)
>>> match.play()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
```

I suggest we either:

1. Add the intended default behaviour (including a test showing that something like the above code snippet won't fall over).
2. Remove the `default` for `four_vector` (so that `player = axl.MemoryOnePlayer()` would fail and then there's no need for the `if four_vector is not None:`).

I don't feel too strongly either way. Perhaps 2. is cleaner?

**Comment by Nikoleta-v3** [comment]
I agree with 2. 

Should we raise a specific error if the vector is not given like `Transition probabilities not given` ?

**Comment by drvinceknight** [comment]
> Should we raise a specific error if the vector is not given like

We haven't for other classes, so I think just leaving the standard Python error (which would kick in if there are no defaults) would be fine.

**Comment by marcharper** [comment]
Good catch.

Since it's an abstract base player it's not in the standard list of players it's fine to initialize a default to throw an error. I'd suggest adding a warning to the user in the default case.

**Comment by Nikoleta-v3** [comment]
I had a look at the `memoryone.py` file. 

If we choose to give an error when `four_vector` is not initialised (by just removing the `if` statement as suggested by Vince), several players that inherit from `MemoryOnePlayer` are going to break.
That is because of the way the have been implemented. Many of the are first initialised and then passed a `four_vector`. 

**Example 1. WinStayLoseShift**
https://github.com/Axelrod-Python/Axelrod/blob/47abcc5f33da0cb91d0ce64e0616162f758e8e7f/axelrod/strategies/memoryone.py#L111-L113
**Example 2. GTFT**
https://github.com/Axelrod-Python/Axelrod/blob/47abcc5f33da0cb91d0ce64e0616162f758e8e7f/axelrod/strategies/memoryone.py#L173-L181

Would it be okay with you if I alter these classes?
For example WinStayLoseShift would be as follow:

```
 super().__init__(four_vector=(1, 0, 0, 1)) 
 self._initial = initial 
```

**Comment by Nikoleta-v3** [comment]
Also if we decide to have a default player with a message it would be as follow:

```
super().__init__()
 self._initial = initial
if four_vector is None:
    vector = (...)
    warnings.warn('Message')
self.set_four_vector(four_vector)
if self.name == 'Generic Memory One Player':
    self.name = "%s: %s" % (self.name, four_vector)
```

**Comment by drvinceknight** [comment]
> Would it be okay with you if I alter these classes?
> For example WinStayLoseShift would be as follow:

Fine by me.

> Also if we decide to have a default player with a message it would be as follow:

You suggestion looks good to me.
