### ISSUE TITLE
How do you change the payoff values?

### ISSUE THREAD

**Issue by JessieMB** [Axelrod-Python/Axelrod#1186]
Can you change the default payoffs to something else?

**Comment by drvinceknight** [comment]
Hi @JessieMB, this can be done as follows:

```python
>>> chicken = axl.game.Game(r=0, s=-1, t=1, p=-10)
>>> chicken
Axelrod game: (R,P,S,T) = (0, -10, -1, 1)
>>> chicken.RPST()
(0, -10, -1, 1)
```

There is more information about this at the this documentation page: http://axelrod.readthedocs.io/en/stable/tutorials/advanced/games.html

Hope that helps.

**Comment by JessieMB** [comment]
Thanks, just what I needed! :D
