### ISSUE TITLE
Tests fail for matplotlib 3.0.0

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#1209]
This has temporarily been solved by #1208, we should at some point update and lower bound mpl in the requirements.

**Comment by langner** [comment]
And it's still not clear to me whether this discrepancy in `PlotTest` is WAI or a bug in mpl 3.0.0. WDYT?

**Comment by drvinceknight** [comment]
Not too sure, I haven't plotted it with `3.0.0` yet, to see how things look?
