### ISSUE TITLE
ReadME citations not up to date

### ISSUE THREAD

**Issue by Nikoleta-v3** [Axelrod-Python/Axelrod#1211]
Hello! So looking at the `Publications` on the `README.md` they do not seem to be up to date with: https://github.com/Axelrod-Python/Axelrod/blob/master/citations.md.

Could we possibly just redirect people there? @marcharper I know that you are collecting the citations. 
Do you want to let me know how and I can close this issue?

**Comment by marcharper** [comment]
If you prefer redirecting that's fine with me. I was just checking Google Scholar occasionally and wasn't necessarily trying to keep the readme in sync with citations.md.

**Comment by marcharper** [comment]
Speaking of which here are some new ones:
* https://arxiv.org/pdf/1809.10007.pdf
* https://link.springer.com/chapter/10.1007/978-3-030-00350-0_30

and one that cites the strategy list in the docs:
* https://link.springer.com/chapter/10.1007/978-3-319-91467-1_24

**Comment by marcharper** [comment]
Also our [latest paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0204981) is officially live now at PLOS :)
