### ISSUE TITLE
Tests for Fortran reimplementations

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#1230]
We have a number of strategies from Axelrod's original tournaments reimplemented and the original strategies in axelrod-fortran and we test them at review time with fingerprints, which is a reasonably good comparison.

I think it makes sense to go a step further and have hypothesis-based tests to help ensure that
* the implementations are in fact correct
* the implementations don't diverge

**Comment by drvinceknight** [comment]
We currently include tests in `axelrod-fortran` for each implemented strategy (https://github.com/Axelrod-Python/axelrod-fortran/blob/master/tests/test_player.py#L118). I like the idea of testing them again/more somehow here but I am not sure about including the `axelrod-fortran` library as a dev dependency.

**Comment by marcharper** [comment]
Great, I didn't realize we had tests on `axelrod-fortran` for this. If we wanted we could have travis run the tests for `axelrod-fortran` without creating a hard dependency for the use of this library, but that might be more trouble than it's worth.
