### ISSUE TITLE
Page not found error in a link in the readthedoc webpage

### ISSUE THREAD

**Issue by rjsu26** [Axelrod-Python/Axelrod#1247]
in **[reference/Tournaments/Stewart and Plotkin’s Tournament (2012)](https://axelrod.readthedocs.io/en/latest/reference/overview_of_strategies.html#axelrod-s-second-tournament)**  as shown in the snapshot below:
--------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/32229344/61162772-e7a26d00-a527-11e9-8bb5-7c33c95cf088.png)
----------------------------------------------------------------------------------------
The **"available online**" link is giving page not found

**Comment by marcharper** [comment]
Thanks, we'll try to find the correct link. It appears that the journal has moved it.
