### ISSUE TITLE
Hyperlink not implemented well in readthedocs

### ISSUE THREAD

**Issue by rjsu26** [Axelrod-Python/Axelrod#1248]
![image](https://user-images.githubusercontent.com/32229344/61162996-110fc880-a529-11e9-8859-4b0a4e1ab1b0.png)
-----------------------------------
**### The implementation of hyperlink, written as [elsewhere], is not done well. 
Link to page:https://axelrod.readthedocs.io/en/latest/reference/overview_of_strategies.html#hard-tft**

**Comment by marcharper** [comment]
IIRC HARD_TFT is taken from another library (PRISON) in the tournament in the Stewart reference. Are you saying that this is not the original reference? I don't think that prisoners-dilemma.com is the likely origin of the strategy.

**Comment by marcharper** [comment]
BTW, feel free to submit PRs to fix broken links. Thanks for taking interest in the library!

**Comment by rjsu26** [comment]
I meant to say that the way of hyperlink here:
[keyword](its link) 
seems to be erraneous.
It should had been [[keyword](link)]

**Comment by rjsu26** [comment]
> BTW, feel free to submit PRs to fix broken links. Thanks for taking interest in the library!

I am willing to implement those many remaining strategies of the second IPD. Is there anyone else working on that?

**Comment by marcharper** [comment]
You can claim one on #1095. Note that we are able to import the strategies via the original Fortran code. See [here](https://github.com/Axelrod-Python/axelrod-fortran).

**Comment by rjsu26** [comment]
> You can claim one on #1095. Note that we are able to import the strategies via the original Fortran code. See [here](https://github.com/Axelrod-Python/axelrod-fortran).

Okay, working on them.

**Comment by rjsu26** [comment]
> I meant to say that the way of hyperlink here:
> [keyword](its link)
> seems to be erraneous.
> It should had been [[keyword](link)]

please comment on this.

**Comment by marcharper** [comment]
> please comment on this.

The link looks like it's broken. As I said above feel free to submit a PR to fix it, otherwise one of the maintainers will fix it eventually.
