### ISSUE TITLE
Travis is broken

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#1253]
Link to [recent breakage](https://travis-ci.org/Axelrod-Python/Axelrod/jobs/579328517).

**Comment by drvinceknight** [comment]
I've restarted the build but get the same error, the only thing I can find online is: https://travis-ci.community/t/xenial-not-wanting-to-start-xfvb/2397

Perhaps try adding:

```
services:
  - xvfb
```

to the travis.yml file?

Here's a PR that seems to fix this for another project: https://github.com/natritmeyer/site_prism/pull/368/files

**Comment by marcharper** [comment]
Thanks! Looks like that is the fix.
