### ISSUE TITLE
ResultsSet __eq__ fails unexpectedly

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#1286]
Specifically I found an example (2 player tournament with 2 turns) that has `nan` eigenmoses results, and the comparison of `nan` to `nan` fails in `__eq__`.

**Comment by drvinceknight** [comment]
Cool, could you paste the inputs here (assuming it's a specific 2 player tournament).

Tagging #1283 so we know that there might be slight overlap.

**Comment by marcharper** [comment]
It was this test but with only two players and two turns:

```
    @given(seed=integers(min_value=1, max_value=4294967295))
    @settings(max_examples=5, deadline=None)
    def test_seeding_equality(self, seed):
        """Tests that a tournament with a given seed will return the
        same results each time."""
        rng = axelrod.RandomGenerator(seed=seed)
        players = [axelrod.Random(rng.random()) for _ in range(8)]
        tournament1 = axelrod.Tournament(
            name=self.test_name,
            players=players,
            game=self.game,
            turns=3,
            repetitions=100,
            seed=seed
        )
        tournament2 = axelrod.Tournament(
            name=self.test_name,
            players=players,
            game=self.game,
            turns=3,
            repetitions=100,
            seed=seed
        )
        results1 = tournament1.play(processes=2)
        results2 = tournament2.play(processes=2)
        self.assertEqual(results1.ranked_names, results2.ranked_names)
```

**Comment by drvinceknight** [comment]
Ah ok cool, hypothesis should print out the specific inputs for which it failed (it stores them in a db ) when run and we should add that in as a test case when we fix.

**Comment by marcharper** [comment]
I think it's not wrong so much as in that case there were not enough vengeful actions to have a well-defined eigenmoses score, hence the NaN values. We'll just need to check for NaN or == instead of just ==.

**Comment by drvinceknight** [comment]
Yeah sounds like it should be relatively easy to sort out :)
