### ISSUE TITLE
Possible incorrect implementation of Gradual

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#1294]
I've had an email from Jean Paul Delahaye  one of the authors of the original paper from which Gradual was implemented:

> In your code, the strategy is wrong

> https://axelrod.readthedocs.io/en/stable/reference/all_strategies.html#axelrod.strategies.titfortat.Gradual.strategy

> import axelrod as axl
> players = (axl.Defector(), axl.Gradual())
> match = axl.Match(players, 20)
> match.play()
> [(D, C), (D, D), (D, C), (D, C), (D, D), (D, D), (D, C), (D, C), (D, D), (D, D), (D, D), (D, C), (D, C), (D, D), (D, D), (D, D), (D, D), (D, C), (D, C), (D, D)]

> players = (axl.Alternator(), axl.Gradual())
> match = axl.Match(players, 20)
> match.play()
> [(C, C), (D, C), (C, D), (D, C), (C, C), (D, C), (C, D), (D, D), (C, C), (D, C), (C, D), (D, D), (C, D), (D, C), (C, C), (D, C), (C, D), (D, D), (C, D), (D, D)]

> Actually, you have to count during punishment... so we don't have the same thing:
> Here's what it should look like:
> All_D ['D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D'] 40
> gradual ['C', 'D', 'C', 'C', 'D', 'D', 'D', 'D', 'C', 'C', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D'] 15

If I remember correctly @Nikoleta-v3 and I worked together on implementing Gradual. We weren't completely sure about some specific parts of the implementation (from the description in the paper [[Beaufils1997]_](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.42.4041) from https://axelrod.readthedocs.io/en/latest/reference/bibliography.html#bibliography) and reverse engineered a number of possible implementations to match the scores. So when fixing this we should check that the scores reported in the paper still match.

**Note also that the author list is wrong in the bibliography and we have dropped `Philippe Mathieu` from there which we should obviously fix.**

**Comment by marcharper** [comment]
Does the original code still exist?

**Comment by drvinceknight** [comment]
Have asked :+1:

**Comment by Nikoleta-v3** [comment]
In the paper 2  tournaments are reported, a round robin one and an ecological one. I have managed to reproduce the results of the paper for the round robin tournament without altering our implementation of `Gradual`. 

Paper: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.42.4041&rep=rep1&type=pdf

```
>>> import axelrod as axl
>>> import numpy as np

>>> players = [axl.Cooperator(),
           axl.Defector(),
           axl.Random(),
           axl.TitForTat(),
           axl.Grudger(),
           axl.CyclerDDC(),
           axl.CyclerCCD(),
           axl.GoByMajority(),
           axl.SuspiciousTitForTat(),
           axl.Prober(),
           axl.Gradual(),
           axl.WinStayLoseShift()]

>>> axl.seed(1)
>>> tournament = axl.Tournament(players, turns=1000, repetitions=1)
>>> results = tournament.play(progress_bar=False)
>>> np.matrix(results.payoff_matrix)[-2]
matrix([[3.   , 0.915, 2.763, 3.   , 3.   , 2.219, 3.472, 3.   , 2.996,
         2.999, 3.   , 3.   ]])
```

These are normalised scores of `Gradual` against all players. These match the paper's results reported on Table 2 (image attached). The score against `Random` is the only which differs.

<img width="881" alt="Screenshot 2020-03-13 at 11 09 46 PM" src="https://user-images.githubusercontent.com/19708408/76669602-5a1a8f80-6584-11ea-942f-054ad950b1a1.png">

**Comment by drvinceknight** [comment]
Apparently the code is here https://github.com/cristal-smac/ipd, I haven't looked through it et. We don't know if that's the exact same code as the one used for the paper (no archive).

We should test the modification they suggest and see if that gives the same results as well (in which case we should change it). 

If it doesn't we could change the name (perhaps `Gradual -> Gradual96`?)  to reflect that it's the Gradual from that paper? (And add the Gradual described by the authors as well?

**Comment by marcharper** [comment]
How do we square Nik's reproduction with the supposed difference in implementation?

**Comment by drvinceknight** [comment]
> How do we square Nik's reproduction with the supposed difference in implementation?

Two possibilities:

- The strategy with the implementation described in the email gives the same reproduction. This is the easiest case to deal with.
- It does not which would indicate that the strategy used for the reported results was not quite the one they thought it was (the code for the paper might have had a bug in it and perhaps has been fixed since). In this. case we'd just need to clarify that strategy in the library is the one that gives the results in that paper.

But to know that. we need to code up what they describe and see what that does.

**Comment by marcharper** [comment]
Ok, but....

> The strategy with the implementation described in the email gives the same reproduction. This is the easiest case to deal with.

that seems unlikely though given that Defector / ALLD is in the tournament. I guess we'll find out!

**Comment by drvinceknight** [comment]
Ah yes good point. Let's see but yeah very unlikely... I'll go back to the author when we've run our own implementation.

**Comment by drvinceknight** [comment]
So here's a modified `Gradual`, it's actually based super closely on the code in their repo (see docstring for links):

```python
C, D = axl.Action.C, axl.Action.D

class ModifiedGradual(axl.Player):
    """
    Modification of https://github.com/Axelrod-Python/Axelrod/blob/master/axelrod/strategies/titfortat.py#L433 
    to reflect "count during punishment"
    
    Based on the logic that appears here: https://github.com/cristal-smac/ipd/blob/master/src/strategies.py#L224   
    
    Looking at https://github.com/cristal-smac/ipd/blob/master/src/ipd.py#L37 the update methjod of the strategy 
    is called after the actions
    """
    def __init__(self) -> None:

        super().__init__()
        self.calm_count = 0
        self.punish_count = 0
        self.punishment_limit = 0

    def strategy(self, opponent: axl.Player) -> axl.Action:

        if len(self.history) == 0:
            return C
        
        
        if self.punish_count > 0:
            self.punish_count -= 1
            return D
        
        if self.calm_count > 0:
            self.calm_count -= 1
            return C
        
        if opponent.history[-1] == D:
            self.punish_count = opponent.defections
            self.calm_count = 2
            return D
        return C
    
    
    def _update_limit(self, opponent):
        if opponent.history[-1] == D:
            self.punishment_limit += 1


```

If we run this against `Defector` we get the output as described in the email:

```python
>>> match = axl.Match(players=(ModifiedGradual(), axl.Defector()), turns=50)
>>> interactions = match.play()
>>> interactions
[(C, D),
 (D, D),
 (D, D),
 (C, D),
 (C, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (C, D),
 (C, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (C, D),
 (C, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D)]
```

However if we run the same tournament as @Nikoleta-v3 did above:

```python
>>> players = [axl.Cooperator(),
           axl.Defector(),
           axl.Random(),
           axl.TitForTat(),
           axl.Grudger(),
           axl.CyclerDDC(),
           axl.CyclerCCD(),
           axl.GoByMajority(),
           axl.SuspiciousTitForTat(),
           axl.Prober(),
           axl.Gradual(),
           axl.WinStayLoseShift()]

>>> axl.seed(1)
>>> tournament = axl.Tournament(players, turns=1000, repetitions=1)
>>> results = tournament.play(progress_bar=False)
>>> np.matrix(results.payoff_matrix)[-2]
matrix([[3.   , 0.985, 2.904, 3.   , 3.   , 2.304, 3.599, 3.   , 2.994,
         2.998, 3.   , 3.   ]])
```

the results no longer match.

I'll drop this in an email to the author and see what they say but I suggest we just add something to the docstring highlighting that the implemented strategy is the one that reproduces the results of the paper.

**Comment by pmathieufr** [comment]
Dear all, some details about Gradual 
First it cooperates, then as soon as the other one betrays, it betrays as many times as it have been betrayals in the past, then it cooperates twice.
Against Defect : 
gradual  C D C C D D D D C C D D D D D D D D D D C C D D D D D D D D D D D D D D D D D D D D D D C C D D D D   ... 983

per_D    D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D   .... 1068

So there's clearly an error in your previous code.
On the other hand, it seems you're right, there is also an error in my 1996 paper.
I re-run this tournament (removing Random, which is non-deterministic and therefore distorts the results). Here it is :

<img width="769" alt="Capture d’écran 2020-03-16 à 20 36 33" src="https://user-images.githubusercontent.com/20242612/76793958-5d9d5900-67c6-11ea-8b4f-39852853498a.png">

**Comment by drvinceknight** [comment]
> So there's clearly an error in your previous code.

My mistake: it looks like I'd pasted the interactions incorrectly:

```
>>> match = axl.Match(players=(ModifiedGradual(), axl.Defector()), turns=50)
>>> interactions = match.play()
>>> interactions
[(C, D),
 (D, D), # 1 defection as a response to the 1 defection by opponent
 (C, D),
 (C, D),
 (D, D), # starts defecting after a total of 4 defections by the opponent
 (D, D),
 (D, D),
 (D, D), # 4 defections
 (C, D),
 (C, D),
 (D, D), # Start defecting after a total of 10 defections by the opponent
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),  # 10 defections
 (C, D),
 (C, D),
 (D, D), # starts defecting after 22 defections by the opponent
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D), # 22 defections
 (C, D),
 (C, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D)]
```

Looking at the tournament scores you posted 
here it is again with the same ordering as yours:

```python
>>> players = [
           ModifiedGradual(),
           axl.TitForTat(),
           axl.GoByMajority(),
           axl.Grudger(),
           axl.WinStayLoseShift(),
           axl.Prober(),
           axl.Defector(),
           axl.SuspiciousTitForTat(),
           axl.Cooperator(),
           axl.CyclerCCD(),
           axl.CyclerDDC(),
]

>>> axl.seed(1)
>>> tournament = axl.Tournament(players, turns=1000, repetitions=1)
>>> results = tournament.play(progress_bar=False)
>>> np.matrix(results.payoff_matrix)[0]
matrix([[3.   , 3.   , 3.   , 3.   , 3.   , 2.999, 0.983, 2.996, 3.   ,
         3.596, 2.302]])
```

We still get a mismatch of results in against `SuspiciousTitForTat` which corresponds to `mistrust` but everything else matches. Perhaps `SuspiciousTitForTat` is not the same as your current `mistrust` (although it did match your published results).

I'll open a PR to update the docstring of `Gradual`  to make it clear that there's an error in the 1996 paper and that the description does not match the behaviour of `Gradual` described elsewhere.

We can also add this "newer"/"corrected" Gradual at some point. Is there another set of published results that uses the "newer"/"correct" one? We can refer to them.

**Comment by drvinceknight** [comment]
> We still get a mismatch of results in against `SuspiciousTitForTat` which corresponds to `mistrust` but everything else matches. Perhaps `SuspiciousTitForTat` is not the same as your current `mistrust` (although it did match your published results).

Looking at https://github.com/cristal-smac/ipd/blob/master/src/strategies.py#L147 your current mistrust if not our `SuspiciousTitForTat` but it corresponds to a memory one strategy with four vector: `(1, 0, 0, 0)` and opening move `D`.

Running the tournament with that and the modified `Gradual` gives:

```python
>>> mistrust = axl.MemoryOnePlayer(initial=D, four_vector=(1, 0, 0, 0))
>>> players = [
           ModifiedGradual(),
           axl.TitForTat(),
           axl.GoByMajority(),
           axl.Grudger(),
           axl.WinStayLoseShift(),
           axl.Prober(),
           axl.Defector(),
           mistrust,
           axl.Cooperator(),
           axl.CyclerCCD(),
           axl.CyclerDDC(),
]

>>> axl.seed(1)
>>> tournament = axl.Tournament(players, turns=1000, repetitions=1)
>>> results = tournament.play(progress_bar=False)
>>> np.matrix(results.payoff_matrix)[0]
matrix([[3.   , 3.   , 3.   , 3.   , 3.   , 2.999, 0.983, 0.983, 3.   ,
         3.596, 2.302]])
```

Now the results match yours.

Out of curiosity, I ran the same tournament with our original `Gradual` to see how this changed from the 1996 paper (I'm using the same ordering as in that paper):

```
>>> players = [axl.Cooperator(),
           axl.Defector(),
           axl.Random(),
           axl.TitForTat(),
           axl.Grudger(),
           axl.CyclerDDC(),
           axl.CyclerCCD(),
           axl.GoByMajority(),
           mistrust,
           axl.Prober(),
           axl.Gradual(),
           axl.WinStayLoseShift()]

>>> axl.seed(1)
>>> tournament = axl.Tournament(players, turns=1000, repetitions=1)
>>> results = tournament.play(progress_bar=False)
>>> np.matrix(results.payoff_matrix)[-2]
matrix([[3.   , 0.915, 2.763, 3.   , 3.   , 2.219, 3.472, 3.   , 0.915,
         2.999, 3.   , 3.   ]])
```

then we obviously still get the correct score against `Defector` but now also get a mismatch against `mistrust`. This looks to me that your `mistrust` strategy in the 1996 paper is also not the same as your current `mistrust` strategy.

**Comment by marcharper** [comment]
I would be in favor of the following:

* Keep the existing Gradual (perhaps rename it) and add the "correct" one so that we can reproduce the 1996 tournament
* Document along side the other tournaments this reproduction, and the issues that arose described above
* Add the latest version of mistrust, if desired

**Comment by drvinceknight** [comment]
> * Keep the existing Gradual (perhaps rename it) and add the "correct" one so that we can reproduce the 1996 tournament

Can I clarify @marcharper: the current Gradual is the one that reproduces the 1996 results in the paper. Is that what you meant? 

I agree that we should definitely keep the current one, it's just a question of which name to we change:

1. We end up with `Gradual` (the current one that reproduces the 1996 paper results) and `ModifiedGradual` (the one I've coded in this issue)
2. We end up with `LegacyGradual` (tthe current one that reproduces the 1996 paper results) and `Gradual` (the one I've coded in this issue)



Given the title of the 1996 paper (which is to introduce `Gradual`) I think I'm slightly learning towards option 1 but I'm not too precious.

In either scenario, in both strategies we should clearly document a summary of this discussion and point to this issue.


> * Document along side the other tournaments this reproduction, and the issues that arose described above

Good idea, what were you thinking in `axelrod-tournament` or as a tutorial in our documentation?



> * Add the latest version of mistrust, if desired

**Comment by drvinceknight** [comment]
I'll close #1296 for now until we've decided what way to go :)

**Comment by marcharper** [comment]
I'm not too concerned about the names as long as they are well-documented.

For the tournament reproduction I was thinking [here](https://github.com/Axelrod-Python/Axelrod/blob/master/docs/reference/overview_of_strategies.rst) maybe? or as a tutorial?

**Comment by drvinceknight** [comment]
> I'm not too concerned about the names as long as they are well-documented.

:+1:

> 
> For the tournament reproduction I was thinking [here](https://github.com/Axelrod-Python/Axelrod/blob/master/docs/reference/overview_of_strategies.rst) maybe? or as a tutorial?

Yeah there is a good idea :+1:

**Comment by drvinceknight** [comment]
I just remembered that we had documented some of this before but in the test for `Gradual`: https://github.com/Axelrod-Python/Axelrod/blob/master/axelrod/tests/strategies/test_titfortat.py#L459

We have the following unit test:

```
    def test_output_from_literature(self):
        """
        This strategy is not fully described in the literature, however the
        following two results are reported in:
        Bruno Beaufils, Jean-Paul Delahaye, Philippe Mathie
        "Our Meeting With Gradual: A Good Strategy For The Iterated Prisoner's
        Dilemma" Proc. Artif. Life 1996
        This test just ensures that the strategy is as was originally defined.
        """
        player = self.player()

        opp1 = axelrod.Defector()
        match = axelrod.Match((player, opp1), 1000)
        match.play()
        self.assertEqual(match.final_score(), (915, 1340))

        opp2 = axelrod.CyclerCCD()
        match = axelrod.Match((player, opp2), 1000)
        match.play()
        self.assertEqual(match.final_score(), (3472, 767))
```

**Comment by drvinceknight** [comment]
I'll pick this up.

**Comment by drvinceknight** [comment]
I've opened https://github.com/Axelrod-Python/Axelrod/pull/1299
