### ISSUE TITLE
Moving CI to GitHub actions

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#1297]
I've moved all my CI to [GitHub actions](https://github.com/features/actions) for some of my other repos. For example https://github.com/drvinceknight/Nashpy.

---

Advantages:

- Testing across multiple OSs in one spot (less moving parts so less maintenance)
- Seems to be faster

Disadvantages:

- We would no longer have a coveralls 100% badge in the README. Warning: if anyone wants to spend time to get this to work on GitHub actions my advice to you is do not: hours hours and hours of my time have been lost. We would still of course have coverage less than 100% fail the CI we just wouldn't use a fancy service that essentially only actually gives us a badge.

---

I would like to do the same for the Axelrod repository. This certainly fits under the "it's not broken right now so why fix it" proposal but with the various moving parts of our CI I have in the past spent a lot of time fixing things whereas GitHub actions seems a bit more robust and it's also all in one spot.

Let me know what you think. if there's no objection I'll open a PR which will kick in the GitHub actions CI and remove the other CI. (I'll add commits with various failures to make sure we get the same level of granularity we currently have)

**Comment by meatballs** [comment]
Seems a damned fine idea and I couldn't really care less about the badge.

**Comment by marcharper** [comment]
SGTM. We could always manually insert the badge image since we enforce 100% coverage.

**Comment by drvinceknight** [comment]
Good idea!

**Comment by marcharper** [comment]
Maybe out of scope but the main github page for the library might benefit from a light once-over. Maybe move the link to the docs higher, update the maintainers ...
