### ISSUE TITLE
Is that possible to use that library for public good games?

### ISSUE THREAD

**Issue by Erenhub** [Axelrod-Python/Axelrod#1298]
Hi,

I'm just wondering if there is any option to change the payoff matrix in order to use this library for other games rather than just prisoners dilemma.

I tried to update game.py but get some error, is there any shortcut to do this?

Regards.

**Comment by Erenhub** [comment]
apperantly i can, sorry

**Comment by marcharper** [comment]
Hi, it's something we're planning for a 5.0.0 version -- more games and game types. Can you say more about what you want to do, explicitly?

**Comment by Erenhub** [comment]
Hi Marc, thanks for returning this message.

I was planning to model a new game which was mainly about social contract between individuals about coronaspread, however i decided to stick with public good game model, which is more easier than creating a new model.

I am open to discuss new ideas as a researcher in complex systems,

Regards.

**Comment by drvinceknight** [comment]
A smile aside: in case you haven't seen this, if you want to change the values of R,S,P,T used in the stage game, there's information on how to do this here: https://axelrod.readthedocs.io/en/stable/tutorials/advanced/games.html

**Comment by marcharper** [comment]
Generically we don't have multiplayer public good in the library that would be split across multiple users; that would be a new game type. OTOH you could use a PD game in a Moran process (e.g. cooperate is to physically distance) and see what the maximum subpopulation size of defectors grows to before the cooperators supress it (if possible).

Can you describe what kind of model you had in mind in more detail?

**Comment by Erenhub** [comment]
Hi. Sorry for the late delay, I was dealing adapting to remote working.

I want to analyse different scenarios of spread between people under different strategies such as social distancing, herd immunity or mixed.I just tried it between 2 agents for fun

As far as i remember moran process is regarding to population, which i am interested here is payoff of the individuals and their strategies. As you told multiplayer public good is a good idea!

if you have any other ideas about implementiotion I am excited to hear !!

Thanks.

**Comment by marcharper** [comment]
See #1298 for a more general discussion.
