### ISSUE TITLE
Test (and improve) the packaging

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#130]
So there is now a packaged version of `axelrod` available via `pip`. This is all from the `packaging` branch and this issue is to discuss any issues before merging in to master and making things 'official' :)

To test, I suggest creating a virtualenv as this will install 'system wide':

```
virtualenv tmp-axelrod2 # I had about 7 of these going as I as testing and am just about to tear them down
cd tmp-axelrod2 # Go to that directory
source bin/activate  # (depending on your shell this might need a tweak)
```

Type the following just to make sure that you have got a virtualenv:

```
which pip
```

Install through the magics of the internetz:

```
pip install axelrod
```

Note that that pulls down `matplotlib` also (which if you're in the virtualenv you will notice).

Now to run the tournament I have made some tweaks (see the `packaging` branch).
Firstly I've renamed the `run_tournament.py` script to `run_axelrod` as `pip` now installs this as an executable file system wide.

So below will run the very basic tournament:

```
run_axelrod --xs --xc --xa --ne
```

One thing that will need work on this branch before pulling in to `master` will be updating the documentation.

**Comment by drvinceknight** [comment]
One of the other changes that I've made is that output is by default in the current directory.

(Owen: I think we need to have a command line argument that points at a `cache.txt` file.)

**Comment by drvinceknight** [comment]
(I also don't like that the authors are just down as me, does anyone know what the done thing is here?)

**Comment by meatballs** [comment]
http://stackoverflow.com/questions/9999829/how-to-specify-multiple-authors-emails-in-setup-py

**Comment by meatballs** [comment]
> I suggest creating a virtualenv as this will install 'system wide':

In case it helps anyone else, this repo: https://github.com/meatballs/dotfiles contains my dotfiles setup which will download and configure the zsh shell with a heap of useful plugins - one of which will auto-activate a virtualenv when you cd into the directory (and then show the active environment in the prompt)

**Comment by drvinceknight** [comment]
Have added @langner and @meatballs as authors: https://pypi.python.org/pypi/Axelrod

Will need to clean up the readme or write a `long_description.rst` file at some point...

**Comment by drvinceknight** [comment]
@meatballs if you're happy (I just merged #134) with the general structure of this, I'll go ahead and start working on a proper PR with updated docs etc... (and we can announce it once that's in :)).

**Comment by meatballs** [comment]
Yep. Sounds good to me. Merging the changes to run_tournament.py now that it's been renamed might be fun

**Comment by drvinceknight** [comment]
Eeeeeek... I'm sure I'll bumble my way through it :)
