### ISSUE TITLE
Add a timed weekly/monthly (?) build?

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#1317]
With GitHub actions it's relatively simply to run a timed build of the CI. This would potentially alert us to bugs that appears as other libraries update. Here is an example of a weekly build on one of 
my class repos: https://github.com/drvinceknight/cfm/blob/master/.github/workflows/config.yml#L7

I don't necessarily think we need this but it's a relatively simple thing to implement. Any thoughts?

**Comment by meatballs** [comment]
If it's simple to do, why not? It gives a bit of warning that something has gone wrong.

**Comment by drvinceknight** [comment]
What do you reckon, monthly? Weekly?

**Comment by meatballs** [comment]
Weekly seems ok to me.

**Comment by drvinceknight** [comment]
Cool, I'll throw that in a PR.
