### ISSUE TITLE
Run isort utility on all files

### ISSUE THREAD

**Issue by gaffney2010** [Axelrod-Python/Axelrod#1326]
Similar to #1312.  The contribution guidelines should say this should be run on every file.  We can run on all files and possibly add a check.

**Comment by drvinceknight** [comment]
There might be a slight problem that arises, in my experience on other projects checking isort and black sometimes don't seem to agree (if I recall). If it works though I'm 100% in favour (and will need to go back to my other projects...)! (If we have to choose I think we go with black).

**Comment by akash-suresh** [comment]
Hey! Can I pick this up? 😄 

I have used `isort`, in one of my earlier projects. And this seems like a fairly simple task to get acquainted with the codebase.

**Comment by drvinceknight** [comment]
Please do :+1:

**Comment by akash-suresh** [comment]
Hey @drvinceknight, I tried running the unit-test suite to make sure, its setup properly. A few of the test cases are failing. I am using Python 3.8.

**Comment by drvinceknight** [comment]
Yeah there are a couple of tests that don't pass yet on py3.8 (https://github.com/Axelrod-Python/Axelrod/issues/1315). If you setup a virtual environment with py3.7 you should be fine.

**Comment by akash-suresh** [comment]
Oh alright. Thanks for the clarification. 👍
