### ISSUE TITLE
How does Moran.py converge every time?

### ISSUE THREAD

**Issue by Erenhub** [Axelrod-Python/Axelrod#1348]
Hi, 

I want to ask an academic question, How did you manage that each moran process to converge in your code?

Thanks in advance.

**Comment by marcharper** [comment]
(1) Mathematically, if the mutation is the transitional kind, one player type will eventually dominate the population. The process exits when one type fixates. Technically this could take an arbitrarily long time, but for practical population sizes it will converge.

The "atomic" mutation type is not guaranteed to converge.

(2) The payoffs are determined by the outcome of matches, so any change to the Match parameters, such as turn length, may alter the payoffs. This could alter the fixation probabilities of the process, but small changes in the turn number, particularly if it is already large, are unlikely to have a substantial impact.
