### ISSUE TITLE
The meaning of Ecological Variant

### ISSUE THREAD

**Issue by Erenhub** [Axelrod-Python/Axelrod#1349]
Hi,

I created a new game and tested the cooperator and defector strategies. I used to eco.reproduce(200) function in order to analyse ESS and get this table:

![ecologialvariant](https://user-images.githubusercontent.com/47353633/83289377-a40f2b00-a1ed-11ea-8c4a-5cab1eac0cf3.png)

But i am still not sure if that means ''Defection'' strategy became Evolutionary Stable after 200 iteration?

Thanks in advance

**Comment by Erenhub** [comment]
++ what could be the reason when i use Moran.py  for 2 defector and 18 cooperator i only have 20 cooperator left after 57 iteration

**Comment by marcharper** [comment]
The ecological model is from R. Axelrod's original work, IIRC. In the picture above Defector eventually took over the population (but that doesn't mean that it's evolutionarily stable as a strategy, just that it won this particular time).

The Moran process is a subsequently developed model. It won't match the output of this ecological model.
