### ISSUE TITLE
Log Levels and Messages

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/Axelrod#135]
* Add an argument to run_tournament to control the log level that's displayed.
* Consider whether the existing log messages should be debug or info level and change as appropriate.
* Add some messages at the start of tournament manager, mainly for the benefit of file logging

**Comment by drvinceknight** [comment]
Sounds cool. I'm guessing you can label these now?

**Comment by meatballs** [comment]
Seems I can!
