### ISSUE TITLE
Add a citation.cff file

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#1392]
Looks like Github now lets you add a citation file which creates a nice `Cite this repository` widget.

https://twitter.com/natfriedman/status/1420122675813441540

**Comment by drvinceknight** [comment]
Info about the citation.cff file format here: https://citation-file-format.github.io

**Comment by VartanAhrensKayayan** [comment]
I can create the citation file. But I need to know does Axelrod want to be cited? Is there a published paper you wish to refer to or a few major contributors that the code can attributed to?

**Comment by meatballs** [comment]
https://github.com/Axelrod-Python/Axelrod/blob/master/CITATION.rst

**Comment by VartanAhrensKayayan** [comment]
Ok, I created the CITATIONS.cff. See #1405.

**Comment by drvinceknight** [comment]
I've set the CI going. Thanks for your patience :)

**Comment by VartanAhrensKayayan** [comment]
The citation file has been added, maybe this should be closed?
