### ISSUE TITLE
Expressing in a formal logical language

### ISSUE THREAD

**Issue by blokhin** [Axelrod-Python/Axelrod#1425]
Dear experts, is it possible to express at least a limited subset of a prisoner’s dilemma in a formal language, e.g. SAT, TPTP, LISP, or maybe even OWL?

**Comment by blokhin** [comment]
I could see the following quite preliminary attempts so far:

- [Lisp](https://www.tobiasthelen.de/ipd/lisp.html) by T. Thelen, 1997
- [Lisp](https://nullprogram.com/blog/2007/11/06/) by C. Wellons, 2007
- ([Haskell and Scala](https://github.com/jpfuentes2/iterated-prisoners-dilemma) by @jpfuentes2, 2014)

**Comment by drvinceknight** [comment]
Hi @blokhin, I'm afraid I'm not too familiar with those languages.
