### ISSUE TITLE
I couldn't find the strategy submitted by Mauk in the competition for 19th place

### ISSUE THREAD

**Issue by ZhengyeHan** [Axelrod-Python/Axelrod#1427]
In the file shown below, there are strategies that show the 18th and the 20th, but there is no strategy that shows the 19th. I can't find it by searching according to the author's name "Mauk"
![05743f64bdce95796048fd6005b4aa9](https://github.com/Axelrod-Python/Axelrod/assets/111236370/7fff47fb-a956-47df-a655-e6c61e5fe79e)

**Comment by ZhengyeHan** [comment]
In addition, according to the paper, there were 63 strategies in that game, but I only saw more than 20 strategies in this file. Did you not write all the code of the strategies, or did you write the strategies in another place？

**Comment by marcharper** [comment]
The closest we have to the original strategies are from a test tournament in Fortran, available in the [axelrod-fortran](https://github.com/Axelrod-Python/axelrod-fortran) library. We are not aware of any copies of the original source code for the tournament run in Axelrod's second tournament.

The strategies in this file are the ones we've been able to find enough documentation on to re-implement (and had the time and inclination to do so). Note that some strategies like Tit-For-Tat are in other files.
