### ISSUE TITLE
If I want to test the first tournament, what should I do based on your code？

### ISSUE THREAD

**Issue by ZhengyeHan** [Axelrod-Python/Axelrod#1429]
The players in the first tournament are as follows：
![5cac8e504768ae38363035ae844b3ed](https://github.com/Axelrod-Python/Axelrod/assets/111236370/cef3f6eb-b208-411c-a677-e3208fd9400b)

**Comment by Nikoleta-v3** [comment]
Hello @623637719  👋🏻  On the [online documentation](https://axelrod.readthedocs.io/en/stable/index.html) we have details on how to run Axelrod's original tournament: https://axelrod.readthedocs.io/en/stable/tutorials/running_axelrods_first_tournament/index.html.

**Comment by ZhengyeHan** [comment]
> Hello @623637719 👋🏻 On the [online documentation](https://axelrod.readthedocs.io/en/stable/index.html) we have details on how to run Axelrod's original tournament: https://axelrod.readthedocs.io/en/stable/tutorials/running_axelrods_first_tournament/index.html.

thank you！please close this
