### ISSUE TITLE
Do you know the source code of the first tournament?

### ISSUE THREAD

**Issue by ZhengyeHan** [Axelrod-Python/Axelrod#1430]
May I ask if you know where is the source code of the first tournament? I can find the fortran [source code](http://www-personal.umich.edu/~axe/research/Software/CC/CC2/TourExec1.1.f.html) of the second tournament, but I can't find the source code of the first tournament

**Comment by meatballs** [comment]
No, we've never managed to lay our hands on that.

**Comment by ZhengyeHan** [comment]
> No, we've never managed to lay our hands on that.

thank you！please close this.
