### ISSUE TITLE
Change the TFT in the first tournament

### ISSUE THREAD

**Issue by ZhengyeHan** [Axelrod-Python/Axelrod#1432]
I ran the code for the first tournament in the following way.
```python
import axelrod as axl
first_tournament_participants_ordered_by_reported_rank = [s() for s in axl.axelrod_first_strategies]
tournament=axl.Tournament(players=first_tournament_participants_ordered_by_reported_rank,turns=200,repetitions=5,seed=1, )
results = tournament.play()
```

 if I wanted to run it locally, in this tournament, I had TFT choose defection in the last two rounds. how should I change the code?

**Comment by ZhengyeHan** [comment]
@drvinceknight

**Comment by marcharper** [comment]
Are you asking how to make TFT defect in the last two rounds? You can use one of the strategy transformers to modify the TFT strategy to do so. See the documentation for how to achieve this.

**Comment by ZhengyeHan** [comment]
> Are you asking how to make TFT defect in the last two rounds? You can use one of the strategy transformers to modify the TFT strategy to do so. See the documentation for how to achieve this.

![image](https://github.com/Axelrod-Python/Axelrod/assets/111236370/2ee69614-f202-40f4-912d-fa3c69659936)
done.thank you
