### ISSUE TITLE
High-noise Tournament for comparison

### ISSUE THREAD

**Issue by BradKML** [Axelrod-Python/Axelrod#1434]
Calling back on previous notes, other than a 5% noise ration for the tournament, can a rematch be done for 10% or even 20% of noise (and then compare rankings change)? https://github.com/Axelrod-Python/tournament/issues/7
Source for the larger set: https://axelrod-tournament.readthedocs.io/en/stable/noisy/strategies.html
Older source with the 5% test: https://axelrod-tournament.readthedocs.io/en/latest/noisy/index.html

Side note: tweaking turn count to either 50, 100 (lower end), 500, or 1000 (higher end) instead of 200 might trip some strategies up as well

**Comment by marcharper** [comment]
You can easily do all these things with the library. Most newer strategies don't care about the game length, but the older tournament strategies sometimes hard code specific rounds in which to change behavior. Most of the literature avoids high noise levels -- high noise tends to have a smoothing effect that isn't particularly interesting and few strategies are designed for such high noise levels.
