### ISSUE TITLE
LimitedHistory should override extend.

### ISSUE THREAD

**Issue by gaffney2010** [Axelrod-Python/Axelrod#1451]
[LimitedHistory](https://github.com/Axelrod-Python/Axelrod/blob/dev/axelrod/history.py#L107) inherits extend from [base class](https://github.com/Axelrod-Python/Axelrod/blob/dev/axelrod/history.py#L50).  However expected behavior is that LimitedHistory only keeps the last `memory_depth` history.

Should make this unittest on TestLimitedHistory pass.
```
    def test_extend(self):
        h1 = LimitedHistory(3, plays=[C, C, D], coplays=[C, C, C])
        self.assertEqual(list(h1), [C, C, D])
        h1.extend([C, C], [D, D])
        self.assertEqual(list(h1), [D, C, C])
```

**Comment by LindyZh** [comment]
Hi! Just wondering if anyone is currently working on this? I would love to contribute 😃

**Comment by gaffney2010** [comment]
> Hi! Just wondering if anyone is currently working on this? I would love to contribute 😃

It's all yours.
