### ISSUE TITLE
Major change suggested: minimisation -> maximisation

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#148]
I think I made an initial mistake with the setup. I would like to make the default game be more in line with a lot of the literature I have been reading recently. This is one in which the players aim to maximise payoffs and not minimise (so the game values change in term).

The payoff matrix would become:

+-----+-----+
|(3,3) |(0,5)|
+-----+------+
|(5,0) |(1,1)|
+-----+------+

The main reason to do this change would be to be in line with the literature if and when we wanted to write an academic paper.

I do not feel that this would be a lot of work (as everything has been built in a modular way and nothing actually takes count of the score until the very end):

- Change payoff matrix in game
- Change mapping function in ecological variant
- (potentially change ordering of the strategies as displayed by plots in `run_axelrod`)

Let me know what everyone thinks.

**Comment by langner** [comment]
This baffled me when I looked at the code, although in principle it makes no difference.

**Comment by drvinceknight** [comment]
Yeah it would indeed make no difference. It's just a question of esthetics
and convention...

**Comment by drvinceknight** [comment]
@meatballs can you let me know what you think about this? Hoping to find some time over the next couple of days to put this in place but just want to make sure that you don't have any big opposition to it.

**Comment by meatballs** [comment]
I'm out and about today but should be able to have a look tomorrow

**Comment by drvinceknight** [comment]
No problem :) (No code to look at, just your opinion on the idea of changing from min to max)

**Comment by meatballs** [comment]
Can't see any problem with this at all

**Comment by drvinceknight** [comment]
Cool: I'll get working on it over the next couple of days.

**Comment by meatballs** [comment]
Might need to put a comment on Artem Kaznatcheev's blog once this goes in - his stuff explaining the differences will be out of date

**Comment by drvinceknight** [comment]
Yeah, I was thinking that :) I've just opened the PR so as soon as we've
worked through it (I might have missed some stuff) one of us should do that
:)
