### ISSUE TITLE
Bug in Q-learners

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#157]
@geraintpalmer has told me that apparently the Q-learners were not written as well as they should have been so the recent change from min to max will have broken them.

**Comment by meatballs** [comment]
Do we know what the nature of this bug it yet?

**Comment by drvinceknight** [comment]
@geraintpalmer does... He did explain it to me but I forget the details...
Geraint can you go over it?

I know that for one the game scores are hard coded and don't use the game
object. Also I think they're still working on minimisation...

**Comment by geraintpalmer** [comment]
Yes the payoff matrix is hard coded into the strategy.

At the time the payoff matrix was a min, but q-learners need to max, so I did something like 5-i for each i in payoff matrix.

**Comment by drvinceknight** [comment]
Are you going to have any time to work on this at some point
@geraintpalmer? (No problem if not, not your priority)

**Comment by marcharper** [comment]
I've updated the game matrix and modified the tests and a few other things. @geraintpalmer Will the strategy work properly with max and the right game matrix? If so, please take a quick look.

**Comment by drvinceknight** [comment]
I'll try and get @geraintpalmer to take a look.
