### ISSUE TITLE
Numpy Revisited

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/Axelrod#158]
Given that this is now published on PyPi with full dependency management, should we rethink the decision not to use Numpy?

It could easily be added as a dependency so that pip install axelrod will also ensure that numpy is available.

**Comment by meatballs** [comment]
Also - since matplotlib is already a dependency at PyPi, numpy is already being installed. I'd say we might as well use it.

**Comment by drvinceknight** [comment]
I'd still like to stay away from Numpy. The numerics we're doing don't really make this too heavy and at present a user can download the zip file and run everything from there with nothing else (the matplotlib stuff is all optional).

**Comment by meatballs** [comment]
It's just a suspicion on my part, but I wonder if numpy's  array representation might give us a performance improvement. There's a cython tutorial here: https://python.g-node.org/python-summerschool-2011/_media/materials/cython/cython-slides.pdf which talks about the boxing/unboxing issue and specifically mentions numpy arrays.

I also suspect that users who aren't too comfortable are more likely to use pip install rather than downloading a zip file.

In the end for me it comes down to whether or not the performance improvement is there and  I don't have evidence either way. It possibly needs some work to compare the speeds with and without.

**Comment by drvinceknight** [comment]
> I also suspect that users who aren't too comfortable are more likely to use pip install rather than downloading a zip file.

That's an excellent point...

**Comment by drvinceknight** [comment]
Just to add to this discussion (although as I said above I think your latest point makes me much more in favour of the idea). This weekend at a hackathon I had a nightmare attempting to get numpy (more precisely scikit learn which depends on numpy) to run nice on travis. This might have just been that I didn't have time to think through it properly but just putting this out there for us to think about.

**Comment by marcharper** [comment]
Note that eigen.py now imports numpy.

**Comment by drvinceknight** [comment]
Good point, I'll add it to the requirements.txt

**Comment by drvinceknight** [comment]
Actually, without it being in the requirements.txt how did tests run on travis? Or do we not have tests for it?

**Comment by drvinceknight** [comment]
> Actually, without it being in the requirements.txt how did tests run on travis? Or do we not have tests for it?

Ah because numpy is a dependancy of matplotlib... Cool... Still adding it to the requirements.txt, but putting it in a different order.
