### ISSUE TITLE
Bug in tournament.py

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/Axelrod#179]
Line 39 Re-introduced by PR #178

**Comment by meatballs** [comment]
and line 41

**Comment by marcharper** [comment]
My bad, looks like commit 85f0b04c0e2eed6 is the culprit.

**Comment by meatballs** [comment]
I bow to the wisdom of Mr Einstein in these circumstances:

> Anyone who has never made a mistake has never tried anything new.
