### ISSUE TITLE
Rework run_axelrod

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/Axelrod#186]
Rework run_axelrod so that run_tournaments can be imported and used in other scripts without needing to construct argparse Namespace objects for the arguments.

Rename run_axelrod to run_axelrod.py (otherwise python won't import it).

Add some long versions of argparse parameters (mainly for readability and the above remark).

Move logging outside of run_tournaments since otherwise the handlers accumulate.

originally submitted in PR #185

**Comment by meatballs** [comment]
Commits from the work @marcharper did on PR #185 are now available against this issue on branch #186

**Comment by marcharper** [comment]
What help do you need for this? I've been using it for the past two days without issue, but of course I have not tried all combinations of parameters.

**Comment by meatballs** [comment]
It was really just to prompt the discussion on whether anything further is needed.

**Comment by marcharper** [comment]
We could add back run_axelrod and sym-link it to run_axelrod.py but there has to a .py to be able to import run_tournaments into other files (e.g. to systematically run many tournaments from within python rather than from a shell script). Otherwise I'll make a PR for this branch.

**Comment by langner** [comment]
Putting `run_tournaments()` in another file would resolve this. If `run_axelrod` is meant to be a script, it should need to be imported anywhere.

**Comment by marcharper** [comment]
Sure, that's fine. The same probably applies to the function `setup_logging` as well.

**Comment by meatballs** [comment]
I think I prefer the sound of this. run_axelrod is really just a calling program into the library. If we're having to import it into other scripts, it tends to suggest we're missing something from the library itself.

**Comment by drvinceknight** [comment]
Yeah I think we should move `run_tournaments` to the library itself and leave `run_axelrod` named as it is but calling it. This also would address #27 as it'll make `run_tournaments` easier to unit test.

**Comment by meatballs** [comment]
I'm happy to pick this one up from here if everyone's ok with that.

**Comment by drvinceknight** [comment]
Very much so, I'd like to take a look at the PR when it's done :)
