### ISSUE TITLE
Adding integration tests

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#191]
A conversation on #190 surrounded the fact that `utils.py` (introduced by #190) was not tested per say (all used methods were tested in other unit tests). We should test `utils.py` as well as test/enhance tests for other components that bring things together such as `test_full_tournament.py`.

**Comment by meatballs** [comment]
I think we need to make a clear distinction between unit tests and integration tests - possibly by creating folders for each under the tests folder - and then sorting our existing suite into the two categories. (i.e. some of what we have already are unit tests, some are integration).

**Comment by drvinceknight** [comment]
Sounds like a great idea.

I'd be keen to work on this (to learn) but I think I'd need help (I have been happily using the words 'integration tests' since yesterday pretending that I've known what it means for years...). So all guidance/suggestions are very much welcome :)

I could have a go and then if you're happy to review via PR (or whatever works for you really).

As you said on #186, I don't think this is too high priority, so I won't be able to work on it properly till approx 200 scripts time but I'll trudge along with it :) (I'll push to a branch on here regularly)

What do you think?

**Comment by meatballs** [comment]
Let's create a branch 191 for this and both work on it. We can still use the PR mechanism for contributing to that branch so that we don't trip each other up.

**Comment by drvinceknight** [comment]
Sounds good, just be aware that I won't be able to contribute high volume
for a while :)

**Comment by meatballs** [comment]
http://googletesting.blogspot.co.uk/2015/04/just-say-no-to-more-end-to-end-tests.html

**Comment by meatballs** [comment]
Once #192 is in, I'll create the basics for this and push it to a new branch 191. From then on, I won't push directly to the that branch, I'll only ever create PRs.

**Comment by drvinceknight** [comment]
Ok, your nudge worked :+1: 

This is all looking really cool. What's the deal with `MagicMock`, is the idea of that to make _true_ unit tests? I don't quite follow what the following is doing in c82b02eded12fa0d2709c64b157320ae02312e97:

```
+        tournament._run_serial_repetitions = MagicMock(
+            name='_run_serial_repetitions')
+        tournament._run_parallel_repetitions = MagicMock(
+            name='_run_parallel_repetitions')
```

Otherwise I follow what is happening so what's the next step? I guess putting in these `Mocks` everywhere?

**Comment by meatballs** [comment]
magic mock creates mock objects and then monitors what gets called in those objects.

That allows us to assert that a method under test successfully calls another method

**Comment by drvinceknight** [comment]
Do we somehow have to specify how we expect a mock object to behave?

**Comment by meatballs** [comment]
In the interests of continuous delivery, how about I create a PR for the work done so far but leave this issue open for the work on the remaining classes?

**Comment by drvinceknight** [comment]
Yeah that sounds good to me.

**Comment by drvinceknight** [comment]
Can we rename this to "further integration tests"?

**Comment by drvinceknight** [comment]
I'm going to close this. If there are more integration tests that are needed we can add specific issues (or reopen this).
