### ISSUE TITLE
Should/could we be using Hypothesis? 

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#198]
After the talk by Rae Knowles at Djangocon... https://hypothesis.readthedocs.org/en/latest/

**Comment by DRMacIver** [comment]
Naturally *I* think you should. ;-)

If you need help figuring out how to, feel free to drop by the IRC channel or mailing list. I also did a talk recently discussing how to migrate existing "normal" style tests to Hypothesis: http://www.drmaciver.com/2015/06/hypothesis-for-django/ (still Django, but the approach is mostly not Django specific).

**Comment by drvinceknight** [comment]
That's super nice of you @DRMacIver :+1: When we get there we'll probably be in touch.

On another note, my day job involves stochastic research (Markov models etc...) in which testing usually involves settings seeds etc... Ever since reading about hypothesis (and seeing Rae's talk) I've been wondering if hypothesis would be a better way...

**Comment by DRMacIver** [comment]
It could be. One of the features of Hypothesis is you can us it to ask you to give you Random instances if you want to try something with a wide variety of seeds. Would that help you?

**Comment by drvinceknight** [comment]
Reopening as hoping to give this a proper go now.

**Comment by drvinceknight** [comment]
Closing this as it's addressed by #454 (discussion can happen there).
