### ISSUE TITLE
Enhance documentation of strategies

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#199]
A clear description of the strategies would help contributions.

This could include:

- a list of the 14 original strategies in Axelrod's first tournament
- a list of the 62 strategies in Axelrod's second tournament
- an indication as to whether or not they are in the library
- a list of further strategies

We have attempted to automate this but I feel that this should now be curated with nice descriptions and code illustrations.

Let me know what people think and I'm happy to work on this.

**Comment by drvinceknight** [comment]
Some things:

- [A pdf that briefly describes the tournaments](http://www2.econ.iastate.edu/classes/econ308/tesfatsion/axeltmts.pdf)
- [The wiki page](http://en.wikipedia.org/wiki/The_Evolution_of_Cooperation)
- [Axelrod's original paper](http://www.jstor.org/stable/173932) (this might be behind a paywall)
- [Axelrod's second paper](http://jcr.sagepub.com/content/24/3/379) (behind a paywall)

**Comment by marcharper** [comment]
You might also consider Stewart and Plotkin's [recent tournament](http://www.nr.com/whp/StewartPlotkinExtortion2012.pdf).

Scripts to rerun the tournaments would also be a neat (and probably easy) addition.

I'm happy to help but sadly behind paywalls these days.

**Comment by drvinceknight** [comment]
Great suggestion @marchaper. I'm working on this, I expect it'll take me a little while but I'll update this issue as I go along :)

**Comment by drvinceknight** [comment]
(By the way, I'm working on the `199` branch which is up.)

**Comment by drvinceknight** [comment]
#207 gets the first set of strategies from Axelrod's initial tournament. Once that's in and we're happy with the format etc I will get started on the second tournament.

**Comment by marcharper** [comment]
Some of the not-implemented strategies are simple cases of memory one strategies. I'm going to add those into the repository before I get started on the S&P tournament.

**Comment by drvinceknight** [comment]
Sounds good, you could also just add them to the documentation and mark
them as not implemented yet? (Like I've done with Axelrod's original one -
really I suppose that just depends on what you feel would take less
time...).

When you say 'get started on the S&P' tournament I guess you mean the
documentation for it right?

**Comment by drvinceknight** [comment]
Ignore my second question: it's stupid :)

**Comment by marcharper** [comment]
Yes I'm updating the docs and adding new tests for the new strategies as I go. Should have something up soon.

**Comment by marcharper** [comment]
So apparently there was some additional tournaments in 2004 and 2005, see [this writeup](  https://bib.irb.hr/datoteka/583494.1818-A-Review-of-Iterated-Prisoner-s-Dilemma-Strategies-v1_2.pdf). Some of these tournaments introduced noise.

I've been writing up some of the strategies (will submit a PR soon). Apparently the strategy I named FoolMeOnce was known as GRIM.

**Comment by marcharper** [comment]
Also if you all haven't seen [this writeup](http://www.scottaaronson.com/morality.pdf), it's very interesting!

**Comment by meatballs** [comment]
At last!! I now know what P, R, S & T actually mean!
