### ISSUE TITLE
How to reference this library in papers

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#215]
I'm currently writing a short paper for a small pedagogic journal and need to reference the library. The library does not play a huge part (I have a throw away sentence: 'This activity can be enhanced by showing students the output of a computer simulation...blablabla \cite{axelrod}')... You can see the current form of the paper [here](https://github.com/drvinceknight/Playing-games-a-case-study-in-active-learning/blob/master/paper/paper.pdf) (work in progress - need to submit by tonight).

As you can see there I've attributed the work to me as the sole author. **This is the worst solution to my question**. One option would be to reference all contributors, this is not technically impossible but I think would perhaps be a bit overkill. Another option would be to reference @meatballs and @langner as authors but that would ignore people like @marcharper (and others!) who have contributed hugely to this.

Does anyone have any suggestions? I know that [the sagemath citing guide](http://wiki.sagemath.org/Publications_using_SAGE) indicates `William Stein and others`. So one option would be to go for `Vince Knight and others` although even that is not really perfect...

Anyway, if anyone has any thoughts, it would be great to discuss (and eventually perhaps include guidance in the docs and the readme).

**Comment by drvinceknight** [comment]
@meatballs in the [gitter room](https://gitter.im/Axelrod-Python/Axelrod) suggested:

> We could create an ‘authors’ page either on gh or readthedocs and point your url at that
and then citation could simply say ‘the Axelrod-Python project team'

I think that's a pretty good idea :+1: 

We just need to clean up/setup a nice sub page on the docs listed everyone (possibly including contributors to Djaxelrod as well?).

I'd be happy to take that on if we thinks it's a good idea.

**Comment by meatballs** [comment]
We create a github.io page or two for the Axelrod-Python organisation which would then cover both projects

**Comment by drvinceknight** [comment]
That's not a bad idea (and certainly worth doing anyway - although it might need some thought as to make sure we don't have multiple things doing the same thing - could that page just be the Djaxelrod page once it goes live?) although I suppose that in the sense that I'm referencing the particular software package, I think it makes sense to point at the rtd page for the axelrod library...

**Comment by drvinceknight** [comment]
I suppose just pointing at https://github.com/Axelrod-Python/ could be worth thinking about... Just thinking about fragmentation...

**Comment by marcharper** [comment]
My contributions, which I view to be relatively minor, are strictly pro bono and will continue to be so. If it suits your purposes and preferences (or the project's goals) to include or not include me in the citation or on an author page, you have my permission to do either.

**Comment by langner** [comment]
You could also reference a DOI through Figshare or Zenodo. Even if you don't use it, that's something you can mint automatically with each release.

**Comment by drvinceknight** [comment]
On 2 Jul 2015 2:51 am, "Karol M. Langner" <notifications@github.com> wrote:
>
> You could also reference a DOI through Figshare or Zenodo. Even if you
don't use it, that's something you can mint automatically with each release.
>

True, this would also work, I can't say that I think it adds much though
(but I might just not appreciate something about DOIs). I really like the
idea of putting of a project page. I'm thinking that this would end up
being very similar to sagemath: has a project page, has documentation and
has an excellent web interface...

**Comment by meatballs** [comment]
Can we close this one now?

**Comment by drvinceknight** [comment]
Yup, I'd like to take on the github pages site repo when I get a chance...

**Comment by meatballs** [comment]
OK. I'll close this and create an empty github.io repo for the organisation.

> Yup, I'd like to take on the github pages site repo when I get a chance...

Given that we are Axelrod-Python rather than Axelrod-Ruby, I take it that would have to be a Pelican site?!!
