### ISSUE TITLE
Backstabber Strategy

### ISSUE THREAD

**Issue by uglyfruitcake** [Axelrod-Python/Axelrod#221]
New world-beating strategy.
Work visible on my fork at https://github.com/uglyfruitcake/Axelrod/tree/221

**Comment by meatballs** [comment]
Can you edit docs/overview_of_strategies.rst as part of this ticket, please?

Rename the section called 'Strategies implemented in the module' to 'Original Strategies'

Add some text to that section to describe it. I suggest:

>
There are several original strategies which have been created as part of this project and have never appeared in previous tournaments.


And then add a section to describe BackStabber.

**Comment by drvinceknight** [comment]
I would just suggest:

> There are several original strategies which have been created as part of this project and have never appeared in previous tournaments.

to be:

> There are several original strategies which have been created as part of this project and have never (to our knowledge) appeared in previous tournaments.
