### ISSUE TITLE
Tweaks to documentation for Stewart and Plotkin tournament

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#222]
Just reading through (awesome work @marcharper). I have some suggestions for tweaks (I'm happy to pick them up):

1. Should we order the S&P tournament above the 'implemented in this module' section (although that is about to be renamed: #221)?
2. Some of the mathjax could use a space between the pipe and the conditional.
3. The implementation section for the strategies of the original Axelrod tournament had the `print p1.history` part with the output shown (and sometimes a discussion about it). At the moment the `print p1.history` is just left with nothing else.
4. I really like the table at the beginning of the section, should we include one like that in the original tournament section?
5. I would suggest that for consistency, the 'Remaining Strategies' section is actually spaced out with 'not implemented' on each section (as for the original Axelrod tournament strategies). This allows them to appear directly on the left menu.

I'm happy to pick all of these up, just let me know your thoughts.

**Comment by marcharper** [comment]
Sure that's all fine with me. I have some additional suggestions:

* For each strategy we need to list a source, since some of these are hard to track down and the names are sometimes ambiguous. I started to do this but then I though either another file or some kind of index along with the strategy definition could be better. Thoughts? This would apply to every strategy in the library.
* Similarly, a way to specify multiple names for a strategy somewhere (e.g. WSLS and Pavlov) other than the doc string for the class, since I don't expect most people to dig that deep.
* HARD_JOSS could actually be made into a named class. I just used the memoryone class to instantiate it, but some other similar strategies have their own classes (e.g. ZDGTFT2). I think we probably want to be consistent.
* Finally, we may want to update the docs on contributing to indicate that for a new strategy, we need (1) the strategy, (2) the literature source, (3) unit tests, and (4) to update the docs

**Comment by drvinceknight** [comment]
> Sure that's all fine with me. I have some additional suggestions:
> 
> For each strategy we need to list a source, since some of these are hard to track down and the names are sometimes ambiguous. I started to do this but then I though either another file or some kind of index along with the strategy definition could be better. Thoughts? This would apply to every strategy in the library.

I'm not too sure I understand the suggestion. Certainly understand the problem. Finding sources for all the strategies (this will not be possible for some of the original ones...) will be tricky... What do you mean by 'another file'? 

> Similarly, a way to specify multiple names for a strategy somewhere (e.g. WSLS and Pavlov) other than the doc string for the class, since I don't expect most people to dig that deep.

Agree... I'm not sure I see how we can do anything different than simply specifying in the documentation ('also know as...') 

> HARD_JOSS could actually be made into a named class. I just used the memoryone class to instantiate it, but some other similar strategies have their own classes (e.g. ZDGTFT2). I think we probably want to be consistent.

Yup that would be cool.

> Finally, we may want to update the docs on contributing to indicate that for a new strategy, we need (1) the strategy, (2) the literature source, (3) unit tests, and (4) to update the docs

Yup. I think your first 3 points are probably separate issues/PRs as they're potentially quite tricky. What do you reckon? I can easily take care of the minor tweaks I mentioned and throw in the 4th bullet point from this comment in a single PR for this issue.

**Comment by marcharper** [comment]
I'll start another issue for sourcing, and I'll submit a PR for HARD_JOSS.

-- Marc

**Comment by marcharper** [comment]
So actually HARD_JOSS is the same as the Joss strategy that is already in the library. Apparently there is also a SOFT_JOSS that uses a four-vector (1., 0, 0.9, 0) instead of (0.9, 0, 1., 0).

**Comment by drvinceknight** [comment]
ALLD is also just Defector. I'll tweak these as I go through. Going through it slowly I'm probably going to add a bit more to the implementation for each strategy as well (GTFT's implementation section for example does not really illustrate what is happening). I'm working my way through though :) :+1:

**Comment by drvinceknight** [comment]
Sorry, now that I'm going through it all carefully ignore my comment. A PR is on it's way (taking me a little while).

**Comment by drvinceknight** [comment]
Have merged #226.

**Comment by drvinceknight** [comment]
Am I right that `GoByMajority` is in fact `HARDMAJO` (http://axelrod.readthedocs.org/en/latest/overview_of_strategies.html#not-implemented-hard-majo)? http://axelrod.readthedocs.org/en/latest/index_of_strategies.html#axelrod.strategies.GoByMajority

**Comment by marcharper** [comment]
Looks like they are the same.

**Comment by drvinceknight** [comment]
@marcharper I've just opened #229 - would be great if you could look through to make sure I got things right :) (No big rush).

**Comment by drvinceknight** [comment]
I see that @meatballs has merged in, would be good if you could look through anyway (just to make sure I haven't missed anything) @marcharper :)

**Comment by marcharper** [comment]
Looks good, I'm not sure I'd say that Extort-2 and ZDGTFT-2 are classical yet, but things move quickly I suppose :)

The only suggestion I have is "Hard joss --> Hard Joss" (Joss is someone's name I think)

**Comment by drvinceknight** [comment]
> Looks good, I'm not sure I'd say that Extort-2 and ZDGTFT-2 are classical yet, but things move quickly I suppose :)

Yeah I wasn't sure about that myself.

> 
> The only suggestion I have is "Hard joss --> Hard Joss" (Joss is someone's name I think)

It is indeed! I'll fix that. Does anyone mind if I push directly to master for that?

**Comment by marcharper** [comment]
It's fine with me.

**Comment by drvinceknight** [comment]
Cool: 0eb9c2
