### ISSUE TITLE
Memoryone tournament

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#238]
It would just be nice to see how our results compare to other recent results and tournaments, and how the ZD strategies fare when memory is not allowed (or is limited). Right now the "best" strategies in the library have long or infinite memories, and that is somewhat at odds with some of the existing literature.

So: Add a tournament for just the strategies with memory_depth in [0,1] (i.e. just memoryone strategies), and another for 0 <= memory_depth < float('inf') (finite memory).

I think I could figure it out, but I suspect it would be much easier for @meatballs since I haven't worked with that part of the library much.

**Comment by meatballs** [comment]
OK. I'll pick this up once #220 is done

**Comment by drvinceknight** [comment]
Sorry for being the voice of negativity again. Not against this per say but is it indeed worth doing all these tournaments within the library itself? I always sort of imagined the library being used to answer interesting questions so that people could import and build scripts for their tournament (this would indeed be a very simple list comprehension to pull them out right?).

At the moment the three tournaments we have are pretty logical (a simple quick demo one and basically two others that keep track of everything). Again, not at all against this particular one but things could start getting bloated if we start including a bunch of particular tournaments (of which there are a huge number of potentially interesting ones)? 

For example this tournament could be a nice one to include in documentation (or indeed a blog post or something) perhaps as an example of creating one?

Of the top of my head the call to create this would be:

```
import axelrod
strategies = [s() for s in axelrod.ordinary_strategies if s().memory_depth in [0, 1]]
tournament = axelrod.Tournament(strategies)
results = tournament.play() ...
```

Ultimately I would rather we had many people using the library to build interesting tournaments then a large complicated library with multiple tournaments built in (*nix philo of doing 1 thing well so to speak). I'm not saying that these two extra tournaments would immediately bloat things but just a bit weary.

**Comment by marcharper** [comment]
I don't disagree but can we get these two in before we halt the proliferation of new tournaments? :)

Alternatively we could have another file of "interesting example tournaments" in addition to run_axelrod. I'm not sure where the boundary of "in the library" is -- most libraries don't "run" anything by default, the just provide functionality, and so run_axelrod seems already a bit "out of the library" to me.

The creation of plots, while clearly useful and interesting, is also outside of the scope of running the tournaments themselves, but appears to be "in library". So maybe it would help to define what is or is not expected to be part of the library.

**Comment by drvinceknight** [comment]
> I don't disagree but can we get these two in before we halt the proliferation of new tournaments? :)

I'd be just fine with that :)

> 
> Alternatively we could have another file of "interesting example tournaments" in addition to run_axelrod. I'm not sure where the boundary of "in the library" is -- most libraries don't "run" anything by default, the just provide functionality, and so run_axelrod seems already a bit "out of the library" to me.

That's a very good point.

> 
> The creation of plots, while clearly useful and interesting, is also outside of the scope of running the tournaments themselves, but appears to be "in library". So maybe it would help to define what is or is not expected to be part of the library.

Yup, you're making very good points here. `run_axelrod` is kind of out of the library isn't it...

Perhaps my concerns are misplaced...

**Comment by marcharper** [comment]
FYI I have a python file of example tournaments. If there is interest I can add it to the repository somewhere.


import os

import axelrod


def ensure_directory(directory):
    if not os.path.isdir(directory):
        os.mkdir(directory)

def axelrod_strategies():
    s = []
    s.extend(axelrod.basic_strategies)
    s.extend(axelrod.ordinary_strategies)
    return [t() for t in s]

def finite_memory_strategies(lower=0, upper=float('inf')):
    strategies = []
    for s in axelrod_strategies():
        if s.memory_depth >= lower and s.memory_depth < upper:
            strategies.append(s)
    return strategies

def memoryone_strategies():
    return finite_memory_strategies(lower=0, upper=2)

def tscizzle_strategies():
    strategies = [
        axelrod.Cooperator(),
        axelrod.Defector(),
        axelrod.Eatherley(),
        axelrod.Champion(),
        axelrod.GTFT(p=0.1),
        axelrod.GTFT(p=0.3),
        axelrod.GoByMajority(soft=True),
        axelrod.GoByMajority(soft=False),
        axelrod.TitFor2Tats(),
        axelrod.Random(0.8),
        axelrod.Random(0.2),
        axelrod.WinStayLoseShift(), # Pavlov
        axelrod.TitForTat(),
        axelrod.TwoTitsForTat(),
        axelrod.Grudger(), # Friedman
        axelrod.Tester(),
        axelrod.SuspiciousTitForTat(),
        axelrod.Joss(0.1),
        axelrod.Joss(0.3),
    ]
    return strategies

def sp_strategies():
    strategies = [
        axelrod.Cooperator(), # ALLC
        axelrod.Defector(), # ALLD
        axelrod.GTFT(),
        axelrod.GoByMajority(soft=False), # HARD_MAJO
        #axelrod.GoByMajority(soft=True), # SOFT_MAJO
        axelrod.TitFor2Tats(), # TFT2
        axelrod.HardTitFor2Tats(), # HARD_TFT2
        axelrod.Random(), # RANDOM
        axelrod.WinStayLoseShift(), # WSLS
        axelrod.TitForTat(),
        axelrod.HardTitForTat(), # HARD_TFT
        axelrod.Grudger(), # GRIM
        axelrod.Joss(), # HARD_JOSS
        axelrod.ZDGTFT2(),
        axelrod.ZDExtort2(),
        axelrod.Prober(),
        axelrod.Prober2(),
        axelrod.Prober3(),
        axelrod.HardProber(),
        axelrod.Calculator(),
    ]
    return strategies

def tournament(name, strategies, repetitions=1000, with_ecological=False):
    ensure_directory(name)
    tm = axelrod.TournamentManager(output_directory=name,
                                   with_ecological=with_ecological)
    tm.add_tournament(name, strategies, repetitions=repetitions)
    tm.run_tournaments()

if __name__ == "__main__":
    strategies = memoryone_strategies()
    tournament("Memoryone", strategies)
    strategies = finite_memory_strategies()
    tournament("FiniteMemory", strategies)
    strategies = tscizzle_strategies()
    tournament("tscizzle", strategies)
    strategies = sp_strategies()
    tournament("sp", strategies)
    strategies = axelrod_strategies()
    tournament("all_strategies", strategies)

**Comment by marcharper** [comment]
Re: #251 251 I vote we close without fixing. I'll start a new personal repository with the tournament generating code.

**Comment by meatballs** [comment]
Agreed.

**Comment by drvinceknight** [comment]
:+1:
