### ISSUE TITLE
History mismatch in new strategy

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#239]
I have been trying to write a [strategy](https://github.com/marcharper/Axelrod/blob/6b9aa9b26a45bfcf9364036a609b350871ab17e2/axelrod/strategies/detector.py) that detects if its history, its strategy method, or the opponent's history is being manipulated. It records its own plays in a second history and then checks it against its internal history each round (and something similar for the opponent). The strategy is not stochastic in any way (yet).

I'm getting strange output when I invoke run_axelrod. The first strategy that ShenanigansDetector encounters is Alternator (which is also deterministic), but I sometimes get two different outputs:

user@tower:~/repos/Axelrod$ ./run_axelrod -p 1
Starting strategies tournament with 10 round robins of 200 turns per pair.
Alternator False
History mismatch
Alternator
['C', 'C', 'D']
['C', 'C', 'C']
['C', 'D', 'C']
['C', 'D', 'C']
user@tower:~/repos/Axelrod$ ./run_axelrod -p 1
Starting strategies tournament with 10 round robins of 200 turns per pair.
Alternator False
History mismatch
Alternator
['C', 'C', 'C', 'C', 'D']
['C', 'C', 'C', 'C', 'C']
['C', 'D', 'C', 'D', 'C']
['C', 'D', 'C', 'D', 'C']

For some reason ShenanigansDetector's own history is not matching its second copy (but the opponent's is ok). If I remove Alternator then Cooperator is the first opponent, and it always fails on the first play against the second opponent:

user@tower:~/repos/Axelrod$ ./run_axelrod -p 1
Starting strategies tournament with 10 round robins of 200 turns per pair.
Cooperator False
Cooperator False
History mismatch
Cooperator
['D']
['C']
['C']
['C']

I can't seem to track down where the bug is :( Any help is appreciated!

**Comment by drvinceknight** [comment]
Commenting to listen in and potentially get to it already... I know that `Mind Bender` did something to stop people messing with it, perhaps taking a glance at that might offer insight...
