### ISSUE TITLE
`update_results.sh` leaves files in the home directory.

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#241]
Easy fix, just testing that I've got the right stuff working.

**Comment by marcharper** [comment]
For some reason strategies_payoff.png and strategies_boxplot.png are not longer in the assets directory (and now missing from the docs). I think this might be related to the update_script change (git doesn't like it when you delete a file without using "git rm ..." or "git mv ...".

**Comment by marcharper** [comment]
The changes to the update_results.sh script do not seem to be the cause; something I did along the way seems to have deleted the two images. PR #247  adds them back in.
