### ISSUE TITLE
Plot for number of wins / distribution of wins

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#248]
In S&P's tournament they give results on how many wins each strategy gets in the tournament (in addition to the average score). It would be nice if the library also generated a plot for the number of wins in addition to the boxplots for mean scores.

**Comment by drvinceknight** [comment]
:+1: Yeah this is worthwhile.

**Comment by meatballs** [comment]
Definitely worth having - but I'd like to pick this up after #220. The changes I'm having to make for that ticket are large and, if we try to do this at the same time, we'll have merge conflicts all over the place all the time.

**Comment by meatballs** [comment]
Just to be clear - Is a win:

1. a single instance of a turn where the player scores higher than its opponent, or,
2. a round of (say 200) turns where the players scores a higher total than its opponent

**Comment by drvinceknight** [comment]
I think it's the second but am completely indifferent. Whatever @marcharper
prefers as far as I'm concerned.

**Comment by marcharper** [comment]
The second.

**Comment by meatballs** [comment]
Thank you! Didn't want to assume!
