### ISSUE TITLE
Project Objectives

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/Axelrod#251]
I think it might be helpful for us to define the aims and objectives of this project and to have those recorded. Here's my shot at what I think those should be:

1. To enable the reproduction of previous IPD research as easily as possible.
1. To produce the de-facto tool for any future IPD research.
1. To provide as simple a means as possible for anyone to define and contribute new and original IPD strategies.

I also think we have a further objective, currently implemented within the library itself, but which ought to be moved to a separate repository:

* To regularly run a small number of interesting tournaments and to publish their results online.

**Comment by meatballs** [comment]
I also think that, whilst we would encourage interesting work and analysis of tournaments which use our library, that analysis should not form part of the library itself. The library should produce the information which the research requires, but the analysis should be done separately by the individual researcher. We should, perhaps, consider listing work which has used the library as part of the github.io pages.

**Comment by drvinceknight** [comment]
I agree with all of these and think it's important to have them written down as it helps to guide some of the discussion on previous/ongoing PRs/issues.

I particularly like '2.' being written clearly as it's something that I think can encourage the use of the library outside of the repository.

I also think having a 'front end' like repository where we keep track of interesting tournaments is a good thing to do. Basically we're talking about doing things in a very '*nix'y: this library does what this library does and does it well.

**Comment by drvinceknight** [comment]
Assuming everyone's ok and on board with this I think this should be a PR to have it written in the README and then arguably have `run_axelrod` lightened...

**Comment by drvinceknight** [comment]
> I also think that, whilst we would encourage interesting work and analysis of tournaments which use our library, that analysis should not form part of the library itself. The library should produce the information which the research requires, but the analysis should be done separately by the individual researcher. We should, perhaps, consider listing work which has used the library as part of the github.io pages.

:+1: YES

I need to work on the github.io pages some more... Looks like I will setup a jekyll site if that's not too painful re python/ruby?

**Comment by marcharper** [comment]
:+1: 

What do you think about having a separate (optional) repository for analysis that people can contribute to? There is value to having things centralized, and blog posts can disappear without records. This makes it easier to combine and build upon other's analyses.

**Comment by meatballs** [comment]
> What do you think about having a separate (optional) repository for analysis that people can contribute to?

Yes, I think we should have our own repo(s) for analysis work. The current tournaments which we run from run_axelrod are a good example, but I'm sure there will be others.

**Comment by drvinceknight** [comment]
> but I'm sure there will be others.

Will these others necessarily be part of the Axelrod-Project organisation? In a way I would love to encourage people that are not us to use the library outside and perhaps in the readme somewhere we keep track of these (asking people to add their name/project kind of thing...).

**Comment by meatballs** [comment]
> Will these others necessarily be part of the Axelrod-Project organisation?

the way I see it, by definition, we'll only be including anything that we want as part of the organisation!

e.g I can imagine a couple of additional tournaments that we might include once we are able:

* Axelrod's original tournament
* Axelrod's second tournament

But I can also imagine somebody wanting to create a tournament of various machine learning strategies against one another (as part of some research on machine learning). That, I think, would be an example of something that should be done independently but that we might quote and link to.

**Comment by drvinceknight** [comment]
:+1: Yup, I like that.

**Comment by marcharper** [comment]
So do we want to close #238? I've already got an external solution.

**Comment by meatballs** [comment]
Hadn't thought of that, but yes, that would seem to fit with some independent research that belongs in your own repo and we should quote it and link to it here.

**Comment by drvinceknight** [comment]
Can someone put together a PR with some information about where to link
etc? Perhaps in the overall README? (Another option being the github.io
page...).

**Comment by drvinceknight** [comment]
Actually I'm putting something together now :)

**Comment by drvinceknight** [comment]
#252

**Comment by drvinceknight** [comment]
Can we close this issue?

**Comment by marcharper** [comment]
:thumbsup:
