### ISSUE TITLE
Changing the default heatmap colormaps?

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#258]
The colormap for the heatmap is using the default `jet` colormap which [is apparently the devil](https://www.youtube.com/watch?v=xAoljeRJ3lU).

I suggest putting together a couple of other maps and throwing them on this issue for us to explore?

**Comment by marcharper** [comment]
I believe matplotlib is [officially](https://github.com/scikit-image/scikit-image/pull/1599) switching to [viridis](http://bids.github.io/colormap/).

**Comment by drvinceknight** [comment]
That looks super nice! Doesn't seem to be an option in the current version?

```
ValueError: Colormap viridis is not recognized. Possible values are: Spectral, summer, coolwarm, Wistia_r, pink_r, Set1, Set2, Set3, brg_r, Dark2, prism, PuOr_r, afmhot_r, terrain_r, PuBuGn_r, RdPu, gist_ncar_r, gist_yarg_r, Dark2_r, YlGnBu, RdYlBu, hot_r, gist_rainbow_r, gist_stern, PuBu_r, cool_r, cool, gray, copper_r, Greens_r, GnBu, gist_ncar, spring_r, gist_rainbow, gist_heat_r, Wistia, OrRd_r, CMRmap, bone, gist_stern_r, RdYlGn, Pastel2_r, spring, terrain, YlOrRd_r, Set2_r, winter_r, PuBu, RdGy_r, spectral, rainbow, flag_r, jet_r, RdPu_r, gist_yarg, BuGn, Paired_r, hsv_r, bwr, cubehelix, Greens, PRGn, gist_heat, spectral_r, Paired, hsv, Oranges_r, prism_r, Pastel2, Pastel1_r, Pastel1, gray_r, jet, Spectral_r, gnuplot2_r, gist_earth, YlGnBu_r, copper, gist_earth_r, Set3_r, OrRd, gnuplot_r, ocean_r, brg, gnuplot2, PuRd_r, bone_r, BuPu, Oranges, RdYlGn_r, PiYG, CMRmap_r, YlGn, binary_r, gist_gray_r, Accent, BuPu_r, gist_gray, flag, bwr_r, RdBu_r, BrBG, Reds, Set1_r, summer_r, GnBu_r, BrBG_r, Reds_r, RdGy, PuRd, Accent_r, Blues, autumn_r, autumn, cubehelix_r, nipy_spectral_r, ocean, PRGn_r, Greys_r, pink, binary, winter, gnuplot, RdYlBu_r, hot, YlOrBr, coolwarm_r, rainbow_r, Purples_r, PiYG_r, YlGn_r, Blues_r, YlOrBr_r, seismic, Purples, seismic_r, RdBu, Greys, BuGn_r, YlOrRd, PuOr, PuBuGn, nipy_spectral, afmhot
```

I'm looking through http://matplotlib.org/users/colormaps.html

I'll throw in to comments below some of the ones I've done so far (mainly choosing from the sequential list).

**Comment by drvinceknight** [comment]
# Blues

![basic_strategies_payoff-blues](https://cloud.githubusercontent.com/assets/2131546/9117755/324a5786-3c64-11e5-9a7e-5bffdbb2efd7.png)

**Comment by drvinceknight** [comment]
# BuPu

![basic_strategies_payoff-bupu](https://cloud.githubusercontent.com/assets/2131546/9117759/3b738742-3c64-11e5-9680-cc08334b29eb.png)

**Comment by drvinceknight** [comment]
# GnBu

![basic_strategies_payoff-gnbu](https://cloud.githubusercontent.com/assets/2131546/9117767/450d6dcc-3c64-11e5-991b-2e1cb3e74260.png)

**Comment by drvinceknight** [comment]
# PuBuGn

![basic_strategies_payoff-pubugn](https://cloud.githubusercontent.com/assets/2131546/9117778/4f27aa20-3c64-11e5-9631-eb598cbd4d8a.png)

**Comment by drvinceknight** [comment]
# PuRd

![basic_strategies_payoff-purd](https://cloud.githubusercontent.com/assets/2131546/9117785/5ae66ed2-3c64-11e5-8b6b-3fed11bb1623.png)

**Comment by drvinceknight** [comment]
# YlBuGn

![basic_strategies_payoff-ylbugn](https://cloud.githubusercontent.com/assets/2131546/9117793/65d7beae-3c64-11e5-9e80-30f24843dc04.png)

**Comment by drvinceknight** [comment]
# summer

![basic_strategies_payoff-summer](https://cloud.githubusercontent.com/assets/2131546/9117874/d2d6ae02-3c64-11e5-84ca-bfb0396d5bf2.png)

**Comment by drvinceknight** [comment]
# cool

![basic_strategies_payoff-cool](https://cloud.githubusercontent.com/assets/2131546/9117878/da090d96-3c64-11e5-903c-13c8c3b6573d.png)

**Comment by drvinceknight** [comment]
# spring

![basic_strategies_payoff-spring](https://cloud.githubusercontent.com/assets/2131546/9117891/fb46a1b2-3c64-11e5-8d28-63888efb20fd.png)

**Comment by drvinceknight** [comment]
# winter

![basic_strategies_payoff-winter](https://cloud.githubusercontent.com/assets/2131546/9117910/12cb245c-3c65-11e5-97a7-64362f5934c1.png)

**Comment by drvinceknight** [comment]
I think that `YlBuGn` gets my vote...

**Comment by drvinceknight** [comment]
Edit: that should have been `YlGnBu` - have edited the corresponding image comment.

**Comment by drvinceknight** [comment]
Here are the full plots with `YlGnBu`:

Basic:

![basic_strategies_payoff](https://cloud.githubusercontent.com/assets/2131546/9118128/6971dbce-3c66-11e5-8e87-ebafb9c00539.png)

All:

![strategies_payoff](https://cloud.githubusercontent.com/assets/2131546/9118246/1ba58b88-3c67-11e5-9a04-09126f91ab69.png)

Cheating:

![cheating_strategies_payoff](https://cloud.githubusercontent.com/assets/2131546/9118132/6de99020-3c66-11e5-933e-26ca0a02d2c8.png)

Unless `viridis` is available and I'm just missing something I suggest we go with `YlGnBu` until the next release of matplotlib with that default...

Let me know if you'd like me to run anymore (it's just this modification of line 68 in `axelrod.plots`):

```
mat = ax.matshow(self._payoff_dataset, cmap='YlGnBu')
```

**Comment by marcharper** [comment]
I believe `viridis` comes in with matplotlib 2.0 (if I recall correctly from the video) in September. I think the only way to get these now is by adding additional dependencies.

I'm ok with `YlGnBu` but it's a little drab... however most of the default colormaps have something to be desired, so hopefully this will improve soon.
