### ISSUE TITLE
A progress bar?

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#259]
Not sure if something like this is worth throwing in: http://pythonhosted.org/progressbar2/?

**Comment by marcharper** [comment]
Could be useful. I think your idea of reducing the footprint of run_axelrod should be part of the consideration. Removing e.g. the Meta* strategies and other time intensive strats from the default tournament reduces the computation time substantially.

That's not to say I don't like those strategies, of course they are interesting. But the time for run_axelrod scales with the number of strategies (as does the time for the Meta strategies, so it's a double whammy). Thoughts?

**Comment by drvinceknight** [comment]
> Removing e.g. the Meta* strategies and other time intensive strats from the default tournament reduces the computation time substantially.

No the main purpose of `run_axelrod` should be to run all the strategies so I don't think that's a good option. Again, people can easily run smaller tournaments if they wanted to...

Perhaps a progress bar is not really necessary though... I don't know I'm undecided about that.

**Comment by marcharper** [comment]
Ok that's fine, I just noticed that some of the strategies take a lot more time than others, and of course the tournament itself scales as O(num_strategies^2), yes?

**Comment by drvinceknight** [comment]
Yeah that's indeed the complexity of the tournament. At the moment it's
still bearable I think, if it did get to the point where things got out of
hand in term of computational time then I'd suggest we revisit removing
some strategies.

As far as the progress bar is concerned, should we leave this issue open to
investigate it or just not bother? (It's not terribly important).

**Comment by marcharper** [comment]
Well it is taking about 15+ minutes to rebuild the assets now. We could also move the assets to their own branch and change where the docs point, which would also prevent merge conflicts when one PR goes in ahead of another. But we would have to remember to update the assets branch periodically.

**Comment by drvinceknight** [comment]
I wouldn't be surprised if we got to the point where it takes a couple of hours for the assets to re build. This could just be something that one of us does overnight every now and then (which it essentially already is - most submitted strategies have been done so without re running the results).

Well, actually I would be surprised because that would be a hell of a lot of strategies but I wouldn't have a problem with it. I think it gets messy if we're running some subset of the tournament and pick and choose.

I think it's not really a problem, my only suggestion with this issue was a progress bar to help give an indication of how long things where taking...

**Comment by marcharper** [comment]
Sure, and sorry to derail. I'll switch to gitter.

**Comment by langner** [comment]
I think there is also more we could do to optimize the inner loops.

**Comment by marcharper** [comment]
@langer We decided to move run_axelrod and the assets to their own repository (the tournament repository in Axelrod), so it's less of a concern now. I'll write scripts / use travis to automatically update the assets when new strategies / PR are merged (which I'm also doing for my examples repository).

Totally unrelated: take a look at the Calculator strategy which tries to detect cycles in opponent histories. It might make a nice addition to Meta Hunter.

**Comment by langner** [comment]
@marcharper I am @langner not langer :)

I just caught up on all the changes... seems OK. I'm not so interested in tuning the meta strategies anymore, since it's not really possible to detect the backstabbers which are currently on top. What we need is some way to outstmart those.

**Comment by drvinceknight** [comment]
I'm going to close this. Since the tournament split it doesn't make sense here...
