### ISSUE TITLE
Bug in eco plots?

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#261]
Working on what is a trivial change for #258 and re running the results I noticed that the eco plots were not working for me. See #260.

I've run this on `master` as well as my `258` branch and have the same outcome:

![basic_strategies_reproduce](https://cloud.githubusercontent.com/assets/2131546/9149924/bac1b7e8-3db9-11e5-85d5-e14ec1a5a9c5.png)

I have tried this on two machines and with matplotlib installed in a virtualenv directly from `requirements.txt`. Can anyone else reproduce this?

(Here's the command to quickly grab the basic plot:

```
./run_axelrod -c cache.txt -p 0 --xs --xc --xa
```

)

**Comment by marcharper** [comment]
The plot produced by that command (for this branch) looks fine on my machine

**Comment by marcharper** [comment]
Ok I was able to reproduce the bug (I had to reinstall Axelrod).

**Comment by drvinceknight** [comment]
#263 has not fixed the issue for me... I still get the following:

![basic_strategies_reproduce](https://cloud.githubusercontent.com/assets/2131546/9154380/462ee6e2-3e83-11e5-8dff-472f7ec989f9.png)

I had originally tried with something a bit like this but it did not make a difference to the heatplot itself. This is what confuses me, the heatplot is fine...

I am also getting this behaviour on `master` so I'm pretty sure the colormap does not have much to do with it.
 
- Can anyone reproduce this bug (see image below) on master?
- I am reverting #263 on my `258` branch, does that give the same for others?

I have run this on MacOSX as well as ubuntu 14.04. When you say @marcharper that you had to 'reinstall' Axelrod, what do you mean? Just a re-clone of the repo? I'll try that.

![basic_strategies_reproduce](https://cloud.githubusercontent.com/assets/2131546/9154385/bf050e20-3e83-11e5-99ac-6d40b5dc1714.png)

**Comment by drvinceknight** [comment]
A clean clone of Axelrod gives the same outcome (on `master`)...

```
>>> import matplotlib
>>> matplotlib.__version__
'1.4.2'
```

How very strange...

**Comment by marcharper** [comment]
```
user@tower:~/repos/Axelrod$ git checkout 258 # With my patch
Switched to branch '258'
Your branch is ahead of 'github-axelrod/258' by 1 commit.
  (use "git push" to publish your local commits)
user@tower:~/repos/Axelrod$ sudo paco -lD "python setup.py install"
[sudo] password for user: 
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
copying axelrod/plot.py -> build/lib.linux-x86_64-2.7/axelrod
running build_scripts
running install_lib
copying build/lib.linux-x86_64-2.7/axelrod/plot.py -> /usr/local/lib/python2.7/dist-packages/axelrod
byte-compiling /usr/local/lib/python2.7/dist-packages/axelrod/plot.py to plot.pyc
running install_scripts
changing mode of /usr/local/bin/run_axelrod to 755
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/Axelrod-0.0.9.egg-info
Writing /usr/local/lib/python2.7/dist-packages/Axelrod-0.0.9.egg-info
*** Warning: The database is older than 7 days.
*** Run 'paco -ua' to update it.
user@tower:~/repos/Axelrod$ ./run_axelrod --rc -p 0 --xs --xc --xa
Starting basic_strategies tournament with 10 round robins of 200 turns per pair.
Finished all basic_strategies tasks in 2.2s
Finished all tournaments in 2.2s
```

Then I have the correct plot in my Axelrod directory (with the correct timestamp).

**Comment by drvinceknight** [comment]
Cool, you don't really need to run `setup.py`, you're calling the local `run_axelrod` there as far as I can but thanks for checking it. 

So it looks like it's just a bug on my side... Surely not though, how weird that it happens on two of my machines... 

I get the exact same behaviour with and without your patch `user@tower:~/repos/Axelrod$ git checkout 258 # With my patch` can you confirm that you get the bug without it? 

I'm puzzled...

**Comment by drvinceknight** [comment]
I thought that perhaps deleting all of the `pyc` files might help but to no avail...

**Comment by marcharper** [comment]
I still get the right plot with upstream:

```
user@tower:~/repos/Axelrod$ git checkout upstream 
Already on 'upstream'
Your branch is up-to-date with 'github-axelrod/master'.
user@tower:~/repos/Axelrod$ ./run_axelrod --rc -p 0 --xs --xc --xa
Starting basic_strategies tournament with 10 round robins of 200 turns per pair.
Finished all basic_strategies tasks in 2.2s
Finished all tournaments in 2.2s
```

Have you tried rebuilding the cache?

**Comment by drvinceknight** [comment]
> Have you tried rebuilding the cache?

Just tried and no difference... This might just be something strange with my matplotlib installs (although have done this on two machines in virtual envs as well)...

Off to walk the puppy now... Will be good to see if @meatballs has anything similar... Very strange... Thanks a lot for taking the time to look in to this @marcharper...

**Comment by marcharper** [comment]
I just did a fresh clone in a virtual machine and I get the bugged version, even with rebuilding the cache, on both master and 258 (with or without my patch). I'm using the standard ubuntu repository versions of matplotlib and everything else.

However I still get the right plot on my other machine -- very strange!

**Comment by marcharper** [comment]
One difference -- working machine has matplotlib 1.3.1, not working virtual machine has 1.4.3.

**Comment by drvinceknight** [comment]
Lol, that's really weird, I'm running 1.4.2, which is what's in the requirements.txt. I get this bug even with a pure pip install of the requirements... How strange...

**Comment by meatballs** [comment]
All works perfectly for me on both master and 258. I have matplotlib 1.4.3

**Comment by drvinceknight** [comment]
Ok, so I'm pretty sure it's a weird `matplotlib` bug and nothing to do with the actual code. Changing the image format to `.pdf` or `.svg` makes everything work fine for me (but `png` still broken).

So #260 just needs someone who still can to run the actual results, @meatballs would you mind doing that? Then we can close #258. 

I'm not sure what the best way forward about this 'bug' is...

**Comment by drvinceknight** [comment]
Is there any reason why we're returning `png` by default instead of `svg`?

**Comment by marcharper** [comment]
SVG support in general in not as good as other formats; git will track SVG files as text files. How do you feel about JPEG or something else?

**Comment by drvinceknight** [comment]
> SVG support in general in not as good as other formats; git will track SVG files as text files.

True re git but in general vector graphics are preferable as there are no issues of pixelation etc so I'd prefer vector based ideally... In general for publications I go with pdf version (vector based) but they're not web supported...

I don't think the fact that git tracks them as text files is actually a negative is it?

**Comment by marcharper** [comment]
If you want SVG that's fine with me, I was just stating what I thought the original reasons might have been.

**Comment by drvinceknight** [comment]
> If you want SVG that's fine with me, I was just stating what I thought the original reasons might have been.

Cool, I'll put a PR together changing to SVG and juts make sure docs are ok etc... In case that was a reason. Whether or not that is a fix for this _bug_ is another question though, it seems like I'm the only one with the issue right? Basing that on the fact that you've been able to update the results for #260 :)

**Comment by marcharper** [comment]
Yes, I'm not able to reproduce the issue reliably.
