### ISSUE TITLE
Move the tournament results to the tournament repository

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#265]
We discussed making this repository a 'pure' version of the library.

We are going to move `run_axelrod`, assets and the cache to this repository: https://github.com/Axelrod-Python/tournament which has a single `gh-pages` branch.

**Comment by drvinceknight** [comment]
I suggest:

- Copy things over and make the tournament repository as is wanted
- Change docs, readme, github.io page to get images served by that repository
- Remove things that are no longer necessary here (via PR)

**Comment by marcharper** [comment]
Can we close this one?

**Comment by drvinceknight** [comment]
Yup, fine by me. Does that need to be rerun by the way? I haven't really been keeping on top of things...
