### ISSUE TITLE
Tournaments sometimes do not finish processing?

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#282]
When running `run_axelrod` (now in the tournament repository) with multiple processes sometimes the tournament seems to hang in `self._process_done_queue`. Here's the traceback when it is manually killed (after the processes all become zombies):

```
user@tower:~/repos/axelrod/tournament$ sh update_results.sh 
-- Regenerating noisy tournament figures
Starting basic_strategies tournament with 10 round robins of 200 turns per pair.
Finished all basic_strategies tasks in 1.1s
Starting strategies tournament with 10 round robins of 200 turns per pair.
Finished all strategies tasks in 41.3s
Starting cheating_strategies tournament with 10 round robins of 200 turns per pair.
Finished all cheating_strategies tasks in 6.8s
Starting all_strategies tournament with 10 round robins of 200 turns per pair.
^CTraceback (most recent call last):
  File "./run_axelrod", line 116, in <module>
    run_tournaments(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/axelrod/utils.py", line 69, in run_tournaments
    manager.run_tournaments()
  File "/usr/local/lib/python2.7/dist-packages/axelrod/tournament_manager.py", line 50, in run_tournaments
    self._run_single_tournament(tournament)
  File "/usr/local/lib/python2.7/dist-packages/axelrod/tournament_manager.py", line 71, in _run_single_tournament
    tournament.play()
  File "/usr/local/lib/python2.7/dist-packages/axelrod/tournament.py", line 50, in play
    self._run_parallel_repetitions(self._outcome)
  File "/usr/local/lib/python2.7/dist-packages/axelrod/tournament.py", line 96, in _run_parallel_repetitions
    self._process_done_queue(workers, done_queue, outcome)
  File "/usr/local/lib/python2.7/dist-packages/axelrod/tournament.py", line 119, in _process_done_queue
    output = done_queue.get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 117, in get
    res = self._recv()
KeyboardInterrupt
```

However upon rerunning, all the tournaments often complete in just a few minutes. I have not collected much data, but it seems to happen about 20% of the time.

**Comment by meatballs** [comment]
I hit something similar to this when I originally wrote the multiprocessing code. At the time, I wasn't handling the queue properly and it was filling (there's a maximum size limit). That shouldn't be the case now, but this is awfully familiar!

**Comment by marcharper** [comment]
Hmm that could be it -- I have a very fast machine (> 4Ghz) running 8 processes at a time.

**Comment by drvinceknight** [comment]
Has this been fixed? I've just run a bunch of tournaments with no issues...

**Comment by marcharper** [comment]
It still happens on my machine, but if no one else has experienced the issue then perhaps there's something is awry with my python installation.

**Comment by drvinceknight** [comment]
It did happen to me once a while ago (just before this issue went up) but
not since...

**Comment by marcharper** [comment]
So I upgraded from Ubuntu LTS to the latest short life release and I can no longer reproduce the issue. So either my installation was corrupted or there is some sort of issue with 14.04 (in case someone brings this up again in the future).

For now I'm going to close as "not reproducible".
