### ISSUE TITLE
Issue with `mpl_toolkits`

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#290]
A student of mine had a problem with the graphical outputs. He was using axelrod (installed via `pip`) on Windows (which is going to make reproducing this tricky), `matplotlib` was installed (v 1.4.3) and while that means that `mpl_toolkits` should be there it wasn't (for some reason...).

```
import matplotlib.pyplot as plt
import matplotlib.transforms as transforms
from mpl_toolkits.axes_grid1 import make_axes_locatable
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ImportError: No module named mpl_toolkits.axes_grid1
```

This caused an awkward failure as the following from `plot.py` kicked in:

```
matplotlib_installed = True
try:
    import matplotlib.pyplot as plt
    import matplotlib.transforms as transforms
    from mpl_toolkits.axes_grid1 import make_axes_locatable
except ImportError:
    matplotlib_installed = False
```

The exception kicking it and it was difficult to even find out why no graphical output was coming through... The error was just:

```
p = plot.stackplot(eco.population_sizes)
p.show()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'show'
```

The exception with `matplotlib_installed = True` above was put in place at the beginning of the project when I was quite keen on making things work even if certain packages where not installed (ie if the library was not pip installed). 

Does anyone have any thoughts on the following:

1. I have no idea how to fix this, it looks like an error with installing matplotlib that did not bring the toolkit with it on Windows (tried multiple times via virtualenv and [SMC](cloud.sagemath.com))... A quick google gave me nothing... Not sure if anyone has any thoughts... This is not super important, my student is using it on SMC right now.
2. Is it worth changing this 'fail quietly' infrastructure? At least the error message would have come up sooner and clearer if it was not there... At the moment if you don't have numpy installed the library won't function.

**Comment by marcharper** [comment]
Looks like a [known issue with mpl](https://github.com/matplotlib/matplotlib/issues/4907), so I'd say it's not our bug for the time being.

**Comment by drvinceknight** [comment]
https://blogs.windows.com/windowsexperience/2016/04/06/announcing-windows-10-insider-preview-build-14316/

**Comment by drvinceknight** [comment]
I think that this is not an issue anymore? Based on test suite running and passing on appveyor.
