### ISSUE TITLE
Is a strategy that pays attention to which strategy it is playing against considered "honest"?

### ISSUE THREAD

**Issue by daira** [Axelrod-Python/Axelrod#291]
https://axelrod.readthedocs.org/en/latest/contributing.html#is-your-strategy-honest says:

"The rules for an ‘honest’ strategy are very simple:

* It does not change what it’s opponents do/know.
* It forgets everything every time it starts playing someone (this is implemented with the reset method)."

Consider a strategy that obtains the class name or code of its opponent (so that it is able to simulate, but not change, what its opponent will do in response to its own move). Is this honest? It seems to meet the definition.

**Comment by meatballs** [comment]
Welcome, Daira!

I'd say that your example is not honest and we need to change the description.

(Also, the apostrophe in "it's" needs to go)!!

**Comment by daira** [comment]
OK cool. Looking through the existing strategies, I think there's a useful distinction between:
* strategies that try to find out how their opponent will behave (and which cannot guarantee to succeed in doing so if their opponent is nondeterministic); and
* strategies that attempt to change what their opponent does or knows.

The latter are interesting for a "code wars"-style, anything-goes tournament, but the former are more interesting to me personally because they can model social phenomena like peer group recognition, and can be independent of low-level details of the Python environment.

**Comment by meatballs** [comment]
> OK cool. Looking through the existing strategies, I think there's a useful distinction between:

> * strategies that try to find out how their opponent will behave (and which cannot guarantee to succeed in doing so if their opponent is nondeterministic); and
* strategies that attempt to change what their opponent does or knows.

I'd agree. Up until now, we've only distinguished between those that comply with Axelrod's original rules and those that do not. I'd support a more nuanced differentiation along the lines you suggest.

**Comment by langner** [comment]
In my view inspecting other players beyond a basic set of properties
related to the "actual game" crosses a boundary. Why? Because it inevitably
leads to strategies tweaking their own internals so as to mislead other
strategies. That falls into the category of strategies that attempt to
change what their opponent does or knows, except that the method is
passive. Ultimately I think the point is to stick to the IPD and not
venture into any kind of code war.

**Comment by daira** [comment]
Being able to simulate the behaviour of your opponent strategy (as a black box) doesn't seem as though it would lead to excessive tweaking of internals to me. Axelrod already includes strategies that do this, as well as strategies that do more active cheating; the proposal is just to distinguish those two groups and to clarify the definition of "honest".

**Comment by marcharper** [comment]
You all might be interested in [this article](https://qchu.wordpress.com/2013/06/30/cantors-theorem-the-prisoners-dilemma-and-the-halting-problem/), in which strategies are able to examine the source codes of their opponents, which leads to some very interesting results.

**Comment by marcharper** [comment]
As for the definition of honest, the typical rules assume that players:
* do not retain state between tournaments
* cannot modify the source of other players
* only have access to opponents decisions, not their source code or internal variables (despite python providing these). This implies access to read (but not modify) the opponent's history (since a copy of the history of play could be retained by any player). Some tournaments go so far as to assign players generic IDs from which the player's "class" cannot be inferred (sometimes called tagging). My colleagues and I [studied](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0120625) how one can infer the strategy of an opponent under these constraints (it's not difficult for memory-one strategies). See also the discussion #138.

As for simulating play of another strategy, I don't necessarily think that is necessarily dishonest, but it needs to be done carefully so as to not mess with the internal state and history of a player. Take a look at MindReader, which does something like this, but not perfectly because of deepcopy loops.

I have no problem with adding more such strategies to the library, but I don't think they should be considered "ordinary strategies".

**Comment by drvinceknight** [comment]
Hi @daira: welcome :) If you haven't seen our gitter.im room feel free to jump in and say hi: https://gitter.im/Axelrod-Python/Axelrod

> I have no problem with adding more such strategies to the library, but I don't think they should be considered "ordinary strategies".

Yeah, from the beginning 'code wars' have been accepted (and good fun) but they've always had to be clearly marked as `cheater` strategies. As @marcharper said `MindReader` is a good example of this. At the very beginning @langner went in to a nice best response dynamic with another contributor by better-ing each other's knowledge of how python could be used to manipulate other strategies.

**Comment by drvinceknight** [comment]
Re:

> "The rules for an ‘honest’ strategy are very simple:
> 
> It does not change what it’s opponents do/know.
> It forgets everything every time it starts playing someone (this is implemented with the reset method)."

Should we change that to:

"The rules for an ‘honest’ strategy are very simple:

It does not change what its opponents do/know.
It does not inspect its opponents source code.
It forgets everything every time it starts playing someone (this is implemented with the reset method)."

?

**Comment by marcharper** [comment]
Sounds good to me. Let's also keep in mind one of the goals of the library:

2. To produce the de-facto tool for any future Iterated Prisoner's Dilemma research.

So if people want to use the library to study strategies that read the source code of other strategies, or tournaments that relax the "no reading source code rule", that's great! The distinction between cheating and non-cheating only affects the default tournaments that are run to update the results [here](https://github.com/Axelrod-Python/tournament) -- anyone is free to run tournaments with any combination of strategies that they please.

**Comment by drvinceknight** [comment]
Yeah: I completely agree @marcharper.

On 4 September 2015 at 23:09, Marc Harper, PhD <notifications@github.com>
wrote:

> Sounds good to me. Let's also keep in mind one of the goals of the library:
>
>    1. To produce the de-facto tool for any future Iterated Prisoner's
>    Dilemma research.
>
> So if people want to use the library to study strategies that read the
> source code of other strategies, or tournaments that relax the "no reading
> source code rule", that's great! The distinction between cheating and
> non-cheating only affects the default tournaments that are run to update
> the results here <https://github.com/Axelrod-Python/tournament> -- anyone
> is free to run tournaments with any combination of strategies that they
> please.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Axelrod-Python/Axelrod/issues/291#issuecomment-137853966>
> .
>



-- 
Dr Vincent Knight
Cardiff School of Mathematics
Senghennydd Road,
Cardiff
CF24 4AG
(+44) 29 2087 5548

**Comment by langner** [comment]
> Being able to simulate the behaviour of your opponent strategy (as a black box) doesn't seem as though it would lead to excessive tweaking of internals to me. Axelrod already includes strategies that do this, as well as strategies that do more active cheating; the proposal is just to distinguish those two groups and to clarify the definition of "honest" to exclude both.

Of course, this is all fine. By 'crosses a boundary' I meant into the realm of cheating strategies.

And... welcome!

**Comment by marcharper** [comment]
So we just had a conversation in the gitter room, and came to the conclusion that whether a strategy is honest or not depends on the rules of the tournament. We're in favor of adding a dictionary to the Player class that denotes e.g.

* reads_source = True
* modifies_source = False
* memory_depth = 1
* etc.

Then whomever is running the tournament can decide if e.g. reads_source == True makes a strategy a cheater or not and include or exclude as desired. We can then calculate the list of "ordinary strategies" as those that do not read opponent's source (and whatever other attributes) for run_axelrod without having to label strategies as cheaters or not in _strategies.py . Also new users will not have to inspect the code of each strategy to determine whether it does something unexpected.

Possible additional attributes:
* in_first_axelrod, in_second_axelrod, etc.
* Any suggestions?

Thanks to @daira for opening this issue and sparking the discussion!

**Comment by drvinceknight** [comment]
Yeah this was a great discussion and I'm super happy with the outcome :) 

As well as all the advantages we discussed last night having **all** the strategies under `axelrod.strategies` will be much clearer. 

Also, just to add that by default we can have a classifier set to `None` which would indicate no classification for a given strategy on that particular dimension which means that adding a new dimension is not a big pain.

**Comment by meatballs** [comment]
I can pick this one if everyone is happy for it to go ahead

**Comment by drvinceknight** [comment]
:+1: Super happy for it to go ahead, I think it's an exciting enhancement.

**Comment by langner** [comment]
+1

**Comment by daira** [comment]
reads_source seems a little imprecise to me. The property I think we want to specify is whether a strategy has any more information than is given by the history of moves so far.

Similarly, the other property we're interested in is whether a strategy interferes with its opponent in any way. (This should include anything that allows it to predict random choices more accurately than simply knowing the distributions of those choices, as well as more active cheating.)

**Comment by daira** [comment]
I suggest ``inspects_opponent`` and ``interferes_with_opponent``.

@drvinceknight wrote:
> Also, just to add that by default we can have a classifier set to None which would indicate no classification for a given strategy on that particular dimension which means that adding a new dimension is not a big pain.

+1. Perhaps we can expose an ``opponent.get(classifier)`` method iff the strategy being run has the ``inspects_opponent`` classifier.

(Of course Python can't enforce that code doesn't use various other tricks to find out about its opponent, but this would make new strategies easy to review.)

**Comment by drvinceknight** [comment]
> Similarly, the other property we're interested in is whether a strategy interferes with its opponent in any way. (This should include anything that allows it to predict random choices more accurately than simply knowing the distributions of those choices, as well as more active cheating.)

Do you mean for example the cases like `Meta Hunter`?

This could be yet another dimension?

> I suggest inspects_opponent and interferes_with_opponent.

I still actually prefer `read_source` and `modifies_source` as well as a potential further one for things like MetaHunter but this I'm sure we can settle on the particular terms eventually... :)

**Comment by meatballs** [comment]
> but this I'm sure we can settle on the particular terms eventually... :)

Time to settle on them now! Work done so far is available on branch 291. I've created a Player.behaviour dictionary, which currently holds 'stochastic' and 'memory_depth' keys, and updated the tests and RoundRobin/Tournament classes to use it.

Next jobs are to add the new dimensions, get rid of the existing strategy classifications and update the documentation.

**Comment by meatballs** [comment]
> I suggest inspects_opponent and interferes_with_opponent.

Me too. I think that's a very clear description of the behaviour.

**Comment by drvinceknight** [comment]
>> I suggest inspects_opponent and interferes_with_opponent.
> Me too. I think that's a very clear description of the behaviour.

All strategies all inspect the opponent to some extent (by looking at the history) whereas including the term `source` clearing indicates doing something that's a bit more than just 'looking at the opponent'.

> Work done so far is available on branch 291. I've created a Player.behaviour dictionary, which currently holds 'stochastic' and 'memory_depth' keys, and updated the tests and RoundRobin/Tournament classes to use it.

I would prefer the dictionary be called `classifiers` (or something like that) as this is exactly what it's for whereas behaviour is perhaps a bit misleading.

> Next jobs are to add the new dimensions, get rid of the existing strategy classifications and update the documentation.

I would suggest putting all the strategies under `axelrod.strategies` although it could be nice to also include some in  `axelrod.basic_strategies` (the elements of which would also be in `axelrod.strategies`) as it's a nice tool to keep just for being able to super quickly create a small tournament (it's been very useful for demos).

**Comment by meatballs** [comment]
> All strategies inspect the opponent to some extent (by looking at the history) whereas including the term source clearing indicates doing something that's a bit more than just 'looking at the opponent'.

OK. Fair point.

**Comment by meatballs** [comment]
> I would prefer the dictionary be called classifiers (or something like that) as this is exactly what it's for whereas behaviour is perhaps a bit misleading.

Oh Lord, that's a lot of 'find and replace.' How much do you care?!!

**Comment by meatballs** [comment]
> I would suggest putting all the strategies under axelrod.strategies although it could be nice to also include some in  axelrod.basic_strategies (the elements of which would also be in axelrod.strategies) as it's a nice tool to keep just for being able to super quickly create a small tournament (it's been very useful for demos).

My next question was going to be about the basic strategies. I think we should try to find some dimension that properly differentiates them and git rid of that classification if we can.

**Comment by drvinceknight** [comment]
Perhaps keep it as it is for now? I could 'jedi refactor' it when it comes to being merged in once we've all discussed and figured out the ideal terminology :)

With all this I can't say I'm overly precious about it: just good for us all to be happy with the conventions :)

**Comment by drvinceknight** [comment]
> My next question was going to be about the basic strategies. I think we should try to find some dimension that properly differentiates them and git rid of that classification if we can.

Yeah I thought that but I do think there's something to be said for being able to create a basic tournament in a very simple way:

```
strategies = [s() for s in axelrod.basic_strategies]
```

is nicer than:

```
strategies = [s() for s in axelrod.strategies if s().classifier['basic_strategy']]
```

All it means is that in `_strategies.py` we'd have:

```
basic_strategies = [Cooperators, ...]

strategies = basic_strategies + [Hunter, ...]
```

I see why it's a bit not ideal because everything is so clean with the `behaviour/classifier` dictionary but I do really like the syntax of `axelrod.basic_strategies` for a quick tournament... What does everyone else think?

**Comment by drvinceknight** [comment]
I also think the problem with including `basic_strategy` as a classification dimension is that it's arguably a bit subjective... Which is what's so great about the `classifier/behaviour` dictionary is that it's not going to be subjective at all.

**Comment by meatballs** [comment]
I suppose I was wondering if we can find some sort of behaviour that distinguishes those strategies as 'basic.' If not, let's go with your suggestion above.

**Comment by drvinceknight** [comment]
:+1:

**Comment by meatballs** [comment]
How about ```inpsects_opponent_source``` and ```updates_opponent_source```?

**Comment by drvinceknight** [comment]
> How about inpsects_opponent_source and updates_opponent_source?

Yeah that seems like a good idea. What about also `manipulate_opponent` for things like `*Hunter`?

**Comment by meatballs** [comment]
I'm missing something here. What do the Hunter strategies do that should require the extra dimension? They just look for patterns in the history, don't they?

**Comment by drvinceknight** [comment]
Sorry: you're very right, I have managed to confuse myself with the
folklore of Hunter! Ignore me :)


On 6 September 2015 at 13:56, Owen Campbell <notifications@github.com>
wrote:

> I'm missing something here. What do the Hunter strategies do that should
> require the extra dimension? They just look for patterns in the history,
> don't they?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Axelrod-Python/Axelrod/issues/291#issuecomment-138081652>
> .
>



-- 
Dr Vincent Knight
Cardiff School of Mathematics
Senghennydd Road,
Cardiff
CF24 4AG
(+44) 29 2087 5548

**Comment by marcharper** [comment]
Some of the strategies actually overwrite the opponent's strategy function, like MindBender. In principle a strategy could overwrite an opponent's history or internal state without rewriting its source (and MindReader does this to some strategies).

All the basic strategies have memory depth 0 or 1 (as well as some others that are not so basic, like the ZD strategies, GTFT, and Joss).

**Comment by meatballs** [comment]
so a third dimension ```overwrites_opponent_strategy``` or not bother with ```updates_opponent_source```?

**Comment by marcharper** [comment]
I don't see the use case for a distinction between "manipulates opponent source" and "overwrites opponent source"; "interferes with opponent" seems ambiguous to me.

How about:

* stochastic (bool, False/None)
* memory_depth: int/float [default float('inf') ? ]
* inspects_opponent_source (bool, False/None)
* manipulates_opponent_source (bool, False/None) [What MindBender does]
* manipulates_opponent_state (bool, False/None) [What MindReader does implicitly, or a hypothetical retroactive history modifier]

And define basic strategies as:
not stochastic and not inspects and not manipulates and memory_depth <= 1

**Comment by drvinceknight** [comment]
> stochastic (bool, False/None)
> memory_depth: int/float [default float('inf') ? ]
> inspects_opponent_source (bool, False/None)
> manipulates_opponent_source (bool, False/None) [What MindBender does]
> manipulates_opponent_state (bool, False/None) [What MindReader does implicitly, or a hypothetical retroactive history modifier]

:+1: 

Sounds good to me.

> And define basic strategies as:
> not stochastic and not inspects and not manipulates and memory_depth <= 1

The only really purpose of having `basic_strategies` is for the ease of being able to create a simple tournament with little complications. If we all agree with that I think keeping the status quo and just having them in a list makes sense. I don't like the idea of defining another classification dimension for this as it's not really objective...

**Comment by drvinceknight** [comment]
> The only really purpose of having basic_strategies is for the ease of being able to create a simple tournament with little complications

To be clear: I was trying to word that as a question? Do people agree/disagree?

**Comment by marcharper** [comment]
Yes, I think it's fine. Rather than this:
```
basic_strategies = [Cooperators, ...]
strategies = basic_strategies + [Hunter, ...]
```
I would favor:
```
strategies = [...all strategies..]
basic_strategies = [s for s in strategies if ...criteria for basic strategies...]
```

This still provides axelrod.basic_strategies for the purpose you describe, and captures new strategies automatically. To that end we could have two functions for filtering: `is_basic` and `follows_standard_axelrod_rules`, and similarly define `ordinary_strategies` as:
```
ordinary_strategies = [s for s in strategies if follows_standard_axelrod_rules(s)]
```

**Comment by drvinceknight** [comment]
Yeah that looks good to me. All this will need to be nicely/carefully documented (the docs need a good overhaul...).

Re `ordinary_strategies`, are you thinking of including that in the library or just leaving that as a 'thing a user can do'?

**Comment by marcharper** [comment]
I like the current setup for automatically updating the plots in the tournament repository, so keeping something like ordinary_strategies serves that purpose, codifies the "axelrod rules", and gives users another example. So I would vote to keep it in (perhaps with a name other than ordinary).

**Comment by drvinceknight** [comment]
My only worry (a very minor worry) is that keeping `ordinary_strategies` in the tournament itself kind of steps backwards in that we are defining things in the tournament (I realise I'm suggesting do that for `basic_strategies`) whereas we could simply include/move `ordinary_strategies = [s for s in strategies if follows_standard_axelrod_rules(s)]` in the script used in the tournament (which itself is a good example for users).

I'm in no way convinced either way but just thinking aloud...

**Comment by marcharper** [comment]
It doesn't really matter, but think about the docs. It would be nice to have a passage like:

The strategies that conform to the rules of Axelrod's original tournaments are available in `axelrod.ordinary_strategies`, formed as follows:
```
ordinary_strategies = [s for s in axelrod.strategies if follows_standard_axelrod_rules(s)]
```

where `follows_standard_axelrod_rules` is defined as ...

You can filter the collection of strategies to a different subset for whatever tournament rules you desire in a similar fashion. For instance if you want to allow strategies to inspect the source code of other strategies, you can use a function such as the following...

**Comment by drvinceknight** [comment]
> It doesn't really matter, but think about the docs. It would be nice to have a passage like:

Very true... Could just as well have:


The strategies that conform to the rules of Axelrod's original tournaments are available in can be obtained by writing:
 
ordinary_strategies = [s for s in axelrod.strategies if follows_standard_axelrod_rules(s)]

Just thinking aloud here...

**Comment by langner** [comment]
> The only really purpose of having basic_strategies is for the ease of being able to create a simple tournament with little complications

I believe I created basic_strategies and this was precisely the reason.

**Comment by meatballs** [comment]
I can't see any harm in keeping basic_strategies and ordinary_strategies within the library (but dynamic as described above). As long as we are providing sufficient dimensions for those who want to do something different, why not make life easier where we can?

**Comment by drvinceknight** [comment]
That's seems sensible to me :)

**Comment by meatballs** [comment]
If I make ```None``` the default for both ```inspects_opponent_source``` and ``manipulates_opponent_state```, then we'll need to go through every strategy and set them properly before the dynamic selection functions will work.

However, if I make ```False``` the default, we only need to sort out the cheating strategies.

The latter is more attractive to me at the moment, as I'm struggling to find much time for this, but I'm conscious that it might be confusing to have ```behaviour``` dictionaries across strategies with different keys defined - some rely on the defaults and others do not.

Also, for now, I'm only testing for the existence of the keys in the dictionary so I don't also have to go through every strategy test.

**Comment by langner** [comment]
You could also write some code that analyzes player code and categorizes it accordingly.

**Comment by marcharper** [comment]
It's fine as either False or None, no? The conditionals should work with either None or False:

>>> (not None) and (not None)
True
>>> (not False) and (not False)
True
>>> (not False) and (not True)
False
>>> (not None) and (not True)
False

**Comment by drvinceknight** [comment]
> If I make None the default for both inspects_opponent_source and manipulates_opponent_state`, then we'll need to go through every strategy and set them properly before the dynamic selection functions will work.

> However, if I make False the default, we only need to sort out the cheating strategies.

I think it's important to have `None` as the default for things that have not been set yet. Using `False` implies that something has been categorised. Marc's right that the conditionals will work but we should be able to find strategies that are not classified yet too... 

Perhaps this can be done in two steps @meatballs? Perhaps just implement the classifier for now and leave the dynamic setting of strategies for another issue? My project student could possibly take care of that as a first contribution? I might also be able to get to it, perhaps we can share out strategies?

Another suggestion: we currently have the non cheating strategies in a list, so we could write a script that takes them and sets the attribute in the classifier dictionary perhaps? Then only the cheating strategies need to be looked at carefully. This can still be done as a second issue/pr though.

**Comment by drvinceknight** [comment]
Just pulled down and taken a look at 291, let me know what you think of my above suggestions @meatballs, perhaps we can share out what needs to be done (if you don't want to go down the line of 1 PR for creating the dictionary which it looks like you have already more or less done and 1 to create the dynamic classification and get rid of the old one). Speaking at the British Science Festival today but should/might have some time this afternoon but also have 4 hours of train time tomorrow am :)

**Comment by meatballs** [comment]
> It's fine as either False or None, no? The conditionals should work with either None or False

Aggghhh!! Of course!! Thank you.

> I think it's important to have None as the default for things that have not been set yet. Using False implies that something has been categorised. Marc's right that the conditionals will work but we should be able to find strategies that are not classified yet too... 

Yep. I should have thought of that!

> Perhaps this can be done in two steps @meatballs? Perhaps just implement the classifier for now and leave the dynamic setting of strategies for another issue? 

Step 1 is done and available on branch 291
