### ISSUE TITLE
What should basic_strategies be?

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#297]
On #296 (which has now been merged in) @langner, @marcharper and I had a chat about `basic_strategies`. Marc wrote a nice function that defined basic strategies however this changed the `basic_strategies` to:

Alternator
Anti Tit For Tat
Bully
Cooperator
Defector
Soft Go By Majority
Suspicious Tit For Tat
Tit For Tat
Win-Stay Lose-Shift

which Karol and I thought (please correct me if I'm speaking incorrectly on your behalf Karol) was a bit too much for the purposes of a demo - which is what I thought `basic_strategies` was for.

I wonder however if a demo would be better served by:

```
strategies = [axelrod.Alternator(), axelrod.Cooperator(), axelrod.Defector(), axelrod.Random(), axelrod.Tit For Tat()]
```

As this shows how to access strategies (using a JuPyTer notebook, this would be quite nice with tab completion for example), then `basic_strategies` can be used to show a bit more of a complicated tournament?

What do people think? I think it's a good one to chat about :) 

Note that the actual work for this has more or less already been done and can be cherry-picked.

**Comment by meatballs** [comment]
Personally, I think it's useful to have a dynamic generation of strategies which are 'basic' as defined by their classifiers.

However, if people also find it useful to have a static list for ```demo_strategies``` then I have no objection to that.

**Comment by drvinceknight** [comment]
Yeah I think I'm coming around to that also. Whether or not you use
demo_strategies is up to the particular demo... I think I might not
actually use it myself and just use tab completion to show grabbing each
strategy...

As new dimensions come in, we could also potentially include them in the
is_basic function (just thinking put loud, not very relevant right now).

**Comment by langner** [comment]
I'm fine with the dynamic one, too.

**Comment by marcharper** [comment]
If you do want to get the basic_strategies code back, just rollback the last commit (c031c23ce0d5d2984b6cce60dc32f0c0f3cff3a0), which removed `is_basic` and the associated tests. Then just put this back in for demo_strategies (if you want this in the library):

```
# Defined by fiat for demo purposes
demo_strategies = [Alternator, Cooperator, Defector, Random, TitForTat]
```

**Comment by drvinceknight** [comment]
I'm on it :)

**Comment by drvinceknight** [comment]
I believe #298 takes care of this now :)

Sorry for being a pain @marcharper.

**Comment by marcharper** [comment]
No worries
