### ISSUE TITLE
Add reproduce method to Player class

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#303]
Sometimes players need to be duplicated (e.g. when playing against themselves or in a dynamic like the Moran process). Right now we handle this with `copy` in round_robin.py:
```
def _pair_of_players(self, player1_index, player2_index):
        player1 = self.players[player1_index]
        class1 = player1.__class__
        if player1_index == player2_index:
            # Check for arguments in __init__. If more than one (self), then
            # deepcopy rather than instantiating the class variable
            argspec = inspect.getargspec(player1.__init__)
            if len(argspec.args) > 1:
                player2 = copy.deepcopy(player1)
            else:
                player2 = class1()
                player2.tournament_attributes = player1.tournament_attributes
            class2 = class1
        else:
            player2 = self.players[player2_index]
            class2 = player2.__class__
        return player1, player2, (class1, class2)
```

Another (potentially better) solution would be for Player to have a reproduce or duplicate method that
* reapplies any arguments to `__init__` and instantiates a new player
* does not copy the history

The generic function in Player for most strategies would be as follows:
```
def reproduce(self):
    cls = self.__class__
    new_player = cls()
    return new_player
```

In strategies that use parameters in `__init__`, the function can be overridden to pass on those arguments appropriately.

Advantages:
* No more `copy` in round robin, which is slow and prevents strategies from themselves using copy.
* Can update MindReader to not alter opponent state
* Implementing the Moran process will be easier
* Concerns are properly separated (instances of Player handle their own copy constructor)

**Comment by drvinceknight** [comment]
Yeah this looks great :+1:

**Comment by langner** [comment]
I don't understand how using this is better than copy.deepcopy with additional tweaks.
