### ISSUE TITLE
Potential Sprint Ideas

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#306]
* More Axelrod tournament strategies #302 
* More hunter strategies, e.g. a cycle hunter (see what Calculator does)
* Generalize prober strategies
* TitForNTats, TatForNTits
* Rewrite Alternator as a special case of Cycler
* More tests (look at coverage report for gaps)
* Python 3.5 compatibility (maybe nothing to do but add to travis.yaml?)

**Comment by drvinceknight** [comment]
These are all great! Not sure about rewriting alternator... It's a simple strategy that nice go show to new comers (potentially people who don't write code) so think it's more readable as it is?

**Comment by langner** [comment]
A note about hunting: I considered writing a hunter for cycles in general, but they are already caught by RandomHunter most of the time (as are mathematical constant motivated strategies).

**Comment by marcharper** [comment]
I'm just trying to think of ways to push MetaHunter over the top, and cycle detection is relatively easy, so perhaps it's slightly better than having the RandomHunter catch it.

**Comment by marcharper** [comment]
Alternator is definitely more readable.
