### ISSUE TITLE
Make `python setup.py develop`

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#308]
Just speaking to @lvisintini , that command is supposed to install a simlink in your environment that means you can use the library in develop mode from anywhere. I expect this is a minor tweak to the `setup.py` script.

**Comment by lvisintini** [comment]
I'll pick this issue up unless someone is working on this already (speak now of forever hold your peace)

**Comment by drvinceknight** [comment]
Awesome! :+1:

**Comment by lvisintini** [comment]
This issue is addressed by PR #312
