### ISSUE TITLE
Installation on ubuntu

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#309]
Apparently matplotlib has issues on ubuntu and these two commands are needed:

```
sudo apt-get install libfreetype6-dev
sudo apt-get install libpng12-0-dev
```

We should add that to the readme somewhere.

**Comment by marcharper** [comment]
This is building from scratch or installing via the package manager? Also which version of Ubuntu?

**Comment by drvinceknight** [comment]
pip install was giving this problem. We think it's related to the other
issue with read the docs but I might have just had a solution suggested to
me. On the train right now, will test.

**Comment by bootandy** [comment]
Can confirm this happened to me using pip install matplotlib

Description:	Ubuntu 15.04
Release:	15.04

**Comment by drvinceknight** [comment]
Cool: I think we should just add those two lines to the README.md

**Comment by drvinceknight** [comment]
See PR #335
