### ISSUE TITLE
Inconsistent terminology used to describe rounds/turns/plays...

### ISSUE THREAD

**Issue by emmagordon** [Axelrod-Python/Axelrod#313]
This gets quite confusing!

Solution could be to clearly define some synonyms, or ideally make the docs/docstrings/comments/graphs etc.. all consistent in their use of terminology.

**Comment by meatballs** [comment]
:+1:

**Comment by drvinceknight** [comment]
I suggest we also add a `glossary.rst` and I suggest the following be the terminology:

- Turns are the 1 shot interactions between two players (throughout this has been confused with rounds).
- A Match is 200 turns
- A round robin is all the matches.

Note that this should be done in the documentation which is also being reworked #299

**Comment by marcharper** [comment]
See also #359 and #362 for moves/actions

**Comment by drvinceknight** [comment]
I've added a glossary #372 which is also starting to address #299.

**Comment by drvinceknight** [comment]
I hope that #384 coupled with the already merged in #372 address this.
