### ISSUE TITLE
`test_strategy` test in axelrod.tests.unit.test_player.py makes unwarranted assumptions

### ISSUE THREAD

**Issue by bricef** [Axelrod-Python/Axelrod#317]
The `test_strategy` method in the `TestPlayer` class makes unwarranted assumptions about the tests for a given strategy. in particular, it assumes that the tests for a given strategy will override the method, but this is not explicitly documented anywhere.

```
    def test_strategy(self):
        """Test that strategy method."""
        self.assertEqual(self.player().strategy(self.player()), None)
```

It feels that the test is really testing that a strategy is a sublcass of `Player`, but that's not really a behavioural test. It would be better to raise a `NotImplmentedError` and check that calling `strategy()` does not return this for all registered strategies.

My suggestions are as follows:

1. Make `strategy()` raise a `NotImplementedError` in the `Player` base class and resolve the broken tests
2. Make `test_strategy()` raise a `NotImplementedError` in the `TestPlayer` class and resolve the broken tests.
3. Change the docs to indicate all test subclasses should implement `test_strategy()`

I'm very strongly in favour of 1, as that's the pythonic and least suprirsing thing to do. It's also the one that would take the most work...

**Comment by bricef** [comment]
Hey @meatballs @drvinceknight @uglyfruitcake What do you guys think?

**Comment by drvinceknight** [comment]
I think I would go for the first option.

**Comment by meatballs** [comment]
Yep, I think option 1 is the way to go. (Sorry it's taken me so long to get around to saying so).

**Comment by bootandy** [comment]
I'd vote for option 1

**Comment by drvinceknight** [comment]
I think that's a consensus :)

Anyone want to pick this up?

**Comment by marcharper** [comment]
FYI (1) breaks about 150 tests.

**Comment by drvinceknight** [comment]
> FYI (1) breaks about 150 tests.

Yeah, we saw that at the pycon sprint... :( I still think it's the better option, what do you rekon @marcharper ?

**Comment by marcharper** [comment]
I'm for it, just a fair warning to anyone that takes it on.

**Comment by drvinceknight** [comment]
Hehe... Yeah...

**Comment by bootandy** [comment]
I'll have a look at this.
