### ISSUE TITLE
Read the docs not automatically updating for docs changes

### ISSUE THREAD

**Issue by emmagordon** [Axelrod-Python/Axelrod#318]
e.g. 9 days ago we had commit id '93a243fbff227fd2c3813053ccf12f0085489762' ('Adding more details to the docs'). This included the removal of incorrect instructions (in contributing.rst) to add any new strategy to one of the basic_/original_/cheating_strategies lists, but on read the docs that is still present.

**Comment by drvinceknight** [comment]
This seems to be a known issue caused by matplotlib/numpy. There are various solutions that include mock and a dummy requirements.txt file but I'm failing to get that to work. Working on it.

**Comment by drvinceknight** [comment]
It seems like 89d77ee5a0285d75889d4ef9c8e18872e7d60677 is the first commit where this fails but I see no reason why.

**Comment by drvinceknight** [comment]
```
OPTIONAL LATEX DEPENDENCIES
                dvipng: yes [version 1.14]
           ghostscript: yes [version 9.10]
                 latex: yes [version 3.1415926]
               pdftops: no

============================================================================
                        * The following required packages can not be built:
                        * freetype, png
```

Looks like we were looking for the wrong stuff. The above error message is also present on most successful builds.

**Comment by drvinceknight** [comment]
I am making no progress on this at all, *but* I have set read the docs up so I it no longer builds from master but from the `318` branch. (I really should have done this straightaway).

**Comment by drvinceknight** [comment]
I've opened https://github.com/rtfd/readthedocs.org/issues/1671 on rtds.
