### ISSUE TITLE
Cannot run unit tests on Windows with Python 2.7

### ISSUE THREAD

**Issue by emmagordon** [Axelrod-Python/Axelrod#322]
Running the axelrod unit tests on Windows with python 2.7 results in the following error:

python -m unittest discover -s axelrod.tests.unit
......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................s.F..s.s..........................................................................................................................................................................................Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Python27\lib\multiprocessing\forking.py", line 488, in prepare
    assert main_name not in sys.modules, main_name
AssertionError: **main**
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Python27\lib\multiprocessing\forking.py", line 488, in prepare
    assert main_name not in sys.modules, main_name
AssertionError: **main**

This is due to a known bug http://bugs.python.org/issue10845, the fix for which has not yet (may not ever be) ported to 2.7.X

**Comment by marcharper** [comment]
Is there anything we can do about this? Something like:
```
try:
     ....
except AssertionError:
     if os == "Windows":
           pass
     else:
           # re-throw exception
```

I'm not a fan of this kind of hackery but it doesn't look like the bug will ever be fixed.

**Comment by emmagordon** [comment]
May have just laughed out loud a bit ;)

Thinking about it though, I think this would be ok if there was also a print statement in the case where we silence the error (pointing out that the unit tests can't be run with this combination, and that the user should change OS or python version). 

The logic also needs changing to check for python2.7+Windows rather than just Windows.

**Comment by marcharper** [comment]
That sounds good to me. Unfortunately I don't have any windows machines, so we'll need someone with one to test a patch.

**Comment by emmagordon** [comment]
Happy to test a patch on my machine.

**Comment by drvinceknight** [comment]
It's certainly hacky... Can't say I'm a fan of 'dirtying' the tests for the sake of an OS... No idea what the right thing to do is though, there are surely some examples of libraries that have the same issue as us?

**Comment by drvinceknight** [comment]
I'm assuming this https://blogs.windows.com/windowsexperience/2016/04/06/announcing-windows-10-insider-preview-build-14316/ (bash on windows) will solve this?

**Comment by drvinceknight** [comment]
Whilst working on #721, I noted that the failure on 2.7 was now because of the mock module not necessarily being present in 2.7? It's not on there on appveyor...

I would suggest we could possibly close this issue though once we drop support for py2.

**Comment by marcharper** [comment]
Closing since we're no longer supporting 2.7.
