### ISSUE TITLE
Am I supposed to have full access to my player's opponent object?

### ISSUE THREAD

**Issue by bootandy** [Axelrod-Python/Axelrod#336]
'''
class Player:
  def strategy(self, opponent):
'''

^ I have full access to my opponent's object here. I can just call opponent.strategy(self) to see what they are going to do. Or I can rewrite their history for instance with opponent.history = ['C']

I would change this to pass a simplified copy of the opponent object - For instance one with just: history, cooperations and defections.

I can't work out if doing this change is against the spirit of the framework. Is doing things like opponent.history = ['C'] 'part of the fun' or should we try and make things like that harder to do?

**Comment by marcharper** [comment]
Each of the strategies has a classifying dictionary that indicates if there are shenanigans going on. In this case, we would set `'manipulates_source': True`, and such strategies can be excluded from tournaments if desired. Take a look at the strategies MindReader and MindBender.

**Comment by drvinceknight** [comment]
Yeah we deal with tomfoolery through the PR process, which has led to some neat 'cheating' strategies :) I'm going to go ahead and close this issue @bootandy (as it's been discussed a fair bit)  but by all means reopen it or jump in to the gitter room to chat :)
