### ISSUE TITLE
History and noise

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#348]
Currently the library records the post-noise play of each player in its history. By tracking its own plays a player can infer the noise rate by counting the number of flipped moves. (There is an example on my [noise_detector branch](https://github.com/marcharper/Axelrod/tree/noise_detector).) However it is not possible to tell if the opponent's moves are flipped.

In a related matter, we do not actually supply the noise parameter in the tournament arguments dictionary. If we did there would be no reason to infer the value but still reasons to track history and respond appropriately.

Any thoughts? I don't think that players usually know the noise level; but they don't usually know the number of rounds necessarily either.

**Comment by drvinceknight** [comment]
Nice idea. I don't see why we wouldn't give the info to the players.

As always: up to the users to make use of strategies that use the information or not.

**Comment by marcharper** [comment]
Agreed, but there is not an easy way of determining which strategies make use of any particular value in the tournament dictionary. So we might consider adding this to the classifier dictionary. Something like:
```
'makes_use_of': ("game_matrix", "tournament_length")
```

**Comment by drvinceknight** [comment]
I really like that suggestion!

**Comment by drvinceknight** [comment]
> I guess this could be automated by looking for e.g. "self.tournament_attributes["tournament_length"]" in the source.

I'm up for automating the process of writing the code but I'd still like to see it hard coded... (For readability...)

**Comment by bootandy** [comment]
I think a player should just know the length of the tournament, it makes strategies more interesting if you know you are near the end.

**Comment by bootandy** [comment]
I've just seen you can access self.tournament_attributes['length']

**Comment by marcharper** [comment]
In any case I think it needs to be classified (as suggested above) for each player whether it makes use of any additional information other than the opponent's history (and its own state). Some researchers study tournaments without a defined endpoint (see the discussion #37). With the classification, the list of strategies can be filtered as needed for whatever conditions the user wants to allow for their tournaments.

**Comment by drvinceknight** [comment]
> I think a player should just know the length of the tournament, it makes strategies more interesting if you know you are near the end.

I (humbly) think another way of saying that would perhaps be 'I think tournaments where strategies can know you are near the end are interesting' but of course as @marcharper points out other tournaments can be of interest to other people. The goal of the library is to facilitate **all those options** so as Marc says: it all needs to be classified and I **LOVE** the suggestion of all strategies having 'makes_use_of': ("game_matrix", "tournament_length")` which makes all these options really easy for the user.

**Comment by drvinceknight** [comment]
If no one wants this ticket, I might suggest my final year project student uses this as a first contribution?

**Comment by meatballs** [comment]
Go for it!

**Comment by marcharper** [comment]
A few notes:
* The PR should add "noise" to the tournament dictionary and pass the current tournament's value
* The classifier dictionary of every strategy gets a new key "makes_use_of" that has as its value a tuple of the tournament attributes that the strategy makes use of, if any (else an empty tuple/list). The strings in the tuple should be the same as the keys in the tournament_attributes dictionary
* Tests should be appropriately updated.

Bonus points:
* Try to detect usage automatically (with the `inspect` module) as part of another test that checks that every strategy's `make_use_of` classifier. This way if someone changes a strategy to use (or no longer use) one of the tournament attributes, it should trip the test

Double bonus points:
* Make the automated bonus test able to accept future new keys of the tournament_attributes dictionary

**Comment by drvinceknight** [comment]
Very helpful @marcharper to have that road map.

It'll no doubt take us a little while to get there and will be sure to not rush the PR through.

**Comment by marcharper** [comment]
I had a thought about strategies that use the tournament length. Some of the strategies in Axelrod's first tournament were modified not to use the tournament length in the second (since it was not constant).

It seems to me that they could easily check to see if they have that information and use it or not, and this way they can operate with or without the information.

**Comment by drvinceknight** [comment]
I'm probably going to pick this one up over the next couple of weeks.

**Comment by drvinceknight** [comment]
#433 is close to doing this but doesn't do any of the smart stuff that @marcharper suggested. I propose that #433 goes in (once all reviewers are happy), we close this issue and we open a new issue for:

> Bonus points:

> Try to detect usage automatically (with the inspect module) as part of another test that checks that every strategy's make_use_of classifier. This way if someone changes a strategy to use (or no longer use) one of the tournament attributes, it should trip the test
> Double bonus points:

> Make the automated bonus test able to accept future new keys of the tournament_attributes dictionary

**Comment by marcharper** [comment]
Fine by me.

**Comment by drvinceknight** [comment]
Have opened #442.
