### ISSUE TITLE
Tournament runtimes

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#354]
This came up on #344. Here's the runtime for the tournament repos update script:

```
user@tower:~/repos/axelrod/tournament$ sh update_results.sh 
-- Regenerating noisy tournament figures
Starting basic_strategies tournament with 10 round robins of 200 turns per pair.
Finished all basic_strategies tasks in 1.9s
Starting strategies tournament with 10 round robins of 200 turns per pair.
Finished all strategies tasks in 147.3s
Starting cheating_strategies tournament with 10 round robins of 200 turns per pair.
Finished all cheating_strategies tasks in 9.2s
Starting all_strategies tournament with 10 round robins of 200 turns per pair.
Finished all all_strategies tasks in 1792.5s
Finished all tournaments in 1950.9s
-- Running Axelrod, regenerating cache, results, and figures
Starting basic_strategies tournament with 10 round robins of 200 turns per pair.
Finished all basic_strategies tasks in 1.8s
Starting strategies tournament with 10 round robins of 200 turns per pair.
Finished all strategies tasks in 122.4s
Starting cheating_strategies tournament with 10 round robins of 200 turns per pair.
Finished all cheating_strategies tasks in 4.3s
Starting all_strategies tournament with 10 round robins of 200 turns per pair.
Finished all all_strategies tasks in 2890.0s
Finished all tournaments in 3018.5s
Be sure to git commit changes to update the docs!
```

Questions:
* Why is the noisy tournament faster?
* Should we do anything about the MindReader / Meta* Combo? The deepcopy in these instances are the source of the increase in runtime. I suspect this is because of the shared history being copied many times over (unnecessarily), but I don't really know exactly how deepcopy works.

**Comment by bootandy** [comment]
>Should we do anything about the MindReader / Meta* Combo
Yes I think we should do something. Firstly I need to run some analysis on exactly what they are doing. But I seem to recall they are responsible for a lot of the runtime in a tournament

**Comment by marcharper** [comment]
I think it's all the deep-copies, and that deep-copying a Meta strategy is particularly expensive.

**Comment by bootandy** [comment]
Ran:
python -m cProfile -s cumtime test.py

test.py looked like this:
strategies = [strategy() for strategy in axelrod.ordinary_strategies]
tournament = axelrod.Tournament(name='test', players=strategies, game=game, turns=30, repetitions=2)

Output ordered by cumulative time:

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
<cut>
   201780    0.192    0.000   10.774    0.000 player.py:111(play)
    54480    1.494    0.000    8.949    0.000 meta.py:42(strategy)
   135360    0.664    0.000    4.396    0.000 qlearner.py:47(strategy)
    22560    0.414    0.000    4.263    0.000 meta.py:129(strategy)
   128062    0.624    0.000    1.883    0.000 collections.py:38(__init__)
   128062    0.350    0.000    1.078    0.000 _abcoll.py:545(update)
   135360    0.360    0.000    0.726    0.000 qlearner.py:80(perform_q_learning)
   135360    0.173    0.000    0.559    0.000 qlearner.py:63(select_action)
    22560    0.423    0.000    0.527    0.000 meta.py:139(meta_strategy)
    47136    0.378    0.000    0.501    0.000 hunter.py:8(detect_cycle)
   170880    0.348    0.000    0.447    0.000 gobymajority.py:37(strategy)
   321144    0.284    0.000    0.434    0.000 {max}
   338400    0.341    0.000    0.433    0.000 memoryone.py:77(strategy)
   135360    0.160    0.000    0.406    0.000 qlearner.py:73(find_state)
    35640    0.036    0.000    0.401    0.000 hunter.py:102(strategy)

This profile run implies it is the meta and qlearner that are taking the most time.

**Comment by marcharper** [comment]
Right, but `MindReader` isn't an ordinary strategy, so it's not in this profile output. If you run all the tournaments that `run_axelrod` does by default, you'll see that the last tournament with all the ordinary strategies and all the "cheating" strategies takes by far the longest. I have put a good deal of effort into improving efficiency otherwise, but I haven't been able to come up with anything to substantially improve `MindReader` -- my last attempt is on [this branch](https://github.com/marcharper/Axelrod/tree/mindreader). I actually replayed the history each time rather than deep-copying. It was a wash in the end. 

Try a tournament with MindReader and some of the Meta strategies. The tournaments for ordinary_strategies are ok time-wise. Improvements still welcome of course :)

**Comment by bootandy** [comment]
You are quite right MindReader takes vastly more time than the other worst-offenders. 

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
4950/3750    0.142    0.000   96.481    0.026 mindreader.py:54(strategy)
    66450    1.936    0.000   11.353    0.000 meta.py:42(strategy)
```

**Comment by marcharper** [comment]
I'm sure it's the deepcopy on the MetaPlayers. Deepcopies are slow in general, and MindReader does a lot of them. With the MetaPlayers it's on another level, but there's not much we can do about that.

**Comment by bootandy** [comment]
Yes It does look like the deep copy is taking most of MindReader's time. 
```
 ncalls  tottime  percall  cumtime  percall filename:lineno(function)
 3380/2580    0.086    0.000   58.143    0.023 mindreader.py:55(strategy)
 2580    0.134    0.000   52.884    0.020 mindreader.py:24(look_ahead)
 55217700/5160   19.270    0.000   48.868    0.009 copy.py:145(deepcopy)
 84211/5225    0.332    0.000   48.807    0.009 copy.py:306(_reconstruct)
 183280/5160    0.579    0.000   48.680    0.009 copy.py:253(_deepcopy_dict)
 99038/8474   14.901    0.000   47.544    0.006 copy.py:226(_deepcopy_list)
```

I considered moving the deep copy of the opponent one line higher above the "for strategy in strategies:" loop and then updating the copy's history. But then if the opponent is updating other internal structures in its strategy method we would miss those on the second pass. So I don't like that idea.

The only thing I can think of is slimming down the Player object, but that is probably more trouble than it is worth.

I don't think I can speed up MindReader. Sorry. :-(.

**Comment by langner** [comment]
Conclusion: reading minds is slow :)

**Comment by marcharper** [comment]
Just an update on the original comment. I'm no longer finding that the noisy tournaments are faster, nor that the single-threaded runs are faster. 

```
-- Regenerating noisy tournament figures
Starting basic_strategies tournament with 100 round robins of 200 turns per pair.
Finished all basic_strategies tasks in 4.9s
Starting strategies tournament with 100 round robins of 200 turns per pair.
Finished all strategies tasks in 1475.8s
Starting all_strategies tournament with 100 round robins of 200 turns per pair.
Finished all all_strategies tasks in 1063.5s
Finished all tournaments in 2544.2s

-- Running Axelrod, regenerating cache, results, and figures
Starting basic_strategies tournament with 100 round robins of 200 turns per pair.
Finished all basic_strategies tasks in 4.2s
Starting strategies tournament with 100 round robins of 200 turns per pair.
Finished all strategies tasks in 977.0s
Starting all_strategies tournament with 100 round robins of 200 turns per pair.
Finished all all_strategies tasks in 816.2s
Finished all tournaments in 1797.4s
```

**Comment by drvinceknight** [comment]
Sorry for only getting to this now. Are you suggesting that we can close this issue?

**Comment by marcharper** [comment]
Yep!

**Comment by drvinceknight** [comment]
:+1:
