### ISSUE TITLE
Move all references of 'C' and 'D' to importable constants

### ISSUE THREAD

**Issue by CamDavidsonPilon** [Axelrod-Python/Axelrod#359]
The library is littered with `'C'` and `'D'`. I think it would be an improvement if these were constants

```
# axelrod/__init__.py

DEFECT = 'D'
COOPERATION = 'C'

# or maybe 
from enum import Enum

class Move(Enum):
  # this numbers don't really matter, they are just used for comparing equality. 
   DEFECT = 0
   COOPERATE = 1

```

Then in other code, you might have:
```
from axelrod import Move
...
# from rand.py

    def strategy(self, opponent):
        r = random.random()
        if r > self.p:
            return Move.DEFECT
        return Move.COOPERATE
```

Another example,  

```
from axelrod import Move
...
# from gobymajority.py

    def strategy(self, opponent):
        """This is affected by the history of the opponent.

        As long as the opponent cooperates at least as often as they defect then the player will cooperate.
        If at any point the opponent has more defections than cooperations in memory the player defects.
        """

        memory = self.classifier['memory_depth']
        history = opponent.history[-memory:]
        defections = sum([s == Move.DEFECT for s in history])
        cooperations = sum([s == Move.COOPERATE for s in history])
        if defections > cooperations:
            return Move.DEFECT
        if defections == cooperations:
            if self.soft:
                return Move.COOPERATE
            else:
                return Move.DEFECT
        return Move.COOPERATE
```

This reads a bit better, plus feels more maintainable - you won't accidently write `'c'` instead of `'C'` for example. Thoughts?

**Comment by marcharper** [comment]
I think something can be done here. Several files have the following near the top (e.g lots of the test files):
`C, D = 'C', 'D'`

We could definitely be more consistent across the library.

**Comment by bootandy** [comment]
I was considering suggesting this myself. 
Constants are less error prone (Have fun debugging the crash from a 'not C' that turned out to be a 'c' and not the letter 'D').

**Comment by marcharper** [comment]
I like `C, D = 'C', 'D'` over `DEFECT` and `COOPERATE` just for brevity. I guess we could start files with `C, D = COOPERATE, DEFECT` or `C, D = Move.COOPERATE, Move.DEFECT`. We don't tend to use `C` or `D` as variables. 

However it shakes out I do think this would be a nice clean-up for the library, and as @bootandy says, reduce the chance of some unintentional mistakes.

**Comment by drvinceknight** [comment]
> I like C, D = 'C', 'D' over DEFECT and COOPERATE just for brevity. I guess we could start files with C, D = COOPERATE, DEFECT or C, D = Move.COOPERATE, Move.DEFECT. We don't tend to use C or D as variables.

I agree with you here @marcharper and also agree that it's a nice cleanup.

**Comment by CamDavidsonPilon** [comment]
How do you feel about the namespacing that `Enum` provides? (basically namespacing is its main purpose). Consider:
```
from axelrod import C, D

```

vs, what I prefer
```
from axelrod import Moves

# two options in code, either 
C, D = Moves.C, Moves.D

If history[-1] == C:
    ...

# or not unpacking

If history[-1] == Moves.C:
    ... 
```

**Comment by marcharper** [comment]
I'm not sure that I have a preference, as long as I don't have to type `Moves.C` instead of `C` every time. So `C, D = <something reasonable>` works for me.

**Comment by bootandy** [comment]
No preference either way here. (Agree that Moves doesn't seem to be the right name).

**Comment by marcharper** [comment]
I don't know that there is a right term. The game theory literature uses moves, plays, actions, pure strategies, and I'm sure many other terms. The wikipedia article on [game theory](https://en.wikipedia.org/wiki/Game_theory) uses moves, plays, and actions interchangeably.

**Comment by drvinceknight** [comment]
> I'm not sure that I have a preference, as long as I don't have to type Moves.C instead of C every time. So C, D = <something reasonable> works for me.

I agree with this. 

> I don't know that there is a right term. The game theory literature uses moves, plays, actions, pure strategies, and I'm sure many other terms. The wikipedia article on game theory uses moves, plays, and actions interchangeably.

I have a slight preference for `action` but not based on much.

**Comment by marcharper** [comment]
Then we're in luck because @CamDavidsonPilon chose "actions".

**Comment by drvinceknight** [comment]
:+1: Yeah I saw that just after commenting here :) :dancers: :cake: :shipit:
