### ISSUE TITLE
Documentation name for GTFT incorrect in overview

### ISSUE THREAD

**Issue by ABarriscale** [Axelrod-Python/Axelrod#377]
In the documentation the strategy Generous Tit For Tat is incorrectly named (GTFT) in the library.
http://axelrod.readthedocs.org/en/latest/overview_of_strategies.html#stewart-and-plotkin-s-tournament-2012

**Comment by drvinceknight** [comment]
Thanks for opening this @ABarriscale, we'll take care of it together at our next meeting.
