### ISSUE TITLE
Tournaments to Reproduce

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#387]
* http://www.graham-kendall.com/papers/lhk2011.pdf

**Comment by marcharper** [comment]
So for this issue we really just need to add the remaining strategies. Most of them are fairly straight-forward.

**Comment by marcharper** [comment]
Strategies still needed:
* adaptive tft
* contrite tft
* gradual
* naive prober
* remorseful prober
* reverse pavlov
* soft grudger

**Comment by drvinceknight** [comment]
I'm happy to pick these up, been a while since I wrote some strategies :) I think some might already be in there...

**Comment by drvinceknight** [comment]
Hey @nikoleta-v3 I've been working on the remaining strategies listed by @marcharper and have `reverse pavlov` and `soft grudger` done but perhaps as a 'getting started with the library' exercise you could implement one of the others? We'll do it together over the next couple of days (perhaps tomorrow - Wednesday) but take a look at the paper linked to at the top and see what you think of the 5 others and pick one out.

**Comment by Nikoleta-v3** [comment]
@drvinceknight Yes it would be a great help for starting and motivate me as I am going through the code. Will make sure to go through the paper today and chose one.

**Comment by marcharper** [comment]
See also #379 for more strategies that we need. Just note that these range from fairly easy to quite hard to implement (typically because they are not sufficiently described).

**Comment by drvinceknight** [comment]
@Nikoleta-v3 and I have had a look and believe that adaptive tit for tat is equivalent to: [GoByMajority](http://axelrod.readthedocs.io/en/latest/_modules/axelrod/strategies/gobymajority.html#GoByMajority).

**Comment by drvinceknight** [comment]
Editing the list above: #626 implements Gradual and I have the other two (reverse pavlov
soft grudger) written on a branch.
