### ISSUE TITLE
How to cite the library

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#389]
We should add sometime to the docs regarding how to cite the library (even as just a place holder for now), such as:

<contributors>
Axelrod: a framework for the Iterated Prisoner's Dilemma, 2015-
https://github.com/Axelrod-Python/Axelrod/

**Comment by drvinceknight** [comment]
Similar to what we have at the bottom of http://axelrod-python.github.io/?

```
@misc{Axelrod-Pythonprojectteam2015,
author = {Axelrod-Python project team},
title = {{Axelrod-Python vx.y.z}},
url = {http://axelrod-python.github.io/},
year = {2015}
}
```

**Comment by marcharper** [comment]
Yes that's it :) Maybe in long form as well since not everyone uses latex.

**Comment by drvinceknight** [comment]
Yeah, perhaps a link to the bibtex :)

V

**Comment by drvinceknight** [comment]
#394 is a first stab.
