### ISSUE TITLE
Strategy Transforming broke caching

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#391]
The standard library pickle can't handle decorated classes. ~~The p~~ Possible fixes are:

* Use [cloudpickle](https://github.com/cloudpipe/cloudpickle) instead of pickle, which is as easy as `import cloudpickle as pickle`.
* Disable caching for transformed players.

Edit: the cloudpickle fix is in, alternate suggestions still wanted.

**Comment by langner** [comment]
Another option would be to not pickle the classes themselves. Additionally, JSON might be a more natural, and human-readable format for storing the cache.

**Comment by marcharper** [comment]
Yeah, there are many that could work. The cloudpickle approach is very simple and maybe be a good quickfix (I have a two-line commit to handle it). I'll open a PR for that in case we want to merge it while we discuss other solutions.

**Comment by meatballs** [comment]
> Another option would be to not pickle the classes themselves. Additionally, JSON might be a more natural, and human-readable format for storing the cache.

I agree. The names of the classes could be used as the key rather than the classes themselves and JSON might be a much nicer way to represent the content - especially when we move to caching the interactions rather than the payoff and cooperation

**Comment by drvinceknight** [comment]
Would JSON also be relevant if/when we build the web api?

**Comment by meatballs** [comment]
> Would JSON also be relevant if/when we build the web api?

Doesn't make any difference as this would all be run within the celery task anyway

**Comment by drvinceknight** [comment]
_Skuttles back to his cave to work on docs..._

**Comment by marcharper** [comment]
The key should be strategy name + init_args to properly handle parameterized strategies.

**Comment by drvinceknight** [comment]
I have merged #392 as it was a bug. 

When we decide what is the best way to fix it (ie this issue) we can go with that?

**Comment by drvinceknight** [comment]
Do we want to discuss this further at some point (ie leave this issue open until people have the time) or are we happy with @marcharper's fix?

**Comment by meatballs** [comment]
Let's go for the quick fix for now. #284 is going to to required some mucking about with the cache anyway

**Comment by drvinceknight** [comment]
> Let's go for the quick fix for now.

Quick fix is already in (was a bug). Mainly just seeing if I can close this issue to keep things tidy. No harm in it staying open.

**Comment by drvinceknight** [comment]
Have removed the bug label (no longer a bug).

**Comment by marcharper** [comment]
So are we happy with cloudpickle for now? If so we can close this one as well.

**Comment by drvinceknight** [comment]
Yup!
