### ISSUE TITLE
Add definitions of play contexts

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#403]
The documentation lacks names for the four possible rounds (C, C) (C, D), (D, C), (D, D) and the meanings of R, P, S, T in the game matrix.

**Comment by drvinceknight** [comment]
I think this should go in an 'Description of Iterated Prisoner's Dilemma' file in the reference section of the docs.

That could then be nicely followed by the suggestion on #404

**Comment by drvinceknight** [comment]
Have opened #428, not convinced it's as good as could be (I lazily copied the old background). Let me know what you think @marcharper :)
