### ISSUE TITLE
Reorganize overview of strategies

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#404]
I think we should de-emphasize the strategies from Axelrod's original tournaments unless they are particularly interesting or well-known now. Additionally, there are **many** strategies in the library that do not appear in the overview at all. I suggest we split the file into:
* One overview with all strategies, in alphabetical order
* Auxiliary files for various tournaments, if desired.

**Comment by drvinceknight** [comment]
Yeah, this is a good suggestion. This further modularises the docs.

**Comment by drvinceknight** [comment]
> One overview with all strategies, in alphabetical order

This could/should be automated from the Sphinx docstrings. We have a script that did that... I removed it during the re write but would be easy to put back in.
