### ISSUE TITLE
Repository size

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#406]
The repository is a lot larger than one might expect (over 100 mb). Likely this is because of the history of the various *.csv *.png *.svg and cache.txt files that were moved out or later removed from the repository.

It's probably a good idea to remove these files from the history and to garbage collect the repository. I'll get to this eventually but if anyone wants to try in the meantime, here are some good links:
* http://stevelorek.com/how-to-shrink-a-git-repository.html
* http://naleid.com/blog/2012/01/17/finding-and-purging-big-files-from-git-history

**Comment by drvinceknight** [comment]
:+1: If I get a second I'll have a go (if I do I'll let people know on the gitter channel).

**Comment by marcharper** [comment]
Looking into this a bit more, once someone does this, we're all going to have to rebase / reclone our repositories. These are the commands to run:
```
git filter-branch -f --tree-filter "git rm -rf --cached --ignore-unmatch *.svg *.png *.csv *.jpg" --prune-empty -- --all
git filter-branch -f --tree-filter "rm -rf *.svg *.png *.csv *.jpg" --prune-empty -- --all
git reflog expire --expire=0 --all
git repack -ad
git clean
git gc --aggressive
```
Unfortunately this will nuke a few of the binary files that we do want to keep for the docs, so those would have to be added back in later. So rather than `git pull`, we'll need to
```
git fetch origin
git rebase --onto origin/master master
```

**Comment by drvinceknight** [comment]
> Looking into this a bit more, once someone does this, we're all going to have to rebase / reclone our repositories. :warning: If you attempt this, do so in an auxiliary repository :warning:

And this would potentially make a mess for people who have cloned the repo and left it for a while right?

**Comment by marcharper** [comment]
Yep :( We may be better off just not messing with it.

**Comment by drvinceknight** [comment]
Hmmm... Might indeed be one of those not quite broken situations... Shame I didn't make the right call to keep these things separate when I stumbled my way at the start... If there is a way to make this better I'd not be against it but nicer to not mess with published history... (If we were to do something the sooner the better...)

**Comment by meatballs** [comment]
I think we should clean it up. Anyone who comes back and hits a problem is likely to come on here or gitter and ask what on earth happened.

**Comment by drvinceknight** [comment]
Just slightly nervous as everything everywhere always says: do not mess
with public history... Before we did it we should _try_ and get in touch
with everyone. Is this a big problem worth fixing?

In a way having the split in the history is kind of nice thing to have as
it shows the evolution of the project?

**Comment by marcharper** [comment]
Well we won't lose important history -- any commits that are altered will get new hashes but all the other info will remain. What will be annoying is the need to rebase any existing branches. Also we'll have to be sure not to merge an older branch that restores the removed object files. I'm not sure how to force github to rewrite its history (or if we need to).

What we probably need to do (to do this right): rename this repository, clean up a clone, and push the clone to github with the name of this repository. I think then we'll get the proper history on github and merge conflicts if anyone tries to restore the old history -- the .git objects won't match up.

**Comment by drvinceknight** [comment]
> Just slightly nervous as everything everywhere always says: do not mess
> with public history... Before we did it we should _try_ and get in touch
> with everyone. Is this a big problem worth fixing?

One thing against this point is that our repository is not exactly the most popular repository around (yet! :muscle: ) so it's not like we're likely to hear a lot of complaints... In fact it would almost be nice to hear someone complain about this...

**Comment by drvinceknight** [comment]
> What we probably need to do (to do this right): rename this repository, clean up a clone, and push the clone to github with the name of this repository. I think then we'll get the proper history on github and merge conflicts if anyone tries to restore the old history -- the .git objects won't match up.

Sounds like the way forward although would suggest that the rename of the repos is one of the last things we do?

**Comment by marcharper** [comment]
Sure, get a clean one ready locally somewhere and then do the name swap.

**Comment by drvinceknight** [comment]
> Good reason to clean it up sooner, no?

Yeah, before the millions of users turn up... (any day now :))

How would this work with a PR? Would the github PR mechanism be smart enough to handle a PR from an 'old version' to the new one? Just worrying that we'd get a PR which would silently rewrite the heavy history.

**Comment by marcharper** [comment]
I'm not sure actually, that's why I think we need to move the repository and add a new one once it's cleaned. We're probably going to mess it up at least once!

**Comment by drvinceknight** [comment]
We'd have to think about all the integrations also right? travis, gitter, coveralls etc...

**Comment by marcharper** [comment]
Well I hoping with the name restored they won't notice. But yes that may become an issue.

Also, I'm not entirely confident that this original list of commands I gave is sufficient. We'll see... but I'd block off time for this in line with re-installing an OS.

**Comment by marcharper** [comment]
I was able to manage this for my AxelrodExamples repository, which also had many images. The commands are updated above. If no one objects I'll give this a shot.

How do we feel about moving all the images out of this repository completely?

**Comment by drvinceknight** [comment]
> How do we feel about moving all the images out of this repository completely?

Do you mean for the docs? If so, then no I don't think that's a good idea. It's nice to have everything self contained re docs (just having the one image outside for the whole tournament is justifiable)...

> Well I hoping with the name restored they won't notice. But yes that may become an issue.

I'm not sure (I have no idea) but I know that when we moved the repository to a new name github did clever things that followed it around...

**Comment by marcharper** [comment]
Actually I did not have to move the repository at all, so hopefully there are no issues with travis et al.

**Comment by marcharper** [comment]
How about this -- I'll try with just the *.csv files first, since we don't want to retain any of those. If that goes well then I'll handle the images a bit more carefully. It will be far easier to just remove them all and add back in the few that we want to retain, but perhaps I can tease out a list of all the images somehow and handle them individually.

**Comment by drvinceknight** [comment]
> How about this -- I'll try with just the *.csv files first, since we don't want to retain any of those. If that goes well then I'll handle the images a bit more carefully. It will be far easier to just remove them all and add back in the few that we want to retain, but perhaps I can tease out a list of all the images somehow and handle them individually.

That sounds good to me.

I'm being my usual anxious self here. To be clear we're just talking about (for now) creating another repository which will potentially (fingers crossed, all goes well) replace this one?

**Comment by marcharper** [comment]
Yes... to be clear this will rewrite all the old commits that contain *.csv files that are no longer used (changing their SHA-1 hashes); then we have to force push the results as the new master here. I can do the removal and push to a new repository for evaluation, and if all goes well we can replace the master branch. If it does not go well then we just force push a copy of the original master back onto this one (we all have a fork that can handle this, and I'll make another clone just in case).

This process of removal will rewrite much of the .git directory that contains the compressed objects that git relies on to reducing the repository size. New branches will have to be branched from (or rebased onto) the new master to prevent reintroducing the (removed) cached git objects (when merging). Otherwise we'll just reintroduce what we removed.

It may mess with github's line counts (since the *.csv files will be removed) but the authorships of un-removed files and associated commits should not be altered.

**Comment by drvinceknight** [comment]
> I can do the removal and push to a new repository for evaluation, and if all goes well we can replace the master branch. If it does not go well then we just force push a copy of the original master back onto this one (we all have a fork that can handle this, and I'll make another clone just in case).

:+1: :)

**Comment by marcharper** [comment]
So I went back to this and reduced the repository from 130 mb to about 3 mb (!) with the following script:
```
rm -rf Axelrod
git clone git@github.com:Axelrod-Python/Axelrod.git
cd Axelrod

git filter-branch --index-filter 'git rm --cached --ignore-unmatch *.png *.svg *.csv' --tag-name-filter cat -- --all
git for-each-ref --format="%(refname)" refs/original/ | xargs -n 1 git update-ref -d
rm -rf .git/refs/original/
git reflog expire --expire=now --all
git gc
git prune
git repack -a -d -f --depth=250 --window=250
```

You can see the results [here](https://github.com/marcharper/Axelrod2). The history is preserved, as are the commit counts. The line counts drop for a few of us because of the removal of the SVG and CSV files.

We'll still need to add back in the images for the docs. How do we want to proceed? Perhaps the tournament repository is a better parking spot.

**Comment by drvinceknight** [comment]
> We'll still need to add back in the images for the docs. How do we want to proceed? Perhaps the tournament repository is a better parking spot.

There are not many images needed for the docs. My latest work on that which gave: http://axelrod-tournament.readthedocs.org/en/latest/ means that I think the only images in the `docs` directory are ones that are 'purely' for documentation which are:

- http://axelrod.readthedocs.org/en/latest/_images/demo_deterministic_strategies_boxplot.svg
- http://axelrod.readthedocs.org/en/latest/_images/demo_strategies_boxplot.svg
- http://axelrod.readthedocs.org/en/latest/_images/demo_strategies_winplot.svg
- http://axelrod.readthedocs.org/en/latest/_images/demo_strategies_payoff.svg
- http://axelrod.readthedocs.org/en/latest/_images/demo_strategies_noisy_boxplot.svg
- http://axelrod.readthedocs.org/en/latest/_images/demo_strategies_noisy_winplot.svg
- http://axelrod.readthedocs.org/en/latest/_images/demo_strategies_stackplot.svg

> I can do the removal and push to a new repository for evaluation, and if all goes well we can replace the master branch. If it does not go well then we just force push a copy of the original master back onto this one (we all have a fork that can handle this, and I'll make another clone just in case).

Does that still sound like a plan?

**Comment by drvinceknight** [comment]
Those all seem like they're here: https://github.com/Axelrod-Python/Axelrod/tree/master/docs/tutorials/getting_started/_static

**Comment by marcharper** [comment]
Yeah, I think the steps are
* someone makes a commit with the docs on my new repository
* we run `git push -f` from the new new master to the main repository
* everyone pulls down the new master and rebases / cherry-picks any branches they want to keep working on

Do we want the documentation images in this repository or somewhere else? In principle if we keep them here then the same issue could arise down the line. But maybe the images won't change that often and it's not worth worrying about.

**Comment by drvinceknight** [comment]
> someone makes a commit with the docs on my new repository

Simply adding the images right?

> Do we want the documentation images in this repository or somewhere else? In principle if we keep them here then the same issue could arise down the line. But maybe the images won't change that often and it's not worth worrying about.

I think we want the images here. This keeps everything modular, the docs for the library stay as the docs for the library, the docs for the tournament are separated out so shouldn't change too often. Basically at some point someone might put together a new tutorial with an image...

**Comment by marcharper** [comment]
Ok, I went ahead and added the images back and used the latest master on the new [repository](https://github.com/marcharper/Axelrod2). We'll probably want to test -- can we try to rebuilt the readthedocs page off the new repository?

Also let's keep at least a few copies of the main repo around locally in case we need to overwrite.

**Comment by drvinceknight** [comment]
> Ok, I went ahead and added the images back and used the latest master on the new repository. We'll probably want to test -- can we try to rebuilt the readthedocs page off the new repository?

Taking a look now.

> 
> Also let's keep at least a few copies of the main repo around locally in case we need to overwrite.

Yup! I am mildly nervous :)

**Comment by marcharper** [comment]
I've done this before with some other repositories, so it should be alright :)

**Comment by drvinceknight** [comment]
> Ok, I went ahead and added the images back and used the latest master on the new repository. We'll probably want to test -- can we try to rebuilt the readthedocs page off the new repository?
> Taking a look now.

I don't see how to do this straightforwardly... It looks like rtd pairs up with a given repo... One option would be to setup a new rtd project, point it at your repo and potentially delete it if everything is happy... Not sure what the alternative is.

**Comment by drvinceknight** [comment]
Closing this now. Reopen if need be.
