### ISSUE TITLE
Create DeterministicCache class

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/Axelrod#412]
Creating a class for the cache would give us some advantages:

1. Encapuslation - the cache has state (e.g. mutability or the number of turns for which it is valid) and it has methods (e.g. store, load, add). A class would allow us to encapsulate that behaviour instead of it existing several times around other classes.

1. Implementation - having a class with 'add' and 'retrieve' methods would allow us to change the underlying implementation (e.g. a database, a redis store) without affecting any of the classes which use it.

This should wait until #284 is complete

**Comment by marcharper** [comment]
:+1:

**Comment by drvinceknight** [comment]
:+1:

**Comment by drvinceknight** [comment]
Closed by #527.
