### ISSUE TITLE
Clone players at tournament level

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/Axelrod#413]
We should move the cloning of players (for self-interactions) to the tournament level so that it only occurs once.

This should wait until #284 is complete.

**Comment by marcharper** [comment]
Instead of once per repetition?

**Comment by meatballs** [comment]
Exactly, yes!

**Comment by marcharper** [comment]
Good idea -- that should be a significant speed up, yes?

**Comment by meatballs** [comment]
I hope so. It would certainly reduce the number of cloning operations and they seem to take a large amount of time each.

**Comment by drvinceknight** [comment]
Sounds good to me.

**Comment by meatballs** [comment]
Given how we've ended up tackling #284, I think this is now impossible.

As we're keeping the Match objects, which each include a pair of Players objects with the completed history, we can't re-use Player objects between repetitions.

**Comment by meatballs** [comment]
Actually, I may have to disagree with myself above. Further thinking required....

**Comment by drvinceknight** [comment]
Done by #483.
