### ISSUE TITLE
Latest version of matplotlib released with new colormaps

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#420]
http://matplotlib.org/devdocs/users/whats_new.html#new-colormaps

Are we going to change the defaults? This immediately implies that anyone using the library would need to update their matplotlib install.

Also, does this have an effect on violin plots when there is no variability? Can we use violin plots throught? I think you mentioned that at some point @marcharper ?

**Comment by marcharper** [comment]
The violin plots should work automatically. For the heatmaps we can do something like:
```
s = matplotlib.__version__.split('.')
if int(s[0]) >= 1 and int(s[1]) >= 5:
    DEFAULT_COLOR_MAP_NAME = "viridis"
else:
    DEFAULT_COLOR_MAP_NAME = 'jet' # Whatever we are using now
```

**Comment by drvinceknight** [comment]
That sounds good to me :)

**Comment by marcharper** [comment]
I'll test this and make a PR. I just used the same code for another library and it worked, so I'll install axelrod into the same virtualenv.

I'd also like to pass through parameters for the image format , dpi, etc. So maybe I can have one "plotting update" PR.
