### ISSUE TITLE
"Ready" github tag 

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#426]
Now that we have more refined tags for PR review, let's dispense with the auto-ready tag that appears. 

I'm not sure how this was setup, so I'm tagging @drvinceknight, since I think he knows...

**Comment by drvinceknight** [comment]
I forget if it was me or @meatballs who set this up. Just tagging him in case he still uses the waffle board and likes the labels. I'm happy for us to get rid of them (and happy to take care of it).

**Comment by drvinceknight** [comment]
I believe I've fixed this without killing the waffle board. Let's see...
