### ISSUE TITLE
Figure out good way to sync gh-pages and master...

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#43]

**Comment by drvinceknight** [comment]
@martinjc has written a nice gh-pages branch with cool visualisations, I'm currently not confident. `run_tournament.py` has been changed on both branches (master and gh-pages) I expect there's merge conflicts to deal with to sort this. This would be a nice easy pull request if anyone wants it...

(Would be nice to include a command line option to exclude the csv output if we wanted it)

**Comment by meatballs** [comment]
Now that we have an organisation, we could create a separate repo for a github pages site. No need to muck about with a gh-pages branch from this repo!!

**Comment by langner** [comment]
I thought the documentation was on the gh-pages branch.

**Comment by drvinceknight** [comment]
Yeah that's a good idea. Although with djaxelrod is there actually a need
for a gh-pages site?

**Comment by drvinceknight** [comment]
No the documentation is being rendered by read the docs.

The gh-pages branch was done a while back and had a bunch of d3 versions of
the graphs.

**Comment by langner** [comment]
Ah yes, I see that now.

**Comment by meatballs** [comment]
How about this for a plan:

 * Short term, we create Axelrod-Python.github.io, load it with the content from `gh-pages` here and bring everything up to date
 * Longer term, we look to incorporate the d3 stuff into whatever front end we put on DjAxelrod

**Comment by langner** [comment]
Sounds OK, but I will not have time to contribute to this at all.

**Comment by drvinceknight** [comment]
Sounds like a good plan. I'm happy to pick it up but that won't
realistically happen until after Djangocon (after which it might be a bit
irrelevant).

On another note for djaxelrod I was thinking of using mpld3 which is a neat
python library that automatically takes matplotlib figs and turns them in
to d3. We recently used this on a hackathon Django project.

**Comment by meatballs** [comment]
OK, let's leave it until after DjangoCon - I wonder how far we'll get with DjAxelrod that week?!!

**Comment by drvinceknight** [comment]
I'm hoping that with your expertise and my cheerleading we'll get very far
:)

**Comment by meatballs** [comment]
> I'm hoping that with your expertise.....

Oh dear. We are doomed!

**Comment by meatballs** [comment]
Do we think DjAxelrod has made sufficient progress for this to be closed?

(I do).

**Comment by drvinceknight** [comment]
I do also.
