### ISSUE TITLE
Update pypi page

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#431]
The formation could use some attention (image sizes and markdown style links). The next release will fix the links I presume.

**Comment by drvinceknight** [comment]
Have fixed the links with v0.0.19, going to see what I can do about the image widths...

**Comment by drvinceknight** [comment]
I believe this fixes it: #432

Won't actually be fixed until a new release is done but can do that as soon as #432 is done.

**Comment by drvinceknight** [comment]
#432 did not completely fix this, the width of the images is still not right...

**Comment by drvinceknight** [comment]
This has now been fixed by #431.
