### ISSUE TITLE
Instantiation of LogHandlers

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/Axelrod#438]
The setup_logging function in utils.py instantiates all the possible log handlers within the logHandlers dictionary. This leads to 'axelrod.log' files being created when they aren't required.

Instead, the dictionary should have the class names as its values and only the selected entry should be instantiated.

**Comment by drvinceknight** [comment]
:+1: I might take a look at this (the log handlers is a part of the library I know nothing about) but if someone wants to jump in before me: be my guest.

**Comment by drvinceknight** [comment]
Fixed by #480.
