### ISSUE TITLE
Django Application

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/Axelrod#44]
This could be turned into a Django application, hosted on Heroku or similar, with the tournament(s) results serialised to JSON via the Django Rest Framework and therefore available publicly for analysis by anyone.

There could be an admin backend for configuring and initialising tournaments and some work in AngularJS and D3 should enable all sorts of visualisiation.

Depends on: #45

Just have to find someone to fund my time to do this rather than the day job!!

**Comment by drvinceknight** [comment]
I would love this to have a Django app. I'm thinking of possibly offering it up as a sprint at dkangocon... Have read through #45, I need to read through it again,  carefully :)

**Comment by meatballs** [comment]
Count me in for that sprint!

 #45 was mainly due to me thinking through how the django model might work. It can represent simple attributes in the DB, but behaviour gets tricky unless it can be broken down into simple rules (and I don't think this can). Better, therefore, to separate the two.

**Comment by drvinceknight** [comment]
I'll respond to that one carefully when I get a chance. Not something I know anything about so I'll have some questions :+1: :)

**Comment by marcharper** [comment]
I can help out with Django a bit, if you all decide to go this route.

**Comment by drvinceknight** [comment]
That would be great. Djangocon is in Cardiff in June and Owen and I are
planning on sprinting on it then... My thoughts are that it would be a
separate repository but can't say that we've had any discussion about it...

**Comment by meatballs** [comment]
It lives!!

https://github.com/Axelrod-Python/DjAxelrod

**Comment by drvinceknight** [comment]
:+1:
