### ISSUE TITLE
Smarter classification of `makes_use_of`

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#442]
This is based on #433 and #348 where @marcharper suggested:

> Bonus points:
> 
> Try to detect usage automatically (with the inspect module) as part of another test that checks that every strategy's make_use_of classifier. This way if someone changes a strategy to use (or no longer use) one of the tournament attributes, it should trip the test
> Double bonus points:
> 
> Make the automated bonus test able to accept future new keys of the tournament_attributes dictionary

**Comment by gaffney2010** [comment]
I've started some work on this.
