### ISSUE TITLE
Proposal: New 'FuzzyChameleon' transformer

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#447]
With @geraintpalmer we have thought of a new transformer called `FuzzyChameleon` (or whatever: working title) which takes as an argument another strategy `<strategy>` and a probability `p`.

Then on every play the transformed strategy would with probability `p` play what `<strategy>` would play. So for example we could have a tournament where all strategies become `TitForTat` on any given round with probability `p`. 

Another example is that this allows us to compare randomness with noise. So letting all players play as `Random` with probability `p` as opposed to a tournament with noise `p` (noise flips decision). This is the use case that motivates this proposal for work with @ABarriscale.

**Comment by drvinceknight** [comment]
Perhaps `Mutation` would be a nicer name...

**Comment by drvinceknight** [comment]
Just throwing this discussion with @marcharper from the gitter channel here (for when I get to it):


> marcharper Dec 01 03:36
> so if you make it a metaplayer, I'd say pass in a list of players and optionally a list of weights to chose > > (randomly) which player to follow
> might be more flexible than a transformer
> but i do like the idea of a transformer as well

> drvinceknight Dec 01 07:22
> so if you make it a metaplayer, I'd say pass in a list of players and optionally a list of weights to chose 
> (randomly) which player to follow
> But that metaplayer would be the only player who actually plays in the tournament right? You wouldn't > get insights of the performance of each player? Or would you? Probably a neat thing to do also:  
> MutatingMetaPlayer but not quite the same thing?

> drvinceknight Dec 01 07:47
> Or... are we saying that instead of decorating players we could create an instance of a meta player for > each strategy that we would like to 'decorate'.
> That makes sense.
> I wonder if a nice way to do it would be a combination of these two things.
> Creating a MutatingMetaPlayer and then creating a decorator that when applied to a strategy creates a > MutatedMetaPlayer instance that jumps between the original player and whatever it should mutate to...
> Although perhaps that's over complicating things...

> drvinceknight Dec 01 07:53
> I'll play around with things...

**Comment by marcharper** [comment]
Once this is done, it would be neat to do linear combinations of a few strategies, maybe ZDGTFT2 and ZD-Extortv2, and find optimal combos. If we compute say the score for some reasonable number of combinations of three strategies, the results can be visualized as a heatmap on the simplex (and my [ternary plotting library](https://github.com/marcharper/python-ternary) would be very useful for that).

**Comment by drvinceknight** [comment]
Yeah that'd be great!
