### ISSUE TITLE
Investigate the use of type hints

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#457]
See discussion on #454.

**Comment by marcharper** [comment]
It's Python 3 only, there are third party libraries like mypy that have some degree of Python 2 support (with a preprocessor that strips the type annotations I believe).

**Comment by marcharper** [comment]
Closing, we can reopen in the future if we drop python 2 support.

**Comment by marcharper** [comment]
In Python 3.6 there will supposedly be a way to do this in comments that is compatible with Python 2.7 and 3.6. So we could do this if we drop support for 3.x for x < 6 once 3.6 is released.

Alternatively we could drop support for Python 2.7 and "do it the right way". That's my preference. With the popularity of anaconda I'm skeptical that there is a real need to continue supporting Python 2. We could also get rid of the warnings in #476.

**Comment by drvinceknight** [comment]
> In Python 3.6 there will supposedly be a way to do this in comments that is compatible with Python 2.7 and 3.6. So we could do this if we drop support for 3.x for x < 6 once 3.6 is released.

Perhaps we could wait for 3.7 so we still have the last two 3s?

What advantages do type hints give us? (I don't know what they are. If an explanation is too complicated I'll look it up :) Just being lazy.) I understand that it's about performance, would we need to go back and annotate a bunch of code?

> 
> Alternatively we could drop support for Python 2.7 and "do it the right way". That's my preference. With the popularity of anaconda I'm skeptical that there is a real need to continue supporting Python 2. We could also get rid of the warnings in #476.

I think it's still too early to drop py2...

Slightly related: https://python3statement.github.io/ Could be nice to include us on there?

**Comment by marcharper** [comment]
Type hints just indicate what the types of variables are for function arguments and return variables, and they can be explicit, like `int` or more vague, such as `sequence`. They actually don't do anything now other than providing a way to test the types, but they can (arguably) increase readability. It's possible that the interpreter could take advantage of the type hints eventually but right now I don't believe that cpython does anything other than parse the hints and make them available through the `typing` module.

**Comment by drvinceknight** [comment]
Cool, so we wouldn't have to go back and annotate but we could?

**Comment by marcharper** [comment]
Exactly.

**Comment by meatballs** [comment]
We could use the annotations instead of numpy style docstrings. There's a sphinx extension that will render the docs from them.

**Comment by meatballs** [comment]
Here's the extension: https://pypi.python.org/pypi/sphinx-autodoc-annotation/1.0

**Comment by marcharper** [comment]
Closing re: #808
