### ISSUE TITLE
FYI: Fix of a bug. Explaining things: does anything need to be looked at?

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#470]
As described at #465, Hypothesis found a particular tournament configuration that crashed. This involved `BackStabber` and `MindReader`. I believe the reason that the entire tournament (with cheaters) didn't crash in this way is because in that case, strategies like `MindControl` changed `BackStabber` to `Cooperator` before it (or any other tricky match) could cause a crash.

- #465 Describes the original bug (the title is misleading, but the comments clarify things: this had nothing to do with py2 v py3. Just Hypothesis finding a bug).
- In #467 I wrote tests (that included another tournament setups: `MindReader` and `ThueMorse` which was also found by hypothesis) that specify these bugs.
- In #469 @marcharper fixed the strategy transformer (used by `BackStabber`), this is a straightforward fix.
- In #468 @marcharper changed how `MindReader` works, it no longer copies but clones strategies. This has the effect of increasing run time but fixes the bugs.

**Comment by marcharper** [comment]
Also see #354, perhaps we can close that one as well.

**Comment by drvinceknight** [comment]
Cool, that's closed. I'll wait a week or so in case anyone else reads this but will close it otherwise.
