### ISSUE TITLE
Git Cleanup -- New PRs

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#472]
Hi all,

We've cleaned up the repository to remove old files, which took the size from 130MB down to about 4MB (see #406). If you are using an old version of the master branch you may have some merge conflicts. In any case, for PR's going forward, we need you to branch or rebase off the new master.

A good way to handle this in general is to have a remote tracking branch for the main repository:

```
git branch --track upstream origin/master
```

You can keep this branch up-to-date simply by
```
git checkout upstream
git pull
```

Note that git will sometimes tell you that the branch is up-to-date after the checkout when that is not actually the case, so the `git pull` is needed.

If you want to over-write your current master branch with the github branch instead, just do (this will overwrite any commits not tagged/branched elsewhere):
```
git pull origin/master
```
You may have to handle merge conflicts; if that doesn't go well, you can delete and recreate your master branch. To do so, set up the tracking branch above, and do the following:

```
git checkout upstream
git branch -D master # deletes master so make sure that you have moved your commits elsewhere
git branch master # recreate master from the upstream branch
```

When you want to open a PR for your `awesome_feature` branch, here's the best way to do that:
```
git checkout awesome_feature
git rebase upstream # or git rebase master if your master is up-to-date with the main repository
# Fix any conflicts
git push your_github_repository awesome_feature
```

If for some reason the rebase doesn't work, you can `git cherry-pick <commit_hash>` the commits over onto the master. For any other issues, just ping us in the gitter chat and we'll help you out!

**Comment by marcharper** [comment]
I'm not sure what you named your branches. Usually when you clone a repository the remote repository is called origin. However you probably started this repository, so it could be named something else. Substitute origin with whatever you've named the repository on github.

Maybe git pull -f isn't a thing (git push -f certainly is). I usually set up a remote tracking branch for the remote master with
```
git branch --track upstream origin/master
```
and then I can always 
```
git checkout upstream
git pull
```
If it gets out of sync (because I commit accidentally), I just move the commits and hard reset the branch, or just delete and recreate:
```
git branch -D upstream # have to be on some other branch I think
git branch --track upstream origin/master
```

When I want to open a PR, I usually just do this:
```
git checkout upstream
git pull
git checkout awesome_branch
git rebase upstream
```

This ensures that I'm up to date with the remote master, checks for any merge conflicts, and usually only grabs the commits that I need.

**Comment by drvinceknight** [comment]
This is also what I do (the naming was not the issue it's the fact that `git pull origin/master` is not the correct syntax).  

As far as I can tell this issue doesn't give required insurrections to deal with the history rewrite (because a force pull is not a thing). Can we either clarify it (if I'm misunderstanding) or close it and open a different issue that explains how to deal with the history rewrite? Even if it just says that there was a history rewrite and people should re clone or get in touch (although I'm not sure we'd be able to offer any different advice then to re clone?).

**Comment by drvinceknight** [comment]
Apologies, I don't setup the remote tracking in the same way you did (I skipped over reading that carefully: my bad), so I see why `origin/master` works. 

Hadn't seen that you'd edited the original issue (gitter notifications aren't working for me). Perhaps this does explain how to deal with the history... This certainly has puzzled me... :+1:

**Comment by drvinceknight** [comment]
> Perhaps this does explain how to deal with the history...

FWIW Have just done this and it all works. Apologies for my confusion :) :+1:

**Comment by drvinceknight** [comment]
Is this worth closing? I was the one who wanted it open. Any thoughts?

**Comment by marcharper** [comment]
I think we can close it.
