### ISSUE TITLE
Opt in: Authorship on paper about library

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#487]
Dear contributor,

@marcharper @meatballs @langner and I have written a manuscript presenting this library as a research tool. This is now nearing the stages of submission and we have decided that we would like all [contributors](https://github.com/Axelrod-Python/Axelrod/graphs/contributors) to the library to be authors on the paper. **To do this however, we are using an OPT IN system so please reply to this comment to say if you would like to be an author on the paper.** A simple yes would be sufficient. We're aiming to submit over the next month or so.

If you would like to see the paper it is available here: https://github.com/Axelrod-Python/An-open-reproducible-framework-for-the-study-of-the-iterated-prisoners-dilemma

We are still deciding on the journal *but*:

1. It will be open access;
2. The paper will also be on the arXiv (https://arxiv.org/)

If you have any questions please do let us know (feel free to jump in the gitter channel, there's usually one of us hanging around :)).

To:

@uglyfruitcake
@JasYoung314 
@doismellburning
@mojones
@CamDavidsonPilon 
@geraintpalmer
@timothyf1
@bootandy
@tricoder42 
@pmslavin
@jomuel
@Karlos78
@lvisintini
@bricef
@ABarriscale
@risicle
@alcarney
@theref
@martinjc
@hollymarissa

**Comment by doismellburning** [comment]
Yes please!

**Comment by pmslavin** [comment]
Hello Vince,

I am happy to be included.  If email and affiliation are being included,
can these please be 'slavinp@cs.man.ac.uk' and 'The University of Manchester'
respectively.


Thanks and regards,

Paul

On Fri, Mar 11, 2016 at 11:29:13AM +0000, Paul Slavin wrote:
> ---------- Forwarded message ----------
> From: Vince Knight <notifications@github.com>
> Date: 11 March 2016 at 08:57
> Subject: [Axelrod] Opt in: Authorship on paper about library (#487)
> To: Axelrod-Python/Axelrod <Axelrod@noreply.github.com>
> Cc: Paul Slavin <pmslavin@gmail.com>
> 
> 
> Dear contributor,
> 
> @marcharper <https://github.com/marcharper> @meatballs
> <https://github.com/meatballs> @langner <https://github.com/langner> and I
> have written a manuscript presenting this library as a research tool. This
> is now nearing the stages of submission and we have decided that we would
> like all contributors
> <https://github.com/Axelrod-Python/Axelrod/graphs/contributors> to the
> library to be authors on the paper. *To do this however, we are using an
> OPT IN system so please reply to this comment to say if you would like to
> be an author on the paper.* A simple yes would be sufficient. We're aiming
> to submit over the next month or so.
> 
> If you would like to see the paper it is available here:
> https://github.com/Axelrod-Python/An-open-reproducible-framework-for-the-study-of-the-iterated-prisoners-dilemma
> 
> We are still deciding on the journal *but*:
> 
>    1. It will be open access;
>    2. The paper will also be on the arXiv (https://arxiv.org/)
> 
> If you have any questions please do let us know (feel free to jump in the
> gitter channel, there's usually one of us hanging around :)).
> 
> To:
> 
> @uglyfruitcake <https://github.com/uglyfruitcake>
> @JasYoung314 <https://github.com/JasYoung314>
> @doismellburning <https://github.com/doismellburning>
> @mojones <https://github.com/mojones>
> @CamDavidsonPilon <https://github.com/CamDavidsonPilon>
> @geraintpalmer <https://github.com/geraintpalmer>
> @timothyf1 <https://github.com/timothyf1>
> @bootandy <https://github.com/bootandy>
> @tricoder42 <https://github.com/tricoder42>
> @pmslavin <https://github.com/pmslavin>
> @jomuel <https://github.com/jomuel>
> @Karlos78 <https://github.com/Karlos78>
> @lvisintini <https://github.com/lvisintini>
> @bricef <https://github.com/bricef>
> @ABarriscale <https://github.com/ABarriscale>
> @risicle <https://github.com/risicle>
> @alcarney <https://github.com/alcarney>
> @theref <https://github.com/theref>
> @martinjc <https://github.com/martinjc>
> @hollymarissa <https://github.com/hollymarissa>
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Axelrod-Python/Axelrod/issues/487>.
========================================
Dr Paul Slavin

The University of Manchester
Advanced Processor Technologies
Room 2.66, Kilburn Building

+44 (0)161 306 3316
slavinp@cs.man.ac.uk
http://www.cs.man.ac.uk/~slavinp 
========================================

**Comment by geraintpalmer** [comment]
Yes :)

**Comment by lvisintini** [comment]
Yes
Thank You!

**Comment by CamDavidsonPilon** [comment]
Though I feel my contributions were minimal compared to others, I'd love to be more formally part of this project - so yes, thank you!

**Comment by jomuel** [comment]
I'd like to be included too, thank you. :)

**Comment by drvinceknight** [comment]
CC: @GDKO

**Comment by GDKO** [comment]
It would be an honour. Thanks :)

**Comment by Karlos78** [comment]
Yes, thanks!

**Comment by martinjc** [comment]
It feels a bit odd to get a paper authorship just for writing a bit of code
- especially when my contributions don't really make it into the real
tournament as they cheated! On the other hand, I do love those papers with
loads of authors, so I'm in.

Cheers,
Martin

**Comment by uglyfruitcake** [comment]
Yes please! Thank you very much! :)

**Comment by tricoder42** [comment]
Sure, thank you very much :)

**Comment by hollymarissa** [comment]
Hilarious. Sure.

**Comment by theref** [comment]
Yes please! :)

**Comment by mojones** [comment]
Yes please, let me know if there's anything I can contribute other than my name :-)

**Comment by timothyf1** [comment]
Yes please :)

**Comment by alcarney** [comment]
Yes please  :)

**Comment by drvinceknight** [comment]
Hi all,

Thanks for responding, I have added in the author names and where I know it, the affiliation.

You can see how this looks here: https://github.com/Axelrod-Python/An-open-reproducible-framework-for-the-study-of-the-iterated-prisoners-dilemma/blob/master/tex/paper.pdf

**Where I was not sure of the affiliation I have put "Not affiliated". Please let me know or edit [the tex file](https://github.com/Axelrod-Python/An-open-reproducible-framework-for-the-study-of-the-iterated-prisoners-dilemma/blob/master/tex/paper.tex#L30) directly via PR if you have a preference.**

One change that needs to be added is by @Karlos78: I'm not sure what your last name is?

**Comment by drvinceknight** [comment]
> One change that needs to be added is by @Karlos78: I'm not sure what your last name is?

Looking through commit history it looks like it might be: "Molden", is that right @Karlos78?

**Comment by drvinceknight** [comment]
If you have responded on this issue and noticed that your name was not on the author list of the paper that's an oversight on my part. Simple mistake, just let me know.

**Comment by drvinceknight** [comment]
> You can see how this looks here: https://github.com/Axelrod-Python/An-open-reproducible-framework-for-the-study-of-the-iterated-prisoners-dilemma/blob/master/tex/paper.pdf

The decision for the journal has been made, and the corresponding version of the paper is now on the `jors` branch of that repo:

https://github.com/Axelrod-Python/An-open-reproducible-framework-for-the-study-of-the-iterated-prisoners-dilemma/blob/jors/tex/paper.pdf

The journal is: http://openresearchsoftware.metajnl.com/

**Comment by drvinceknight** [comment]
Closing this. Planning on submitting today.

**Comment by drvinceknight** [comment]
The arxiv version of the paper is here: http://arxiv.org/abs/1604.00896

I will be emailing you all (with my best knowledge of your email address, either because I know it or from the git history) with a password to 'claim it' as an author on the arxiv.
