### ISSUE TITLE
Questions regarding tournament

### ISSUE THREAD

**Issue by Karlos78** [Axelrod-Python/Axelrod#49]
Not sure if this is the right place for this, if not, please say!

I've been reading a bit around the history of this, and found a document which claims that the original tournament had 14 entries (15 including random) and the follow up had 62 entries (63 including random).  These 62/63 strategies then went into the ecological tournament.

So whilst the number of strategies is not yet close to the number in the second iteration of the original tournament, we have nearly double the number used in the first iteration.

My questions:

* Is the intention to ultimately run the tournament and declare a winner?
* If so, will there be a prize? :trophy: 
* Any thoughts on why Tit for Tat isn't winning yet? Is it really just that more strategies are required?
* I've not yet found anything that describes what hardware/software was used to run the original tournament. Anyone know?

**Comment by langner** [comment]
This essay from Hofstader also describes some the tournaments with interesting comments: http://www2.econ.iastate.edu/tesfatsi/AxelrodComputerTournaments.ExcerptsFromHofstadterSciAmArticle.1983.pdf

**Comment by drvinceknight** [comment]
> Not sure if this is the right place for this, if not, please say!

This is a great place for this: thank you so much for starting the conversation.

> Is the intention to ultimately run the tournament and declare a winner?

I hadn't really planned to do anything more than put it up and see what happened. This has already gone way past my expectations: I'm so glad so many people have contributed :)

> If so, will there be a prize? :trophy:

Well: @geraintpalmer (forgetful grudger) just got his smile wiped off his face by @theref (retaliate): I know that's not an actual prize but it's made me happy (@theref is an undergrad here who has worked with me and @geraintpalmer is doing his PhD here). 

I'd be up for doing an actual tournament but it's tricky as everyone can see how everyone is doing. Perhaps I could add a thing to the `README.md` with whoever it is that is in the lead?

> Any thoughts on why Tit for Tat isn't winning yet? Is it really just that more strategies are required?

Absolutely no idea. It will have something to do with the makeup of strategies. All the strategies that are doing well follow the guidelines held by Axelrod though: they're nice etc... (Although Grudger is doing better than I'd have expected).

If and when I find time I might try and figure out the results a bit better (who knows there might even be an academic publication in this somewhere with all contributors as authors :D).

@langner has suggested in issue #28 running an evolutionary variant of this. @geraintpalmer and I were talking about that an hour or so ago and we definitely will work on that at some point.

> I've not yet found anything that describes what hardware/software was used to run the original tournament. Anyone know?

I'd love to know :)
