### ISSUE TITLE
Setting Match/Tournament length

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/Axelrod#493]
At the moment, the number of rounds per match is set by the tournament and passed to the matches within it.

This should probably be done within the Match class so that they can be created completely independently - but the Tournament needs to retain some level of control over the definition of matches within itself.

Proposal:

* Match takes an ```end_match``` function as a parameter in its constructor (rather than ```turns``` as at present).

* ```end_match``` functions takes a single parameter - the number of turns played so far - and return a boolean to indicate whether the match should stop.

* The default ```end_match``` function returns true when the number of turns played reaches 200

* The tournament can pass whatever ```end_match``` function it likes to all matches within itself

I also think this would simplify the work required for #37

**Comment by marcharper** [comment]
Also we have the function `Player.set_tournament_attributes(self, length=-1, game=None, noise=0)` that `Match` can take advantage of, maybe in conjunction with a boolean that indicates whether players are aware of the match parameters.

**Comment by drvinceknight** [comment]
I wonder if this makes the match class more complicated than it needs to be? 

The fact that's its easy to make a match between two players of a given number of turns (or as it is presently: a given probability) is quite nice. What problem is this solving? At present _it is_ easy to create a match independently isn't it?

**Comment by drvinceknight** [comment]
(I might just be misunderstanding)

**Comment by marcharper** [comment]
Some players change behavior if they are aware of the match length. Right now we handle that by setting tournament attributes; it would nice to be able to do the same with matches to be able to properly access the different behaviors.

Moreover I'd say it's more a concern of the Match class than of Tournament -- it's easy to image a tournament of three rounds of 50, 100, and 200 turns respectively. It just so happens that a traditional tournament is a single round of matches of equal length.

**Comment by drvinceknight** [comment]
Right. I see a bit better. 

So for matches that won't technically have a length *as far as the players are concerned* (ones that end probabilistically which is what I've been thinking about recently) we'll have to have a separate way of dealing with that? (`match.length=False but `match.prob=.8` kind of thing?).  

I do like the user interface we currently have as described here:  http://axelrod.readthedocs.org/en/latest/tutorials/further_topics/creating_matches.html

**Comment by drvinceknight** [comment]
As far as a tournament of 200, 100 and 50 length rounds would that not just be taken care of by the new functionality that @meatballs put together where a tournament type would be defined in such a way for that?

**Comment by marcharper** [comment]
Sure, I think @meatballs new code would be used for that. I'm just advocating for a boolean like `players_know_match_length` that indicates whether `Player.set_tournament_attributes(self, length=-1, game=None, noise=0)` is invoked by the `Match` class or not, with the default being no. In the case of a probabilistic tournament obviously players couldn't be told the length, but could still be told the game matrix.

**Comment by marcharper** [comment]
Plus if we want to use the `Match` class internally for say testing it needs to be able to set the length attributes -- some tests require this.

**Comment by drvinceknight** [comment]
That sounds like a simpler change than I was imagining.

I do think it would be good to have an overall switch that chooses or not to let the players knows the game length. I do like that. 

Perhaps once I see the implementation it'll make more sense :) 

:+1:

**Comment by meatballs** [comment]
My initial thoughts above suggested passing in a function to Match. However, in a similar fashion to the TournamentType, I'm starting to wonder whether it should be a class with an attribute to record whether it has a fixed length.

**Comment by meatballs** [comment]
(Reading Fluent Python, I've now discovered that functions can have attributes, which would probably do this task, but I think consistency within the library is important here)

**Comment by drvinceknight** [comment]
> My initial thoughts above suggested passing in a function to Match. However, in a similar fashion to the TournamentType, I'm starting to wonder whether it should be a class with an attribute to record whether it has a fixed length.

I'm a bit confused still. I feel that both those suggestions add a level of complication that's not needed?

I agree that there should not be any such thing as a tournament length really and it's just a question of each `Match` having a length (as @marcharper said earlier, for example to have 50, 100, 200...). I see that this is worth fixing.

I am on board with this:

> I'm just advocating for a boolean like players_know_match_length that indicates whether Player.set_tournament_attributes(self, length=-1, game=None, noise=0) is invoked by the Match class or not, with the default being no.

but as far as I see that actually requires quite a simple change:

- The Match class sets the attributes
- A boolean is passed to the Match class init

I don't see the need for any other classes etc? Anything complicated can just be taken care of by the tournament_type classes which leaves things in one place and doesn't add to the complexity. I'm not sure what problem exactly that would solve.

**Comment by meatballs** [comment]
That's all fine for fixed length tournaments. I suppose I'm trying to do things here:

1. Pass the responsibility from the Tournament to the Match - it seems everyone is on board with that

2. Create the ability to have match length determined by a function  - the simplest of which will be to return a fixed number of rounds

**Comment by drvinceknight** [comment]
> Pass the responsibility from the Tournament to the Match - it seems everyone is on board with that
> 

Yup: :+1: 

> Create the ability to have match length determined by a function - the simplest of which will be to return a fixed number of rounds

Would this not be nicer coming out of the `tournament_type`? It would always be possible for Matches that have 'more sophisticated' stopping conditions to create their own Match classes that inherit from the base one?

I'm quite keen to keep the UI described here: http://axelrod.readthedocs.org/en/latest/tutorials/further_topics/creating_matches.html

*If* someone wanted to build a quick tournament with a basic knowledge of Python they can easily create matches and play them (without necessarily building it in to the library). Having used the `Match` class in talks I'm not yet overly excited about using them if I had to also define a stopping function...

My proposal would be to change:

```
 __init__(self, players, turns, deterministic_cache=None,
                 cache_mutable=True, noise=0, prob_end=None)
```

to include:

```
 __init__(self, players, turns, deterministic_cache=None,
               cache_mutable=True, noise=0, prob_end=None,
               players_know_match_length=False,
               players_know_prob_end=False)
```

and make the basic changes required around that.

**Comment by meatballs** [comment]
> Would this not be nicer coming out of the tournament_type?

I don't think so. I think matches should be completely independent and fully capable without being part of a tournament.

**Comment by meatballs** [comment]
> I'm not yet overly excited about using them if I had to also define a stopping function...

You wouldn't. I'm suggesting that the simple 'fixed length' function would be the default

**Comment by drvinceknight** [comment]
> I don't think so. I think matches should be completely independent and fully capable without being part of a tournament.

I agree with that (that Matches should be independent) but the tournament_type uses them and creates the ones it wants. A tournament type defines what types of matches are needed. 

I think adding another layer/class is a step away from the very simple: tournament_type -> creates matches which make up a tournament.

> You wouldn't. I'm suggesting that the simple 'fixed length' function would be the default

But that's still a function isn't it? When really I just want a number (or a probability). In anything more sophisticated I would suggest it's no longer really a 'match' and it would be worth just inheriting and creating a new class (that the corresponding tournament_type class would just create)...

**Comment by meatballs** [comment]
> A tournament type defines what types of matches are needed.

Agreed - so it would pass the match type (or function) to the matches it creates

**Comment by meatballs** [comment]
e.g. Rather than having ```turns=200``` in its init, match might instead have ```type=fixed_length(turns=200)```

**Comment by drvinceknight** [comment]
> e.g. Rather than having turns=200 in its init, match might instead have type=fixed_length(turns=200)

OK that's not looking as 'displeasing' (not meaning that to sound as arrogant/stupid as it does) as I thought.

I'm not sure I'm completely there yet, I was after my conversation with @marcharper which got me to this:

```
 __init__(self, players, turns, deterministic_cache=None,
               cache_mutable=True, noise=0, prob_end=None,
               players_know_match_length=False,
               players_know_prob_end=False)
```

Would `players_know_*` be passed by the `type` function?

Also (thinking aloud) for `type=probabilistic_end(probability=.5)` we'd have that `probabilistic_end` would return a fixed number (flipping a continue/end coin at each round is wasteful), basically emulating:

```
        if self._prob_end is not None:
            # If using a probabilistic end: sample the length of the game.
            # This is using inverse random sample on a pdf given by:
            # f(n) = p_end * (1 - p_end) ^ (n - 1)
            # Which gives cdf:
            # F(n) = 1 - (1 - p) ^ n
            # Which gives for given x = F(n) (ie the random sample) gives n:
            # n = ceil((ln(1-x)/ln(1-p)))
            try:
                x = random.random()
                end_turn = ceil(log(1 - x) / log(1 - self._prob_end))
            except ZeroDivisionError:
                end_turn = float("inf")
            except ValueError:
                end_turn = 1
        else:
            end_turn = float("inf")
```

we would in essence be moving that out of the Match class (I'm thinking aloud here)...

**Comment by drvinceknight** [comment]
> __init__(self, players, turns, deterministic_cache=None,
>                cache_mutable=True, noise=0, prob_end=None,
>                players_know_match_length=False,
>                players_know_prob_end=False)

I guess we could put all those arguments in to the type class?

(I'm beginning to see it.)

**Comment by drvinceknight** [comment]
Although if we're putting all those arguments in the type class does it not make sense to just have a bunch of inherited classes for Matches?

**Comment by drvinceknight** [comment]
So for example we could rip out the probabilistic ending I put in to Matches and just have:

```
class ProbabilisticEndingMatch(Match):
    ....
```

and make sure it all inherits what we have discussed so far including:

> Pass the responsibility from the Tournament to the Match - it seems everyone is on board with that

The function match type class/function we're talking about could then just be methods if needed for a specific type of Match (no need for basic Matches as they just return a number of turns).

**Comment by drvinceknight** [comment]
> So for example we could rip out the probabilistic ending I put in to Matches and just have:

Although if we include:

```
players_know_match_length=False,
players_know_prob_end=False
```

for the case of the Probabilistic ending match there would be no need for a separate Match class, the tournament type could just create matches of different length and make sure the players don't know about it.

**Comment by meatballs** [comment]
> Although if we're putting all those arguments in the type class does it not make sense to just have a bunch of inherited classes for Matches?

Yes - I was just trying to keep some consistency with the Tournament and TournamentType. Perhaps they too need refactoring to Tournament and RoundRobinTournament.....

**Comment by drvinceknight** [comment]
> Perhaps they too need refactoring to Tournament and RoundRobinTournament.....

Perhaps. I do like that the Tournament is made up of matches that are created by a tournament_type but you understand the guts of all this way more than I do :) 

I think in the instance of the Matches we do really _just_ need to be able to have: `players_know_match_length` (there would be no need for `prob_end` at all).

This would allow us to have Matches as completely independent entities (which I think we ultimately all agree is the way to go) that are all that are needed in the case of basic round robin and probabilistic ending tournaments however inheritance could be used if necessary (as opposed to creating another layer of abstraction with a match_type class).

In terms of reducing layers, I suppose that having a `RoundRobinTournament` class would also achieve that...

**Comment by drvinceknight** [comment]
Off to walk the :dog: before the :rugby_football: :)

**Comment by drvinceknight** [comment]
(I think we'd never need to create a `RoundRobinTournament`, that could just be the base `Tournament` - breaks too much previously run code by various users -  but other tournament types like probabilistic ending could inherit from it.)

**Comment by marcharper** [comment]
It sounds like we have a few proposals:
* pass a function `end_match` the encodes the match ending logic
* inherit from a generic `Match` that has a fixed length for new match types, like the probabilistic ending variant. In this case we could simply have a member function for `end_match` that is overridden in child classes, and the arguments to `__init__` would change appropriately (rather than all being added to the generic `Match` class and then being passed to `end_match`).

Both seem fine to me. The second option is more consistent with the style of the library otherwise, but I'm also a fan of functional approaches.

And then perpendicularly we modify the match class for:
* whether players know the match length
* whether players know the game matrix
* etc.

Finally we have tournament variants -- FixedLengthTournament, MultiRoundTournament, etc. I like the idea of being able to inherit from the tournament class to make new tournament types, but it also might be enough to have a generic tournament class that takes a dictionary of configuration data:
```
tournament_config = {
    rounds = "3",
    turns = [50, 100, 200],
    drop_bottom: 0.50 # drop the lowest half of players each time
}
```
We'd need to fit probabilistic ending options in there as well which might be easier with a derived class. I'm leaning that way since I've also wanted to add the Moran process as a tournament option, and the `Match` refactor has made that much easier (but I hadn't thought that it could be a tournament type before now, rather I was planning an independent structure).

**Comment by drvinceknight** [comment]
> inherit from a generic Match that has a fixed length for new match types, like the probabilistic ending variant. In this case we could simply have a member function for end_match that is overridden in child classes, and the arguments to __init__ would change appropriately (rather than all being added to the generic Match class and then being passed to end_match).

I prefer this approach as it means not adding another layer. 

Sorry for continuously bringing this up but I'm weary of making things more complicated than required: do we need a `end_match` function or could inherited `Matches` not simply overwrite the `play` method? I'm still not sure I see why `end_match` is needed. 

Note that the base `play` method is going to be cleaned up as there won't be a need for the probabilistic ending anymore assuming that below goes in:
 
> whether players know the match length
> whether players know the game matrix

> We'd need to fit probabilistic ending options in there as well which might be easier with a derived class. I'm leaning that way since I've also wanted to add the Moran process as a tournament option, and the Match refactor has made that much easier (but I hadn't thought that it could be a tournament type before now, rather I was planning an independent structure).

I prefer the idea of separate classes than options, and in particular once the ability for the Match to decide what a player knows is in then it will become very simple to make the probabilistic ending.

**Comment by meatballs** [comment]
> I'm weary of making things more complicated than required

Oh, dear, that doesn't sound good. My apologies if any of it is my doing - just point me in the direction of where it's not right and I'll see what I can do about it.

**Comment by drvinceknight** [comment]
Sorry I think my choice of words was incorrect. By weary I think I mean 'cautious', I just want to avoid it. I'm not saying we have that in the library (I don't think we do, in fact the latest work you did for the tournament types I love because of the simplicity of it all). 

I'm just querying if we're going to need a `match_end` attribute where it might be simpler to just invite an overwrite of the `play` method. 

For example I think you mentioned that the `match_end` would take the current round as argument but I can imagine a logic that depended on the current scores ('first to 50 type of thing'). 

Apologies again, certainly not suggesting the current setup is more complicated than required. Poor choice of words.

**Comment by meatballs** [comment]
That's a relief!!

I'm not minded to start coding anything on this just yet. I think it needs a little more thought first. One for the train to Glasgow tomorrow morning,.....

**Comment by drvinceknight** [comment]
Yeah it feels like we're almost there now. I am excited about this it is yet again going to make the library better (and soon #37 will write itself!). :)

**Comment by drvinceknight** [comment]
Suggestion: doing this in two steps that basically corresponding to the 1) and 2) you mentioned above Owen. 

1) Move the tournament length to the Matches (and include an option as to whether or not the Match tells this to the players): in essence getting rid of tournament length and replacing it by match length. This seems to correspond to the title of this issue. 
2) If the Match logic needs changing we can do that as a separate piece of work? 

I suggest doing them as two separate pieces of work because once 1) is done I can very easily implement probabilistic ending. Perhaps we could wait till that (prob ending) is done to see what problem remains that 2) would solve?

**Comment by meatballs** [comment]
OK. I'll get 1 done first and then we'll see where we stand

**Comment by drvinceknight** [comment]
> OK. I'll get 1 done first and then we'll see where we stand

Awesome.

Quick thought, the optional argument telling the match what it can tell the players should not just be the match length but anything that could be in the `player.makes_use_of` dictionary (so for example the game etc...)... Perhaps best to pass in dictionary mapping variables to booleans or something (so that it's generic and future proof for further properties that we may or may not want players to know...).

Just a thought.
