### ISSUE TITLE
GoByMajority incorrect player name

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#500]
:dog: ruh roh:

```
>>> import axelrod as axl
>>> p = axl.GoByMajority()
>>> p.name
'Player'
>>> 
```

**Comment by marcharper** [comment]
Maybe we can make name into a property? or at least set the variable during `__init__`.

**Comment by drvinceknight** [comment]
#501 takes care of this. I went for moving the name to the `init`. Also included more tests.
