### ISSUE TITLE
win-stay lose-shift should maybe not be classified as stochastic

### ISSUE THREAD

**Issue by mojones** [Axelrod-Python/Axelrod#506]
win-stay lose-shift inherits from memoryone, which makes it stochastic, but as the probabilities are all either 0 or 1 it doesn't actually behave stochastically. Maybe the stochastic field should be overridden for this subclass.

**Comment by marcharper** [comment]
This is supposed to be caught -- I thought we had some code that would check if the probabilities were all zero or one.

**Comment by drvinceknight** [comment]
It is being caught, all working fine for me:

```
In [14]: import axelrod as axl

In [15]: p = axl.WinStayLoseShift()

In [16]: p.classifier['stochastic']
Out[16]: False
```

It's caught by this line in the global memory one player class:

```
53     def set_four_vector(self, four_vector):
54         if not all(0 <= p <= 1 for p in four_vector):
55             raise ValueError('An element in the probability vector, %s, is not between 0 and 1.' % str(four_vector))
56
57         self._four_vector = dict(zip([(C, C), (C, D), (D, C), (D, D)], map(float, four_vector)))
58         self.classifier['stochastic'] = any(0 < x < 1 for x in set(four_vector))
```

And this is the test which also tests the expected classification (see line 19):

```
   13 class TestWinStayLoseShift(TestPlayer):
   14
   15     name = "Win-Stay Lose-Shift"
   16     player = axelrod.WinStayLoseShift
   17     expected_classifier = {
   18         'memory_depth': 1,
   19         'stochastic': False,
   20         'makes_use_of': set(),
   21         'inspects_source': False,
   22         'manipulates_source': False,
   23         'manipulates_state': False
   24     }
```

Closing this but let me know if you're not getting the same behaviour @mojones or if I've misunderstood (and just reopen the issue). :+1:

**Comment by mojones** [comment]
It gets classified as stochastic when constructed, but not before:

```
axelrod.WinStayLoseShift.classifier['stochastic']

True


axelrod.WinStayLoseShift().classifier['stochastic']

False
```

Which was causing problems when I wanted to get a list of classes like

`[s for s in axl.ordinary_strategies if not s.classifier['stochastic'] ]`

**Comment by drvinceknight** [comment]
Ah yes: that's a good point.

What do you reckon @marcharper? Easy enough to just have a line that overwrite the classifier for the class?

**Comment by marcharper** [comment]
The default classification of a player class `s` should match the classification of `s()` whenever the default parameters are used. So let's add a line in that fixes this for WSLS and any other affected strategies.

**Comment by drvinceknight** [comment]
#511 fixes this.
