### ISSUE TITLE
Rename `tournament_type`

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#526]
The `TournamentType` class is passed to the `Tournament` class and is 'mainly' used there to generate matches.

This is great, as it make it very easy to create a tournament using whatever rules we want to build matches.

The different types of tournaments are at the moment (currently just the one: `ProbEndTournament)` built using inheritance from the `Tournament` class. I think it would be more verbose to rename `tournament_type` to `match_generator` or something similar (**suggestions?**).

I've been thinking about this when answering a gitter query about creating a different type of tournament in which I explained that you had to build a new class of tournament and a new class of tournament_type. A new class of tournament and a new class of match generator seems more explicit.

**To be clear: I'm not suggesting any change of functionality, just a rename of a class.**

An alternative would be to move the match generation functions out of the class and just have them as methods of the tournament but I think this is not necessary and it could be nice to keep these things separated (although I'm not entirely sure why).

**Comment by meatballs** [comment]
I've been thinking something similar, so yes!

(I also like 'Arena' as used in https://github.com/tscizzle/IPD_Morality  - similar to our TournamentManager)

**Comment by drvinceknight** [comment]
> I've been thinking something similar, so yes!

Cool. I'll put something together. I've also thought of a nice example, I think as to why they can be kept separate (`match_generator/tournament_type` and `tournament`), I'll write that in to a tutorial on "creating new tournaments".

> 
> (I also like 'Arena' as used in https://github.com/tscizzle/IPD_Morality - similar to our TournamentManager)

I like the name too (although `TournamentManager` does say what it does...). Happy either way.

**Comment by drvinceknight** [comment]
Closed by #531
