### ISSUE TITLE
Pickle Protocol Version

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/Axelrod#530]
The DeterministicCache class currently uses whatever pickle protocol the local python installation sets. For python 2.x, it's version 2 and for python 3.x it's 3.

A suggestion was made that we could specify the version to use so that it's consistent everywhere.

The only benefit I can see is that this would simplify our test code which currently has to derive the python version and set the expected pickle output accordingly.

The downside would be that, in order to be generic, we would have to specify the lowest common denominator (protocol version 2). The later versions were introduced for good reason, one of them being speed, and that's exactly what our cache is intended to improve.

My opinion for the moment is that we should leave it as is - but am I missing something where it might be of further benefit?

**Comment by drvinceknight** [comment]
I'm mostly agnostic but perhaps in favour of leaving it as it is.

**Comment by marcharper** [comment]
I'd advocate dropping Python 2 support at some point in the near future. It solves a number of issues (like random number generation), and well, it's been 7.5 years since it was released.

**Comment by drvinceknight** [comment]
At some point but I don't want us to do it too soon. The complications that arise aren't insurmountable. 

I guess though that implies that you're also happy with the status quo re pickle protocol?

**Comment by drvinceknight** [comment]
On #534, just seen:

```
next = __next__  # Python 2
```

heh heh... much sympathies...

**Comment by marcharper** [comment]
Unless there's a major improvement in the protocol I'm fine with the older one that works in all the versions we support.

**Comment by drvinceknight** [comment]
> Unless there's a major improvement in the protocol I'm fine with the older one that works in all the versions we support.

Just to clarify: that's not the status quo right? Currently, in the tests we check the py version and work with that. 

Owen and I both are happy with that, so the cache takes advantage of py3 when it's used.

**Comment by marcharper** [comment]
As long as you are both handling it I'm fine with that too :)

**Comment by drvinceknight** [comment]
👍

**Comment by meatballs** [comment]
Thanks all. I'm going to close this with the decision to leave things as they are i.e. The protocol version is whatever the local python implementation defaults to and our tests have to allow for that.
