### ISSUE TITLE
Setting information passed to players by matches

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/Axelrod#538]
The conversations on #493 and #537 sparked the idea that a tournament could define the set of information which its matches could pass on to the players. Currently, the length, game and noise are always passed to all players.

e.g.
```
{
    'length': True
    'game': True
    'noise': True
}
```

Alternatively, we could pass the actual values which we want the players to use (which may or may not be the correct values).

**Comment by drvinceknight** [comment]
:+1:

**Comment by marcharper** [comment]
I'd like to pass this info through to the Moran process matches as well.
