### ISSUE TITLE
Add cache to prob end tournament

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#543]
Following #540 the cache can be used for more or less every match that has the potential to be repeated (regardless of structure of the tournament).

Thus it can be used in the prob end tournament and perhaps could also be used 'more' elsewhere (I'm not completely familiar with the defaults, it might make sense to tweak those?).

**Comment by meatballs** [comment]
Whoops! sorry, I meant to sort that as part of #540

**Comment by marcharper** [comment]
I'l try to get this working with the Moran process.

**Comment by drvinceknight** [comment]
No biggy, no harm in doing it in steps :)

**Comment by marcharper** [comment]
Well it would likely speed up the computations that i'm currently running...

**Comment by drvinceknight** [comment]
My response was to @meatballs 's apology for leaving it out messages crossed). Getting it in the Moran process would be great :)

**Comment by marcharper** [comment]
Oh, gotcha. So question @meatballs, say I want to rebuild the cache. How do I invoke that at the beginning of a script? Something like:
```
import axelrod as axl
cache = axl.rebuild_cache()
match = Match(..., cache=cache)
```

**Comment by meatballs** [comment]
at the moment, the only we have is via the TournamentManager class. Might be worth a new ticket to look at improviing that.

**Comment by drvinceknight** [comment]
Could you not just create a new cache object instance?

```
cache = axelrod.DeterministicCache()
match = Match(..., cache=cache)
```

**Comment by marcharper** [comment]
@drvinceknight That will load an existing cache but not create a new one (I think)

**Comment by drvinceknight** [comment]
Oh really?

Running:

```
>>> axl.DeterministicCache()
{}
```

Here's me with a screenshot just playing around with #544:

https://www.dropbox.com/s/j7min2fjtatyg0c/Screenshot%202016-04-16%2019.19.05.png?dl=0

**Comment by drvinceknight** [comment]
Am I misunderstanding?

**Comment by marcharper** [comment]
It's tournament that builds the cache, there's no code in Deterministic cache to build one.

**Comment by drvinceknight** [comment]
> It's tournament that builds the cache, there's no code in Deterministic cache to build one.

Ah ok I think I was misunderstanding what was meant by 'build' :)

By build cache we mean: 'put stuff in there (potentially from file)'? Not: 'create an empty cache ready to put stuff in there (by some way or another)'.

**Comment by drvinceknight** [comment]
We should probably move this to #545, @meatballs has submitted a 1 line deletion that fixes this issue :)
