### ISSUE TITLE
Make Cache Buildable on Demand

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#545]
Re: #543 
I.e.:

```
import axelrod as axl
cache = axl.rebuild_cache()
match = Match(..., cache=cache)
```

**Comment by drvinceknight** [comment]
Continuing from #543:

So is the idea that 

```
cache = axl.rebuild_cache(filename)
```

Would take a filename so that we can 'build a cache' from a file? The tournament currently does that but we want to be able to do it outside (as for the moran process or whatever else)? 

(Just catching up with everyone, I had misunderstood on #543 I think.)

**Comment by marcharper** [comment]
I want to do this actually:
```
import axelrod as axl
strategies = [...]
cache = axl.build_cache(strategies, filename="")
match = Match(..., cache=cache)
```

**Comment by drvinceknight** [comment]
Ah cool, you add the `strategies` so it only builds the smallest cache necessary?

**Comment by marcharper** [comment]
Exactly. I'm working on it now.

**Comment by drvinceknight** [comment]
Sweet. We could also have a function that updates the cache file? Actually that might already be a method on the cache... :+1:

**Comment by marcharper** [comment]
Turns out it i's actually faster for my code to generate a new cache for each set of matches, I guess because it avoids a lot of dictionary look ups when there's really only one value that it needs per match.

**Comment by meatballs** [comment]
> So that I can use a cache without having to run a tournament to build it.

you already can if you pass the same cache object to each match - which is all the tournament does

**Comment by meatballs** [comment]
> Would take a filename so that we can 'build a cache' from a file?

You already can - the init for the cache will take a filename

**Comment by marcharper** [comment]
Yeah I see that now @meatballs

**Comment by drvinceknight** [comment]
> You already can - the init for the cache will take a filename

So we __can__ already do this by doing:

```
cache = axl.DeterministicCache(filename)
```

Just checking I understand :) ?

The cache has a `save` method, is it worth having a `update=False` default so that you can choose to update a saved cache if you wanted to (by changing that to `update=True`, with `False` it would overwrite)?

**Comment by marcharper** [comment]
Not sure, but I found that the best thing to do for my purposes is to add an internal cache to the Moran process that persists across resets (essentially exactly how the tournament class works). I'll open a PR shortly.

**Comment by drvinceknight** [comment]
I'll open an issue for writing a quick tutorial about the cache object. I suggest I write it, as I think I'm the one that perhaps has touched it the least, you guys can check I've understood?

**Comment by drvinceknight** [comment]
> I'll open a PR shortly.

I'm going offline for the night, will check it out tomorrow (only saying as this, as it's been a fun couple of hours with us all working at the same time :)).
