### ISSUE TITLE
Bump release number

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#551]
@drvinceknight @meatballs @langner 

The library is definitely at a point that it can both recreate recent tournaments and can be used for a variety of research purposes, including the generation of great new strategies.

We should consider giving the library at higher release number. At the least a roadmap to 1.0 would be a good thing to lay out.

**Comment by drvinceknight** [comment]
I'm all for this :+1:. Should the next one be 0.1 and we talk about what we want for 1.0 or are we ready for 1.0 already?

**Comment by langner** [comment]
I don't have an strong opinion about this, as long as the versions are reasonable. I'm not sure if we wanted to follow a semantic versioning scheme or something else?

**Comment by marcharper** [comment]
How about 0.9 and we start a new issue for 1.0 milestones? Or we start with the 1.0 discussion and see if we're already there?

**Comment by drvinceknight** [comment]
> How about 0.9 and we start a new issue for 1.0 milestones? Or we start with the 1.0 discussion and see if we're already there?

Sounds good to me.

> a semantic versioning scheme or something else?

Can you say more about what this means @langner? I'm not too familiar with this sort of stuff...

**Comment by meatballs** [comment]
http://semver.org/

**Comment by meatballs** [comment]
> How about 0.9 and we start a new issue for 1.0 milestones? Or we start with the 1.0 discussion and see if we're already there?

I like option 2 ^

**Comment by drvinceknight** [comment]
Thanks @meatballs, I'm happy to go with that :) We should make efforts to not have to "make incompatible API changes," :)

> I like option 2 ^

We can use the github milestone thingy... Can that continue on this issue? Anything specific we feel is needed before 1.0?

**Comment by drvinceknight** [comment]
Closing this as discussion has moved to #553.
