### ISSUE TITLE
Refactor Factory Classes?

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#552]
Does anyone have thoughts about replacing the `TournamentManagerFactory` classes (and maybe the `TournamentManagers`) with scripts that directly call the `Tournament` objects? There are at least a few benefits:
* The library itself serves as examples of how to run tournaments in a way more typical of an external user
* Simplifies the library by removing some classes. The factory classes are only used internally and are not documented for external usage
* It's easier to follow the logic of what's going on
* It's arguably more pythonic

Of course there is significant potential downside:
* [if it ain't broke don't fix it](https://en.wiktionary.org/wiki/if_it_ain't_broke,_don't_fix_it)

**Comment by drvinceknight** [comment]
> Does anyone have thoughts about replacing the TournamentManagerFactory classes (and maybe the TournamentManagers) with scripts that directly call the Tournament objects? 

Yes please.

> It's easier to follow the logic of what's going on

I have to admit I found it quite confusing going through the `TournamentManager` to the `TournamentManagerFactory` when I was adding prob end to the `run_axelrod` script. Given that the tournament api is quite simple now I think this level of abstraction is not needed but perhaps I'm missing something.

For info, when it came to running the tournament on our university cluster, as I had to do it in two intermediate steps (write data, then analyse), to make sure I knew what was happening this is what I had, (repeated for each of the 3 tournaments):

- This runs the tournament: https://github.com/Axelrod-Python/tournament/blob/gh-pages/run_noisy.py
- This analyses it: https://github.com/Axelrod-Python/tournament/blob/gh-pages/analyse_noisy.py

I realise there's repetition for the plotting but I think we could make `run_axelrod` much simpler by simply having a `plot_all` function that takes a `result` set and then 1 function for each tournament (`run_basic_strategies`, `run_strategies`,...) type we wanted (that would basically be 1 line of code), then the arguments being read in could just call those functions. I realise there will be some minor duplication of code but I think that the gain in readability is worth it.

These functions wouldn't need to be part of the library themselves, they just make use of the library. We could put them at the top of `run_axelrod` which I think would make it more readable.

Perhaps a 1st step would be to refactor `run_axelrod` (given all the dependencies, we could also now use docopt perhaps?), if we have all the functionality without the need for the `Manager` and `Factory`, classes we could remove them?

**Comment by meatballs** [comment]
Yes, I think that now we've simplified the structure with the Match class, we ought to look again at the TournamentManager/TournamentManagerFactory classes and the run_axelrod script. I think there's plenty of scope for improvement!

**Comment by marcharper** [comment]
Great, I like this suggestion:

> Perhaps a 1st step would be to refactor run_axelrod (given all the dependencies, we could also now use docopt perhaps?), if we have all the functionality without the need for the Manager and Factory, classes we could remove them?

**Comment by drvinceknight** [comment]
> Great,

Unless anyone can get to it sooner, I'm happy to have a go at this. Busy this evening, so will probably get to it by end of tomorrow (Tuesday).

**Comment by marcharper** [comment]
I likely won't have a chance before then.

**Comment by drvinceknight** [comment]
Here's my re write of `run_axelrod` https://github.com/Axelrod-Python/Axelrod/pull/557.

**Comment by drvinceknight** [comment]
Just another thought: what about we just remove `run_axelrod` all together? 

There are scripts for it on the tournament repo, docs and there is the notebooks repo also. We could then take out the `Manager` and `Factory` classes (and possibly the logger?). This simplifies things and further modularises code, I don't think that in practice it's a big step with regards to usability (and in line with #553)...

**Comment by meatballs** [comment]
> Just another thought: what about we just remove run_axelrod all together?

My mistake. I thought that was the intention of this issue from the beginning!! Either way, yes from me

**Comment by drvinceknight** [comment]
> My mistake. I thought that was the intention of this issue from the beginning!! Either way, yes from me

My mistake actually! Reading it back I think you're right, I misinterpreted "with scripts that directly..." (although @marcharper, I'm suggesting we don't even have those and just point to notebooks, tournament docs etc...). I'll have a go at that, should be straightforward (famous last words). :) 👍

**Comment by marcharper** [comment]
I guess we don't need it all. We'd have to rewrite the tournament repo script, which should be easy to do with what you've already done on #557.

**Comment by drvinceknight** [comment]
The tournament script has already been changed a bit (to just be run by
separate scripts anyway for my university cluster). I can add the basic
tournaments to that when it comes to it (or we can add whatever really:
whatever makes updating those results easier, not as important a decision
compared to the library itself I guess?). :)
