### ISSUE TITLE
Which versions of python 3 to support?

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#554]
I think it's safe to say that most using Python 3 will be on a recent version. With Python 3.6 on the horizon, I suggest we officially support the two latest versions of Python 3. That means dropping 3.3 support now and 3.4 when 3.6 is released.

Thoughts?

**Comment by drvinceknight** [comment]
Just asking: if we're going to continue to support py2 (which I personally feel we should for a while longer) is there an advantage to dropping any py3s?

**Comment by meatballs** [comment]
> is there an advantage to dropping any py3s?

For me, yes.  I tend to view Python 2 and Python 3 as almost separate languages, but each has a current version, which we should support.

For Python 3, we should probably support the previous version too, but for Python 2, there's no reason to support anything but the current version.

**Comment by drvinceknight** [comment]
> For Python 3, we should probably support the previous version too, but for Python 2, there's no reason to support anything but the current version.

Yup, I agree for py2.

I'm asking what is the advantage of dropping py3.3, py3.4, if it's just an extra build or two on travis? Given the backwards compatibility we ensure because of py2 I would have thought that py3.3 and py3.4 would/should continue to work?

I don't feel strongly about this, just trying to understand what we gain by dropping any py3s at all. Is the idea that there could potentially be a problem at some point and it makes sense to reduce the number of pys we say "this works for sure"?

**Comment by meatballs** [comment]
> Is the idea that there could potentially be a problem at some point and it makes sense to reduce the number of pys we say "this works for sure"?

for me, yes. We get rid of the Travis builds for those versions and speed things up there too.

**Comment by drvinceknight** [comment]
Ok, I would have thought we could just keep them until there's an issue (as it's just travis time that it costs in the meantime and at least we'd know that something doesn't work on py3.x) **but I'm very happy to go with whatever you guys feel is best. No doubt I'm missing something about the potential complications** :)👍

**Comment by marcharper** [comment]
I don't the two versions as that different -- it's most what is a generator or not, print statement versus function, etc. and the issues can typically be solved by `from __future__` and `list(...)`. But travis does seem to have a high fail rate so a one less build is a plus. At the rate we're going we'd soon have another version rather than one less.
