### ISSUE TITLE
init_args not quite behaving as expected?

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#568]
Not too sure if that's quite the right title, there's a bit of unexplained/unexpected behaviour with how the init_args decorator is working for the EvolverLookerUp strategy.

See this (closed) PR for more details: #567. Basically the following:

```
>>> import axelrod as axl
>>> lookup_table = {('', 'C', 'D') : "D", ('', 'D', 'D') : "D", ('', 'C', 'C') : "D", ('', 'D', 'C') : "D",}
>>> p = axl.LookerUp(lookup_table)
>>> p.init_args == p.clone().init_args
True
>>> p = axl.LookerUp()
>>> p.init_args == p.clone().init_args
True
>>> p = axl.EvolvedLookerUp()
>>> p.init_args == p.clone().init_args
True
```

is not quite expected as we are not setting the init args. The above is the behaviour we want but after a  conversation on gitter we're not sure why it's happening as it was thought that a line of code was actually missing.

I realise this is not a well written issue/bug report but I'm not entirely sure I understand what's going on. Just opening this to keep track :) :+1:

**Comment by marcharper** [comment]
Here's what I don't get. If you apply `@init_args` to a base class `__init__`:

```
def init_args(func):
    """Decorator to simplify the handling of init_args. Use whenever overriding
    Player.__init__ in subclasses of Player that require arguments as follows:

    @init_args
    def __init__(self, myarg1, ...)
    """
    @wraps(func)
    def wrapper(self, *args, **kwargs):
        r = func(self, *args, **kwargs)
        self.init_args = args
        return r
    return wrapper
```
then we should see that `self.init_args` is set to the arguments. But then when we clone the child class:
```
    def clone(self):
        """Clones the player without history, reapplying configuration
        parameters as necessary."""

        # You may be tempted to reimplement using the `copy` module
        # Note that this would require a deepcopy in some cases and there may
        # be significant changes required throughout the library.
        # Consider overriding in special cases only if necessary
        cls = self.__class__
        new_player = cls(*self.init_args)
        new_player.match_attributes = copy.copy(self.match_attributes)
        return new_player
```
it should be passing `self.init_args` to the child `__init__`, causing an argument error. If you apply `@init_args` to the child `__init__` as well, it should overwrite `self.init_args` and everything is fine.

So why can we clone `EvolvedLookerUp` without any errors?

**Comment by marcharper** [comment]
I get it now. The function decorated by `@init_args` overwrites the arguments every time it's called because `self.init_args` is saved inside the wrapper function, including when the parent `__init__` is called in the child class `__init__`. So what I said on gitter a few days ago isn't correct. I recommend that we close the issue.

**Comment by drvinceknight** [comment]
👍
