### ISSUE TITLE
Increase coverage / handling the case when matplotlib is not installed

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#581]
On #579 I took a closer look at the coverage.

Here's the output from master at 6cab8c801c7d06d256a8ca9371dbd50f986a52bf:

```
Name                                  Stmts   Miss  Cover   Missing
-------------------------------------------------------------------
__init__.py                              15      0   100%   
_strategy_utils.py                       68      3    96%   102, 112, 116
actions.py                                9      0   100%   
deterministic_cache.py                   48      4    92%   56, 60, 92, 145
ecosystem.py                             34      0   100%   
eigen.py                                 30      0   100%   
game.py                                  14      0   100%   
interaction_utils.py                     55      0   100%   
match.py                                 66      0   100%   
match_generator.py                       63      1    98%   45
mock_player.py                           25      0   100%   
moran.py                                 81      2    98%   44, 115
player.py                                79      1    99%   119
plot.py                                 176     30    83%   11-12, 21, 34-45, 50, 63, 88-93, 112, 117-122, 170-175, 202, 218, 243, 246-247, 264
random_.py                               11      0   100%   
result_set.py                           267      0   100%   
strategies/__init__.py                    8      0   100%   
strategies/_strategies.py                35      0   100%   
strategies/alternator.py                 10      0   100%   
strategies/apavlov.py                    64      0   100%   
strategies/appeaser.py                   13      0   100%   
strategies/averagecopier.py              18      0   100%   
strategies/axelrod_first.py             192      1    99%   112
strategies/axelrod_second.py             51      0   100%   
strategies/backstabber.py                29      0   100%   
strategies/calculator.py                 27      0   100%   
strategies/cooperator.py                 14      0   100%   
strategies/cycler.py                     44      0   100%   
strategies/darwin.py                     32      0   100%   
strategies/defector.py                   14      0   100%   
strategies/forgiver.py                   16      0   100%   
strategies/gambler.py                    26      0   100%   
strategies/geller.py                     22      0   100%   
strategies/gobymajority.py               63      0   100%   
strategies/grudger.py                    48      0   100%   
strategies/grumpy.py                     28      0   100%   
strategies/hunter.py                     90      0   100%   
strategies/inverse.py                    10      0   100%   
strategies/lookerup.py                   48      0   100%   
strategies/mathematicalconstants.py      23      0   100%   
strategies/memoryone.py                 163      0   100%   
strategies/meta.py                      146      0   100%   
strategies/mindcontrol.py                24      0   100%   
strategies/mindreader.py                 33      0   100%   
strategies/oncebitten.py                 67      0   100%   
strategies/prober.py                     62      0   100%   
strategies/punisher.py                   55      0   100%   
strategies/qlearner.py                   71      1    99%   57
strategies/rand.py                       12      0   100%   
strategies/retaliate.py                  69      0   100%   
strategies/sequence_player.py            33      0   100%   
strategies/titfortat.py                 103      0   100%   
strategy_transformers.py                148      0   100%   
tests/__init__.py                         0      0   100%   
tournament.py                           124      0   100%   
-------------------------------------------------------------------
TOTAL                                  3076     43    99% 
```

There's some really low hanging fruit (the last column: line numbers, point out things that would push the 98,99%s to 100% really easily).

For the `plot.py` file the low coverage is actually mainly due to our catches for when `matplotlib` is not installed (apart from that it's just some simple title settings that would be easy to test). I was very keen on making that (matplotlib not being a strong requirement) a possibility but the library really has matured now (numpy is a strict requirement for example) so perhaps that's not necessary, I have two suggestions:

1. Remove the error handling for when matplotlib is not installed and just assume it's installed from here on in. 
2. See if it's possible to pretend that matplotlib is not installed and test that the error handling we've got in place

I think my preference would be to go with 1: this simplifies the code base (and improves the coverage ratio).

**Comment by marcharper** [comment]
I also vote for option 1, since if a user installs with pip then they'll have matplotlib as well. And if they use anaconda, they'll already have numpy, mpl, and a bunch of other things. I basically consider them in the "standard library".

**Comment by meatballs** [comment]
One fly in the ointment is matplotlib not working with virtualenv

**Comment by meatballs** [comment]
Slightly more detail on my comment above is here:http://matplotlib.org/faq/virtualenv_faq.html

It does work, but it can be a pain depending on your local environment. I don't bother having it installed in my Axelrod dev virtualenv, for example, as it's far too much pain and grief.

**Comment by drvinceknight** [comment]
Well we definitely need to keep the library usable from a virtual env so that might just be that until matplotlib install nicely in one...

Related: It's causing me grief with py3.4 on travis right now... Trying to get it to install: for some reason it's just stopped! (fine on py2 and py3.5). Does this look similar to the virtual env error? https://travis-ci.org/Axelrod-Python/Axelrod/jobs/129327836 I'm hoping it's a temporary issue with travis.

(Am playing around with a `580-vk` branch.)

**Comment by drvinceknight** [comment]
Having a go at the low hanging fruit (will leave the matplotlib alone for now).

**Comment by drvinceknight** [comment]
Going through the coverage report and adding tests. Line 45 in `match_generator` is not currently being tested:

```
 38     @opponents.setter
 39     def opponents(self, players):
 40         if self.clone_opponents:
 41             opponents = []
 42             for player in players:
 43                 opponents.append(player.clone())
 44         else:
 45             opponents = players
 46         self._opponents = opponents
```

This is because al our tests are for the `RoundRobin` and `ProbRoundRobin` which **do** clone the opponents. Just checking, with the various changes that have happened recently will there ever be a case where we do **not** clone the players? (IE can this be removed?)

**Comment by marcharper** [comment]
I think we always want to clone them, so the conditional (and the boolean) can be removed.

**Comment by drvinceknight** [comment]
Have opened #588, only things not being tested in there are the matplotlib exceptions.

**Comment by drvinceknight** [comment]
I'm going to close this: we can revisit matplotlib if need be.
