### ISSUE TITLE
Authors in license

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#615]
Currently the license just has my name to it, I imagine this is just a relic of when I started the library. I suggest we put the code devs there or perhaps the Axelrod-Project development team? Is that a done thing? Don't really know what's best.

**Comment by drvinceknight** [comment]
https://github.com/Axelrod-Python/Axelrod/blob/master/LICENSE.txt

**Comment by meatballs** [comment]
Good explanation here: http://haacked.com/archive/2006/01/26/WhoOwnstheCopyrightforAnOpenSourceProject.aspx/

**Comment by drvinceknight** [comment]
As the "Axelrod-Project development team" is not a legal entity (or a coorporation as in that explanation) could we still put that? I think that's what I'd prefer... What do you reckon?

**Comment by meatballs** [comment]
The copyright needs to be held by a legal entity - so that's either an individual person or some form of corporate body. For us, I reckon that means it's either @drvinceknight (as he's the one that kicked it all off) or Cardiff University. 

We could look into creating some kind of unincorporated association to hold the rights but that's probably more trouble that it's worth.

Another good explanation here: http://ifosslawbook.org/uk/

**Comment by drvinceknight** [comment]
> We could look into creating some kind of unincorporated association to hold the rights but that's probably more trouble that it's worth.

I think that does sound like more work that it's worth. 

FYI, Have just checked a couple of other packages:

- https://github.com/astropy/astropy/blob/master/licenses/LICENSE.rst they have 'Astropy Developers'
- https://github.com/scikit-learn/scikit-learn seem to just state the license without mention of copyright
- https://github.com/matplotlib/matplotlib/blob/master/LICENSE/LICENSE have: "Matplotlib Development Team"
- https://github.com/numpy/numpy/blob/master/LICENSE.txt have "NumPy Developers"

So perhaps "Axelrod-Project development team" is ok?

**Comment by meatballs** [comment]
> So perhaps "Axelrod-Project development team" is ok?

I don't think so. If we're going to bother with a copyright statement, then we should get it right and that means it has to be a legal entity.

**Comment by meatballs** [comment]
Or, we somehow define and make public the rules about who the Axelrod Project development team consists of. That makes it an unincorporated association and the copyright is held jointly by its members.

**Comment by marcharper** [comment]
I'm not an expert on these matters. As far as I understand, everything that's been contributed is by default covered by the existing license, i.e. owned by @drvinceknight . He may or may not have legal agreements with Cardiff that gives them some legal rights.

That said I don't see a reason to expand the copyright beyond the core team (or even just @drvinceknight), the license is already very liberal.

**Comment by langner** [comment]
My (decreasingly influential) vote is for a "team" to be noted... whether
precise or note, it is what most projects put in.

**Comment by drvinceknight** [comment]
How about moving it to the core team? Ie listing our four names? We could also just leave it as it is? 

I am completely agnostic here but have a preference for not just having my name there just because I don't want to assume/take any more credit than anyone else. That's obviously not what's happening with just my name there but new comers to the project might assume so.

**Comment by meatballs** [comment]
How about putting something in the contribution guidelines that explains 

1) The copyright is held by (either @drvinceknight or jointly by the 4 core team members)
2) That by submitting a contribution to the repo, you are assigning the rights of your work to the copyright holder(s)

and gives some explanation as to what that all means with a couple of links for further info.

**Comment by meatballs** [comment]
I have no objection to @drvinceknight being the sole holder but I'm also happy for it to be jointly held by the core team. I just can't see any point naming an entity that has no legal standing - in that case, we might as well not bother with the copyright at all if it's that unimportant to us.

**Comment by drvinceknight** [comment]
> 2) That by submitting a contribution to the repo, you are assigning the rights of your work to the copyright holder(s)

Ehhh are we doing that? I thought the copyright automatically stayed with the contributors and it was just being released under the same license? (That's how it is with sagemath). Such a statement would specifically take the copyright away right from the contributors?

I don't seem to see anything like that on other projects (but they also mainly have '<project name> team' as the copyright holders)?

> copyright at all if it's that unimportant to us.

That's an idea. The way I understand it is that we need a license to allow people to use it (it's not a restrictive thing but in fact a permissive thing right?). What's the copyright actually for? Perhaps we can just do away with it as you suggest and so it's all just done 'automatically'? 

I know that on the sagemath project some people add a copyright statement to contributions but that there is in fact no need to do so because it's assumed anyway (there was a recent discussion about this).

**Comment by meatballs** [comment]
> Ehhh are we doing that?

No, we're not at the moment.

> I thought the copyright automatically stayed with the contributors and it was just being released under the same license?

But we're also not recording the copyright when contributions are made - e.g. do we really want 3 lines of code within tournament.py copyrighted to me, the next 5 to somebody else and the rest to yet another? I suspect not.

It also becomes very difficult when more than one person works on the same code - which often happens when we review PRs.

Other projects do have contributor agreements which do the assignment: https://en.wikipedia.org/wiki/Contributor_License_Agreement

> What's the copyright actually for?

for us, that's a very good question! I suspect none of really cares too much and that dedicating the work to the public domain is probably not a bad option.

**Comment by drvinceknight** [comment]
I am even more agnostic now. Pretty confused. I suppose my instinct would be to follow the examples of other research software libraries but perhaps just easier to leave things as they are: am not sure anything is broken...

**Comment by drvinceknight** [comment]
Here's my conversation with @npch

---

Neil Chue Hong [10:11 AM] 
Hi @vinceknight - what you’re talking about is a process for managing multiple contributors.

Vince Knight [10:11 AM] 
Right.

Neil Chue Hong [10:11 AM] 
There are two basic models

Neil Chue Hong [10:17 AM] 
1) One entity holds the copyright on behalf of all contributors, by asking them to sign a Contributor Licensing Agreement. A good guide is here: http://oss-watch.ac.uk/resources/cla [This is the model that became popular in the 2000’s]

2) Each contributing entity retains copyright to the code they contribute. However contribution guidelines clearly state that contributors assent to the license and inclusion in the canonical version of the software. Where there are multiple contributors to a piece of code, the author line is updated. [This is a model that was used at the start of open source, and which is starting to be used more again: http://ebb.org/bkuhn/blog/2014/06/09/do-not-need-cla.html]

[10:18] 
Advantages of 1) are that it’s easier to relicense the software under a different license as one entity “controls” it. Advantages of 2) are that it requires less administration and seems more “aligned” to open source philosophy.

[10:18] 
In my experience however, university legal departments seem to like 1) better, because it’s more formal and couched in legal terms they understand.

Vince Knight [10:19 AM] 
Thanks Neil. How does 2) (which I think we’d prefer, or at least I would) work for files where different lines of code have been written/rewritten by different people? Is it just that our vcs will allow us to know who owned what and when they owned it?

[10:21] 
Also, in the case of 2) does that mean we’d remove my name from the copyright in the license and basically replace it with a clear statement about assent to the licence etc… ?

[10:21] 
(having that statement in the contributor guidelines)

Neil Chue Hong [10:24 AM] 
Generally, you don’t need to worry about which lines were written by which people past the VCS history. However it’s important in your guidelines that you state that contributors are responsible for asserting that they are allowed to contribute the code they are contributing.

Vince Knight [10:25 AM] 
Thank you. Do you mind if I paste what you have said here in to the issue on our github repo?

Neil Chue Hong [10:26 AM] 
WRT your other question (and this is where it gets messy), what you’d do is you’d keep your name in the copyright in the license, and then add other contributors as they contribute. The way I’ve seen this done in most projects is that this is kept up to date in each individual source code file, but it doesn’t matter so much in the “main” license file in the root of the repo. What you’ll find is that this settles down relatively quickly.

[10:26] 
And yes, happy for you to paste.

[10:27] 
That last bit around the management of names in the license you should quote as opinion, as that part is just my observations, rather than being solid advice :slightly_smiling_face:

Vince Knight [10:27 AM] 
I know on the sagemath project, some people add their name to the copyright in individual source files but a recent discussion has included that opinion that this was not necessary as it was all assumed and in the VCS...

[10:28] 
I will paste this in now. Will tag you for completeness but not asking for you to spend anymore time on this: really appreciate it.
---

**Comment by marcharper** [comment]
Could we simply say "copyrighted by the various contributors" and link directly to the contributors page? Then there's no need to update the license each time there is a new contributor. Also I don't want to get into a situation where we have to discuss if a contribution is significant enough to warrant adding a name to the license.

To clarify one point discussed above, I believe that when people make contributions they are implicitly agreeing to the existing license. If that's not the case please clarify.

**Comment by drvinceknight** [comment]
> Could we simply say "copyrighted by the various contributors" and link directly to the contributors page? Then there's no need to update the license each time there is a new contributor. Also I don't want to get into a situation where we have to discuss if a contribution is significant enough to warrant adding a name to the license.

I like this suggestion.

> 
> To clarify one point discussed above, I believe that when people make contributions they are implicitly agreeing to the existing license. If that's not the case please clarify.

That is also what I believe.

Perhaps both these two points could be put in to the contribution guidelines? Just clarifying things?

**Comment by meatballs** [comment]
> Could we simply say "copyrighted by the various contributors" and link directly to the contributors page?

Sounds like a plan!

> I believe that when people make contributions they are implicitly agreeing to the existing license.

Yes, they are - but that's separate to assigning copyright.

**Comment by drvinceknight** [comment]
> Sounds like a plan!

Perhaps when you get a chance you could pick this up @meatballs?

**Comment by meatballs** [comment]
Will do
