### ISSUE TITLE
Running CI for windows on appveyor

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#616]
Is it worth running our test suite on appveyor ('travis for windows')?

https://www.appveyor.com/

Assuming we can get all the dependencies to build should be straightforward. Also, might help with some of the Windows issues: #322 (perhaps will confirm that can only run the test suite on py3).

**Comment by drvinceknight** [comment]
This might be helpful: https://github.com/ogrisel/python-appveyor-demo

**Comment by marcharper** [comment]
Honestly I'm not sure if it's worth it, but I'm not opposed to trying it out.

**Comment by drvinceknight** [comment]
Very glad we got this implemented: thanks @inglesp!
