### ISSUE TITLE
Naive Prober strategy docstring not indexed

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#631]
Naive prober has been put in it's own module: `naiveprober.py`, I suggest moving it to `prober.py`. This will automatically ensure it appears here: http://axelrod.readthedocs.io/en/latest/reference/all_strategies.html

**Comment by drvinceknight** [comment]
Another approach would be to simply add `naiveprober.py` to the `all_strategies.rst` file but I think it's nicer to have it in the `prober.py` file.

**Comment by meatballs** [comment]
Seems eminently sensible!
