### ISSUE TITLE
Make sure that the attrs option of responses_test actually work properly.

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#634]
Refer to the discussion at #633.

Edit: Could also look at ContriteTFT

**Comment by drvinceknight** [comment]
:+1:

FYI, for when this is looked at  ba1cce5 was failing on the expected response (the C versus the D) so it's not just the attr that aren't working in that case.

**Comment by drvinceknight** [comment]
Wrong hash, I meant 27a065e

**Comment by marcharper** [comment]
The reason for the failures are because the order of random draws is not the same in the two cases since the opponent is `Random()`. The test function actually calls the strategy functions (to try to set the proper internal variables) and then overwrites with the intended (not necessarily actual history). So in this case `random.random()` is called one additional time (in the beginning), which mucks up the random seeding.

As far I as I can tell the test function is working as intended.
