### ISSUE TITLE
Fix Zenodo hook

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#641]
Having to automatically write the zenodo release is a pain and leaves it open to error (because I'm an idiot :)).

When I log in to zenodo, and go to the github tab I see: https://www.dropbox.com/s/dwc3hrdenbux4af/Screenshot%202016-06-21%2009.00.20.png?dl=0

The Axelrod project is nowhere to be seen there. Could @marcharper or @meatballs see if they see the same?

**Comment by meatballs** [comment]
I've authorised zenodo for our github organisation. should work ok now

**Comment by drvinceknight** [comment]
Thanks @meatballs, looks like it's ok:

https://www.dropbox.com/s/p2qnp4s65ggxogl/Screenshot%202016-06-21%2009.11.31.png?dl=0

I'll leave this issue open until a new release (can do one with #639) just to check :)

**Comment by meatballs** [comment]
👍
