### ISSUE TITLE
Suggestion: Adding a 'community' (or something like that) page to the documentation

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#644]
We have currently got 3 top level sections in the docs:

- Tutorials
- Reference
- Citing the library

I suggest making that:

- Tutorials
- Reference
- Community
- Citing the library

Under the community section I suggest we include stuff about communication (gitter, irc, twitter, email,...) also perhaps some sort of CoC as well as that nice thing @meatballs found a while ago (I forget where it was Owen: it was this nice introductory text for some library somewhere). Basically something saying we're friendly and approachable.

**Comment by meatballs** [comment]
👍 Can't remember where I found that myself. I'll have a hunt around

**Comment by meatballs** [comment]
Possibly pybee.org

**Comment by drvinceknight** [comment]
> I think it was a project that was using this: http://contributor-covenant.org/

I don't think it was that (although that looks great and we should include that or similar). I remember something about 'being part of the team'. Of course I might well be making this up. I thought it was a project of @lukasa's but I've looked through his and don't seem to be able to find it...

**Comment by Lukasa** [comment]
I have [this](http://python-hyper.org/en/latest/one-of-the-team.html) and [this](http://python-hyper.org/en/latest/contributing.html).

**Comment by drvinceknight** [comment]
Thanks Cory. I think the second one was the one I was remembering.

**Comment by meatballs** [comment]
Even if that wasn't it, there's some great stuff there for us to consider. Thanks @lukasa

**Comment by Lukasa** [comment]
My pleasure folks, happy to be of any use at all for a project like Axelrod!

**Comment by drvinceknight** [comment]
I'm having a go at this.
