### ISSUE TITLE
Remove csv method from results set

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#645]
The `ResultSet` class has a csv method that writes the payoffs of players to a csv string. This is very much superseded by the new file format for tournament interactions. I suggest we remove it (it's a relic of my early implementation where everything that happened during the tournament was lost).

**Comment by meatballs** [comment]
👍

**Comment by Nikoleta-v3** [comment]
I can pick this up !

**Comment by Nikoleta-v3** [comment]
I can pick this up !
