### ISSUE TITLE
Renaming `strategies`

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#664]
So a while ago we had a long discussion about the lists containing our strategies. The main conclusion (of which I was heavily in favour) was that `axelrod.strategies` includes ALL the strategies and `axelrod.ordinary_strategies` includes those that 'do not cheat'.

My main argument in favour of this was that we don't want to label strategies at all thanks to the classification. I have seen a few people get caught out by the fact that cheaters are present in `axelrod.strategies`. As the library really has evolved in to a powerful research tool (far from the original 'tournament on github') I think I was mistaken before and would suggest the following naming:

```
axelrod.strategies -> axelrod.all_strategies # Or something like that? (Or perhaps we don't even need this?)
axelrod.ordinary_strategies -> axelrod.strategies  # axelrod.ordinary_strategies can stay put with perhaps some sort of depreciation? (just to make sure we're not breaking anything)
axelrod.cheating_strategies  # to include the strategies that are classified as cheating
```

The main output of this would be that if you want to do serious IPD research then, `axelrod.strategies` is the list you need (I think, if my memory serves me correctly this is what @marcharper was in favour of).

Any thoughts?

**Comment by meatballs** [comment]
I'm fairly agnostic on this one.

**Comment by marcharper** [comment]
I'm in favor, obviously. My main complaint with the cheating strategies is that they are often much more computationally demanding (in addition to their other shenanigans). I suggest also moving some of the more intense strategies out of the "standard list" including all the meta strategies except meta hunter. (The cycle hunters are also pretty demanding...)

**Comment by langner** [comment]
+1

**Comment by drvinceknight** [comment]
Great, I'll go ahead and put that together.

>My main complaint with the cheating strategies is that they are often much more computationally demanding (in addition to their other shenanigans). I suggest also moving some of the more intense strategies out of the "standard list" including all the meta strategies except meta hunter.

So my main concern with the cheaters is for newcomers to the library (with no in depth knowledge) wanting to quickly access 'valid'/'non cheating strategies'. I've seen 2 people recently expecting (understandably) that they would be in `axelrod.strategies` (and getting weird results from their tournaments when they had the cheaters in there). Without reading the docs very carefully or looking through the source code there is nothing really telling anyone that there even are cheating strategies anymore.

So my worry about moving the 'computationally heavy' strategies out of the proposed `axelrod.strategies` list would be that this would replace one problem with another: the meta strategies are still valid and interesting from a research point of view and a new user would still (I believe) want them in?

Would perhaps, having "another" list for these "heavier" strategies be ok?

So, for newcomer, to create a strategy and pit it against all the 'non cheating strategies' in the library would go:

```
players = [s() for s in axelrod.strategies]
players.append(new_strategy())
tournament = ...
```

For those who would want to exclude heavier strategies, for example from the pov of someone wanting to train strategies they could do something like:

```
players = [s() for s in axelrod.strategies if s not in axelrod.recursive_strategies]  # Or whatever we want to call them
```

This would:

1. Ensure that complete newcomers get valid strategies from axelrod.strategies without needing to know to combine various lists of strategies.
2. Slightly more knowledgeable users can get rid of heavy strategies without having to actually name them explicitly.

No matter what we decide to do, in the PR I think it's worth adding a tutorial before the 'Creating Matches' one (or maybe just after...) perhaps about 'accessing strategies' and simply saying where they all are?

**Comment by drvinceknight** [comment]
Have opened #665 with an attempt of this.
