### ISSUE TITLE
Rank strategies by run time

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#666]
Re: the discussion at  #665 
Edit: Here's the [spreadsheet](https://docs.google.com/spreadsheets/d/1v65yMUeCW26kplPSsoRUUoEEV5NwM5bMEoTuQuqByQg/edit?usp=sharing)

**Comment by meatballs** [comment]
Good old [Robocode](http://robocode.sourceforge.net/) used to create tournaments which pitched strategies of similar complexity against one another by placing limits on the amount of memory a strategy instance consumed for a given tournament.

We might consider something similar...

**Comment by drvinceknight** [comment]
Closing this: have opened https://github.com/Axelrod-Python/Axelrod-notebooks/issues/3 on the notebook repo to make sure we move over the code.

(Feel free to re-open if we think there's something we should do here for the library itself.)
