### ISSUE TITLE
Use __slots__ to reduce memory footprint

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/Axelrod#667]
The second point in [this talk](https://www.youtube.com/watch?v=_O23jIXsshs) shows how using ```__slots__``` within classes can dramatically reduce the memory footprint.

The only potential gotcha is that you then cannot dynamically create attributes on a class where ```__slots__``` has been defined. We aren't doing that anywhere at the moment and it seems unlikely that we'll be doing so any time soon.

**Comment by drvinceknight** [comment]
I'm playing around with the results set #573 (where memory is the real issue): I'll try this there as well at some point :)

**Comment by meatballs** [comment]
I already have some code for this. i'll push it

**Comment by meatballs** [comment]
branch issue-667

**Comment by drvinceknight** [comment]
Cool, any indication as to the difference it makes?

**Comment by meatballs** [comment]
> Cool, any indication as to the difference it makes?

Not yet. Still working on it and #668 is causing me grief!

**Comment by drvinceknight** [comment]
Cool. :+1:

**Comment by meatballs** [comment]
This is just about done. I can't assess whether it's been worthwhile as I can't run anything on my machine until #669 is merged.

**Comment by drvinceknight** [comment]
Ah! Sorry I had assumed you'd branched off of that...

Will merge it now so that you can actually work!

**Comment by meatballs** [comment]
Thank you kindly!

**Comment by meatballs** [comment]
Unfortunately, this makes little difference to the memory footprint.

Slots makes most difference when there are many instances of a class being held in memory at the  same time. Our issue occurs during the build of a result set - which only has a single instance - and so the use of slots make no difference at all.
