### ISSUE TITLE
Tournament Transformers?

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#678]
Implement `@noise(noise)` and `@spatial(graph)` decorators for tournament classes.

**Comment by drvinceknight** [comment]
Awesome idea. 👍

**Comment by marcharper** [comment]
Perhaps -- I can still think of some ideas, like applying a transformer to all strategies, or further tournament variations. But we can close if you'd like and reopen later if needed.

**Comment by drvinceknight** [comment]
:+1:

**Comment by marcharper** [comment]
It might be worth thinking about decorators for `Match`.
