### ISSUE TITLE
Problems running tournaments with restrictive file permissions

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#680]
Just had an email with the following error:

```
Playing matches:   0%|          | 0/6 [00:00<?, ?it/s]
                                                      

Analysing:   0%|          | 0/60 [00:00<?, ?it/s]Traceback (most recent call last):
  File "<pyshell#10>", line 1, in <module>
    results = tournament.play()
  File "C:\Python34\lib\site-packages\axelrod\tournament.py", line 113, in play
    keep_interactions=keep_interactions)
  File "C:\Python34\lib\site-packages\axelrod\tournament.py", line 129, in _build_result_set
    game=self.game)
  File "C:\Python34\lib\site-packages\axelrod\result_set.py", line 757, in __init__
    keep_interactions=keep_interactions)
  File "C:\Python34\lib\site-packages\axelrod\result_set.py", line 1031, in _build_score_related_metrics
    for match in match_chunks:
  File "C:\Python34\lib\site-packages\axelrod\result_set.py", line 889, in read_match_chunks
    with open(self.filename, 'r') as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Marcos\\AppData\\Local\\Temp\\tmpwwoqxprr'
```

As far as I can see it looks like there is some problem due to file permissions of where the temporary file was written. I've suggested giving a filename to the `play` call as a fix (hoping it will write the interactions to a place that the user has access to).

I wonder what the best fix is. 

One suggestion I see is to allow for an option in the play method `memory=True` (`False` by default) which would keep all the interactions in memory. **This would not be good for large tournaments obviously** but should be ok for smaller ones. 

This would not be complicated to do (I think?), we would just add methods to the tournament that do the same as the methods that write to file but write to an interactions dictionary that could be passed directly to the `Results` class file...

Any better ideas?

**Comment by marcharper** [comment]
Users should have access to their own temp directory. Maybe we should wait for additional reports on this one before making any changes.

**Comment by drvinceknight** [comment]
Sure :+1: (I forwarded the email to the google group)

**Comment by Ducksual** [comment]
I'm confirming this issue as well.

In [5]: results = tournament.play()
Analysing:   0%|                                                               | 0/150 [00:00<?, ?it/s]---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
<ipython-input-5-b84cada0d038> in <module>()
----> 1 results = tournament.play()

C:\Users\ducks\PycharmProjects\Axelrod\axelrod\tournament.py in play(self, build_results, filename, processes, progress_bar, keep_interactions)
    111         if build_results:
    112             return self._build_result_set(progress_bar=progress_bar,
--> 113                                           keep_interactions=keep_interactions)
    114         else:
    115             self.outputfile.close()

C:\Users\ducks\PycharmProjects\Axelrod\axelrod\tournament.py in _build_result_set(self, progress_bar, keep_interactions)
    129                                        players=[str(p) for p in self.players],
    130                                        keep_interactions=keep_interactions,
--> 131                                        game=self.game)
    132         self.outputfile.close()
    133         return result_set

C:\Users\ducks\PycharmProjects\Axelrod\axelrod\result_set.py in __init__(self, filename, progress_bar, num_interactions, players, nrepetitions, game, keep_interactions)
    795         self._build_empty_metrics(keep_interactions=keep_interactions)
    796         self._build_score_related_metrics(progress_bar=progress_bar,
--> 797                                           keep_interactions=keep_interactions)
    798
    799     def create_progress_bar(self, desc=None):

C:\Users\ducks\PycharmProjects\Axelrod\axelrod\result_set.py in _build_score_related_metrics(self, progress_bar, keep_interactions)
   1069         match_chunks = self.read_match_chunks(progress_bar)
   1070
-> 1071         for match in match_chunks:
   1072             p1, p2 = int(match[0][0]), int(match[0][1])
   1073

C:\Users\ducks\PycharmProjects\Axelrod\axelrod\result_set.py in read_match_chunks(self, progress_bar)
    927             progress_bar = self.create_progress_bar(desc="Analysing")
    928
--> 929         with open(self.filename, 'r') as f:
    930             csv_reader = csv.reader(f)
    931             repetitions = []

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\ducks\\AppData\\Local\\Temp\\tmp2863x16s'

**Comment by drvinceknight** [comment]
It seems like the problem is related to the fact that the file is still open in "w" mode and that the results set does then open in in "r" mode which windows doesn't like.

@Ducksual, @meatballs  and I have had a chat and I think there's a fix using temporary directories.
