### ISSUE TITLE
Unique ID for Player

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/Axelrod#688]
The axelrod-api project currently generates a unique id for each Player class and a dictionary with the id as its key. These could both be done within the library itself and used more widely than just the api.

The unique id is currently produced using a function which strips the whitespace from the player name and converts it to lower case. This could be done with a property in the Player class.

The dictionary mapping id to class is done using a comprehension based on the existing strategies lists and could be added to ```strategies.__init__.py```

The unique id function is currently ```strategy_id``` within https://github.com/Axelrod-Python/axelrod-api/blob/master/api/core/serializers.py

The dictionary is a class variable within https://github.com/Axelrod-Python/axelrod-api/blob/master/api/core/views.py

**Comment by marcharper** [comment]
This is a good idea. Seems like there are two concerns: human readability and uniqueness. Since some of our players have parameters, for uniqueness we'd want to do something like:
* Player name as a string + JSON of dictionary of arguments (aka init_args) as a string, and then hash the string (python's built-in `__hash__` for strings would be fine)
* For readability, we'd want exactly what you've done -- strip names of spaces or replace with underscores -- but this doesn't get the arguments, unless the player name includes the argument (like "GTFT: 0.33" does).

**Comment by meatballs** [comment]
Good catch on the parameters - I like the idea of hashing the arguments and adding to the end of the id. (I need the id to be absolutely unique)

**Comment by drvinceknight** [comment]
I don't think readability is the biggest concern of the id (we have the name for that) so 👍  for hashing. :)

**Comment by drvinceknight** [comment]
FWIW (for whoever wants to do this):

> python's built-in __hash__ for strings would be fine

@Nikoleta-v3 and I thought we might need this for a thing yesterday (we didn't in the end) and found that `__hash__` wasn't giving universal output (different hashes on different machines, same py different OS). This didn't occur when using `hashlib` it seemed to work fine (http://pythoncentral.io/hashing-strings-with-python/).

Might have of course been doing something wrong. We'll just need to make sure the tests include some hard coded ids :)

**Comment by meatballs** [comment]
I'll pick this one up.

I plan to use an md5 hash (from the hashlib module) and then the urlsafe encoding on it from the base64 module.

I may consider truncating the md5 hash to make it a little shorter - we don't have sufficient strategies for their to be much likelihood of collision.

**Comment by meatballs** [comment]
Rethink - this is intended to be an index of strategy classes which means the init_args aren't available and shouldn't be included.

**Comment by drvinceknight** [comment]
> Rethink - this is intended to be an index of strategy classes which means the init_args aren't available and shouldn't be included.

Based on conversation on the PR, is it worth investigating if it's possible to get an id for player instances? So a hash of the name and the parameters?

**Comment by meatballs** [comment]
> Based on conversation on the PR, is it worth investigating if it's possible to get an id for player instances? So a hash of the name and the parameters?

What's the use case?

**Comment by drvinceknight** [comment]
> What's the use case?

In summary: being able to generate a clone of a given player from some string representation of it.

For example:

I write the results of 2 tournaments (each with 2 different sets of 2 players) to a data set:

    ``` 
    tournament_id, player_hash, rank
    1, xyz, 1
    1, abc, 0
    2, ghl, 0
    2, qwe, 1
    ```

So now I want  to rerun those tournaments or run the winner of tournament 1 versus tournament 2 (or whatever). With the hashes `xyz` and `ghl` I could get the exact same instances of the strategies. For example perhaps `xyz` is `Random` with a probability of .85.

So this would imply that players would have a `.hash()` method that allows us to get the string representation **but** also that there was some smart 'thing' that would be able to take a hash, for example `xyz` and figure out that that's an instance of the `Random` class generated with a probability of .85. For example:

```
>>> axl.hash_to_player(`xyz`) # would return the player
```

It could just be that we hash the name and have a given symbol that never appears in the hash but that separates any parameters. (Unless I'm missing something I don't think that would be too tricky?)

For a bunch of strategies, the name already somewhat does this (or at least it's human 'readably' possible to do this) but that's not done consistently. For example some strategy instances have `Hard` or `Soft` at the start of their name based on a boolean parameter.

**Comment by meatballs** [comment]
>  With the hashes xyz and ghl I could get the exact same instances of the strategies. For example perhaps xyz is Random with a probability of .85.

I don't believe this would work. The hash function is one-way and it would be virtually impossible to  deduce that 0.85 is the required probability from the hashed value.

This is partly the reason for creating #706

**Comment by drvinceknight** [comment]
> The hash function is one-way and it would be virtually impossible to deduce that 0.85 is the required probability from the hashed value.

It would be doable if the hash was in fact a combination of a hash of the class and then some marked and then the init args.

So if `Random` had hash: `qwerty` and our 'separator' (which somehow couldn't ever appear in the class hash) was `!` then `qwerty!.2` would be the playing initiated by `Random(0.2)`.

> This is partly the reason for creating #706

That might indeed be a nicer way of doing this. We would just need to record the init_args dictionary and the name of the class (no need to hash the name of the class).

**Comment by drvinceknight** [comment]
Although actually, I've just realised, we can already do this (by this I mean my use case)! We can use the player `init_args` method :)

I suggest we close this issue and concentrate on #706  :)

**Comment by meatballs** [comment]
>
It would be doable if the hash was in fact a combination of a hash of the class and then some marked and then the init args.

So if Random had hash: qwerty and our 'separator' (which somehow couldn't ever appear in the class hash) was ! then qwerty!.2 would be the playing initiated by Random(0.2).

I started thinking about some similar schemes, but they all smell pretty nasty to me.

**Comment by meatballs** [comment]
>Although actually, I've just realised, we can already do this (by this I mean my use case)! We can use the player init_args method :)

I don't think you can. It doesn't contain any information telling you which argument means what. You have to 'know' that from somewhere else.

**Comment by meatballs** [comment]
> I suggest we close this issue and concentrate on #706 :)

That's where I've ended up.

**Comment by drvinceknight** [comment]
> I don't think you can. It doesn't contain any information telling you which argument means what. You have to 'know' that from somewhere else.

Not for the use case I described. You can do it automatically (so for the use case I suggested above), this is in fact why the player `init_args` was implemented right? 

```
>>> s = axl.Random
>>> p1 = s(.7)
>>> p1_clone = s(*p1.init_args)
>>> p1_clone
Random: 0.7
```

So if my data file had:

```
Player_class, Player_init_args
axelrod.strategies.rand.Random, (0.7,)
```

Then that could be read in and used as above.

**Comment by meatballs** [comment]
OK, yes, that would work for your use case above. It wouldn't be good enough for the API, however.

**Comment by meatballs** [comment]
In fact, it would work whenever we want to re-create a tournament that's already been previously defined.

I think we want more than that, though. We need to provide sufficient information within the class to enable it to be instantiated without reference to background information or previous instantiations.

**Comment by drvinceknight** [comment]
Yup. That's what I was talking about. I'm agreeing with you. Going to close this issue, we can reopen if necessary. :+1:
