### ISSUE TITLE
Add long run time to player classifier

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#690]
See chat on #689, idea is to add `long_run_time` to the classifier dict.  We could then change:

```
long_run_time_strategies = [MetaMajority, MetaMinority, MetaWinner,
                   MetaMajorityMemoryOne, MetaWinnerMemoryOne,
                   MetaMajorityFiniteMemory, MetaWinnerFiniteMemory,
                   MetaMajorityLongMemory, MetaWinnerLongMemory, MetaMixer]
```

to be

```
long_run_time_strategies = [s for s in all_strategies if not s.classifier['long_run_time']]
```

This could be `False` by default so we'd only need to actually add it to the `long_run_time_strategies`. All the tests are in place that should pick it up for the lists and we could add a test to the global test player class too...

**Comment by marcharper** [comment]
We should define long-run strategies somehow. I suggest we pick one strategy as the threshold, and I nominate PSO Gambler.

**Comment by drvinceknight** [comment]
Haha: I literally just pushed this using the same classification we had already in place: the meta ones. Easy enough to change though: I'm happy with whatever threshold.

**Comment by marcharper** [comment]
That's where it is already.

**Comment by drvinceknight** [comment]
Ok cool :)

If we wanted to change it, we just need to change this test and then hunt them down: https://github.com/Axelrod-Python/Axelrod/blob/master/axelrod/tests/unit/test_classification.py#L168
