### ISSUE TITLE
Strategy Filtering by Dictionary

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/Axelrod#696]
Within the api, there are a set of functions to filter strategies from their classifier entries using a dictionary. (This is because parameters within a url are passed as dictionary).

For example, the url https://axelrod-api.herokuapp.com/strategies/?stochastic=false&inspects_source=true passes the following dictionary:
```
{
    'stochastic': 'false',
    'inspects_source': 'true'
}
```
and it's then used to generate the list of strategies which satisfy those filtering criteria.

We could implement that functionality within the library itself, so that we could do something like:
```
filter = {
    'stochastic': 'false',
    'inspects_source': 'true'
}
print(axelrod.filtered_strategies(filter))
```

This wouldn't add anything that couldn't already be done with a list comprehension. The same filtering can be done already with:
```
print([[s in axl.strategies if not s.classifier[’stochastic’] and s.classifier[‘inspects_source']]))
```

However, it would add an extra capability to the library rather than it existing only within the api.

**Comment by drvinceknight** [comment]
> We could implement that functionality within the library itself, so that we could do something like:
> 
> filter = {
>     'stochastic': 'false',
>     'inspects_source': 'true'
> }
> print(axelrod.filtered_strategies(filter))
> This wouldn't add anything that couldn't already be done with a list comprehension. The same filtering can be done already with:
> 
> print([[s in axl.strategies if s().classifier[’stochastic’] and s().classifier[‘inspects_source']]))

My initial thoughts on this were negative as discussed on gitter but I think I've come around (the wonders of a 🐶  walk). I think I see how you're thinking of this now and it's a nice 'further list'. Would need to make sure it's documented at the end of http://axelrod.readthedocs.io/en/latest/tutorials/advanced/classification_of_strategies.html ("You can also directly access a filtered list blablabla kind of thing").

> However, it would add an extra capability to the library rather than it existing only within the api.

Cool. I would still like us to be selective with things (no doubt as you build the api you might find other things worth adding). So if something is useful in the api and only the api then I don't think we should pop it in the library: we don't want to add more than is needed: each tool should do it's own job well. (In this particular instance I now see the point).

**Comment by meatballs** [comment]
> the wonders of a 🐶 walk

As you may have noticed previously, I am utterly unable to think whilst sat down!

**Comment by drvinceknight** [comment]
> I am utterly unable to think whilst sat down!

My biggest problem is that I am sadly completely able to open my big dumb mouth before thinking.

**Comment by meatballs** [comment]
> My biggest problem is that I am sadly completely able to open my big dumb mouth before thinking.

Ah well, that applies to at least half our core team, then.

**Comment by marcharper** [comment]
@meatballs I'm a fan of this -- convenient and easy for newcomers and a nicer syntax versus comprehensions of a loop.
