### ISSUE TITLE
Include method to write a summary data set to file

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#701]
The results set used to have a method to write some output to csv. The output was a mid way point between the interactions and a summary (it held the total score of each strategy for each repetition).

As we now have all the interactions written by default I suggest adding a method to the results set that gives a very quick summary data set. Here is the function that I have in mind (would move it to a method of the result set):

```
import axelrod as axl
from numpy import median
from collections import namedtuple
import csv

def summary_data(results, filepath=None):
    """
    Obtain summary of performance of each strategy: 
    ordered by rank, including median normalised score and cooperation rating.
    
    Parameters
    ----------
    
        results : axelrod.results 
        filepath : a filepath to which to write the data
        
    Output
    ------
    
        A list of the form:
        
        [[player name, median score, cooperation_rating],...]
        
        If `filepath` is passed then a summary data file with the following headers will be written:
        
        "Rank", "Name", "Median-score-per-turn", "Cooperation-rating"
    """
    
    median_scores = map(median, results.normalised_scores)
    player = namedtuple("Player", ["Rank", "Name", "Median_score", "Cooperation_rating"])    

    summary_data = [perf for perf in zip(results.players, median_scores, results.cooperating_rating)]
    summary_data = [player(rank, *summary_data[i]) for rank, i in enumerate(results.ranking)]
    
    if filepath is not None:
        with open(filepath, 'w') as csvfile:
            writer = csv.writer(csvfile)
            writer.writerow(player._fields)
            for player in summary_data:
                writer.writerow(player)
    
    return summary_data
```

This would give:

```
>>> axl.seed(0)
>>> players = [s() for s in axl.demo_strategies]
>>> tournament = axl.Tournament(players)
>>> results = tournament.play()
>>> sd = summary_data(results, "test.csv")
>>> sd
[Player(Rank=0, Name='Defector', Median_score=2.4924999999999997, Cooperation_rating=0.0),
 Player(Rank=1, Name='Grudger', Median_score=2.4900000000000002, Cooperation_rating=0.503875),
 Player(Rank=2, Name='Tit For Tat', Median_score=2.308125, Cooperation_rating=0.62675),
 Player(Rank=3, Name='Cooperator', Median_score=1.869375, Cooperation_rating=1.0),
 Player(Rank=4, Name='Random: 0.5', Median_score=1.8218750000000004, Cooperation_rating=0.495125)]
```

and `tmp.csv` would have:

```
Rank,Name,Median_score,Cooperation_rating
0,Defector,2.4925,0.0
1,Grudger,2.49,0.503875
2,Tit For Tat,2.308125,0.62675
3,Cooperator,1.869375,1.0
4,Random: 0.5,1.821875,0.495125
```

This data file would always have 4 columns and as many rows as players in the tournament (so it would not be a big file). Definitely a method and only called if needed: would add this dataset as output available on the tournament repo.

The code is all there, if we think it's a good idea, I can easily throw a PR together.

**Comment by drvinceknight** [comment]
Perhaps also add a column for `Wins`.

**Comment by marcharper** [comment]
How do you feel about a method that makes the standard plots? Essentially I'm suggesting that we move `obtain_assets` from the tournament repository into the axelrod repository.

I think it would also be good to have a standard output data frame function, with columns for each strategy, much like what I did for my blog posts (and in the examples repository).:
* wins
* mean score
* std score
* percent cooperation
* percent CC, CD, DC, DD
* and so on

These two things, together with the summary data set, greatly reduces the friction to using the library for research purposes. And with the API work by @meatballs, we may soon be in a situation where a user can specify a tournament via the web and receive a zip file with a summary analysis, a dataframe, and a collection of plots. How cool would that be?

**Comment by drvinceknight** [comment]
> How do you feel about a method that makes the standard plots? Essentially I'm suggesting that we move obtain_assets from the tournament repository into the axelrod repository.

Yeah sounds good.

> 
> I think it would also be good to have a standard output data frame function, with columns for each strategy, much like what I did for my blog posts (and in the examples repository).:
> 
> wins
> mean score
> std score
> percent cooperation
> percent CC, CD, DC, DD
> and so on

Any reason why the columns for each strategy as opposed to the way I'm suggesting? Rows for strategies sorted by rank which I feel makes it nicely readable.

For percent cooperation, CC, CD etc this would add more calculations to the result set.

**Comment by marcharper** [comment]
> Any reason why the columns for each strategy as opposed to the way I'm suggesting? Rows for strategies sorted by rank which I feel makes it nicely readable.

Just including features that I've found useful, we can also add on to the columns later.

**Comment by drvinceknight** [comment]
> Just including features that I've found useful, we can also add on to the columns later.

My question isn't about the features but why the strategies as columns (as opposed to strategies as rows as per my initial suggestion)? It's not anything I'm against, I'm just curious as to what the reason is.

**Comment by marcharper** [comment]
Oh, that was just a typo, sorry!

**Comment by drvinceknight** [comment]
Ah cool :)

So yeah: I'm in favour of your suggestion: I think it's what I was suggesting with more things added to the result set (which after the re write is so fast anyway, it's probably not too bad a thing).

**Comment by drvinceknight** [comment]
Have opened #708
