### ISSUE TITLE
Fix citation link in documentation

### ISSUE THREAD

**Issue by theref** [Axelrod-Python/Axelrod#709]
Browsing through the documentation i noticed that the link on [this](https://axelrod.readthedocs.io/en/latest/citing_the_library.html) page causes a 404 error.

Instead of pointing at `https://github.com/Axelrod-Python/Axelrod/blob/master/CITATION.txt` I think it should point to `https://github.com/Axelrod-Python/Axelrod/blob/master/CITATION.rst`.

This could be nice beginner issue for anyone who comes to the sprint at PyCon.

**Comment by drvinceknight** [comment]
Thanks: have labelled. 👍
