### ISSUE TITLE
Need to improve documentation for strategy test functions

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#726]
I am not the biggest fan of our strategy test functions (`test_responses` etc...). I feel they make the tests too implicit and often find myself rewriting things explicitly to try and find errors etc... (For example see: https://github.com/Huaraz2/Axelrod/pull/1/commits/4b62612d692c82cf6259bc21bb946f5d27ade4cf).

One person from the PyConUK sprints mentioned that they found them hard to use and that they could be better documented. 

Could we improve the documentation: http://axelrod.readthedocs.io/en/latest/tutorials/contributing/strategy/writing_test_for_the_new_strategy.html Perhaps including more "this is equivalent to ..." and/or say explicitly that you do not need to use them? 

On a similar vain is `markov_test` a good name? It implies stochasticity to me but it's just a referral to the states of the common markov chain right?

**Comment by marcharper** [comment]
`test_markov` isn't a good name (that's on me). It's really just a test of how the player behaves in the four possible first contexts CC, CD, DC, and DD, and is the logical follow up to the first play test. Something like `second_plays_test` is a better name.

I think we could definitely improve the docs for using the `attrs` parameter for `responses_test` -- it's powerful and should be used more.

**Comment by drvinceknight** [comment]
> Something like second_plays_test is a better name.
> 
> I think we could definitely improve the docs for using the attrs parameter for responses_test -- it's powerful and should be used more.

Sounds good to me.

**Comment by drvinceknight** [comment]
This was closed by #820
