### ISSUE TITLE
Human Strategy

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/Axelrod#728]
A strategy that presents the history of a match in the terminal and prompts for keyboard input rather than deriving its own action.

**Comment by drvinceknight** [comment]
👍  Big fan of this idea.

**Comment by drvinceknight** [comment]
@marcharper not for research obviously (?) although a lovely little thing to bring up for outreach/teaching activities.

**Comment by meatballs** [comment]
There is a basic working version of this now on branch issue-728.

Stuff left to think about:
- [ ] How to test it
- [ ] How to make the screen printing prettier
- [ ] What to do about having to play against yourself in a tournament

**Comment by marcharper** [comment]
Very nice idea @meatballs !

**Comment by Huaraz2** [comment]
>  What to do about having to play against yourself in a tournament

@meatballs could you set it such that at the start of the first turn for the human strategy you have to input your name and then that way you could differentiate between the two human strategies. Not sure how you could test this though

**Comment by meatballs** [comment]
@Huaraz2 It's already doing that!

**Comment by Huaraz2** [comment]
@meatballs ah ok wasn't sure as I haven't had time to have a play with it, what is the problem when it plays itself then at the moment?
