### ISSUE TITLE
Add docstring requirements to contribution guidelines

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/Axelrod#729]
One comment at the PyCon UK sprint was that it's not clear from our guidelines that we expect numpy style docstrings for methods and functions.

We do have #347 to clean up our existing codebase, but we've not been explicit in our expectations for new code.

**Comment by drvinceknight** [comment]
👍  (Just an FYI for whoever works on this, the numpy guideline does not extend to strategies for which numpy style `----` etc under section headings breaks the autodoc as it conflicts with the rst syntax).
