### ISSUE TITLE
Track CC, CD, DC, DD in player class 

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#744]
Currently we track cooperations and defections for efficiency for several strategies. Some strategies also use the context counts, so we might consider doing the same for these as well. See [Retaliator](https://github.com/Axelrod-Python/Axelrod/blob/master/axelrod/strategies/retaliate.py for an example.

**Comment by mturzanska** [comment]
Could I work on this one?

**Comment by drvinceknight** [comment]
> Could I work on this one?

Please do!

**Comment by drvinceknight** [comment]
Cosed by #752
