### ISSUE TITLE
Short and Long Run-time strategies

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#771]
I'd like to add a few more meta strategies to the library, such as MetaWinners for the collections of stochastic and deterministic strategies. I do not, however, want to add more long run time strategies, since we've already got several and they take up the vast majority of the run time (especially against each other).

So I'd like to propose that we leave out the long run time strategies from the default collection of strategies, or at least add a prominent collection of "short run time" strategies:
```
fast_strategies = [s for s in all_strategies if obey_axelrod(s())
                           and not s().classifier['long_run_time']]
```

This is because I don't think new comers to the library will necessarily be aware that there are long time strategies that take up a lot of run time.

**Comment by drvinceknight** [comment]
My preference would be to add `short_run_time`. I think leaving the
`strategies` as is is important to do.

If only for backwards compatibility, but also, the risk of newcomers not
knowing that there's another set of valid strategies elsewhere is in my
opinion worse than that they might have some tournaments that run for a
while. The status quo of: all 'valid' strategies are in `strategies` and
they can be further obtained using the filters is a good way of doing
things.

I think that in practice, if anyone were to run something on the full set
of strategies I think they would expect a long time anyway (and they would
perhaps have enough experience to deal with the filtering).

But I think having a helper list of `short_run_time ` strategies is a good
idea. We always said that we could keep adding these shortcut lists :)
