### ISSUE TITLE
Add ability to pass more options to plot objects

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#776]
axis labels for example (this came up on gitter).

**Comment by marcharper** [comment]
If we give access to the underlying matplotlib axes object then users can modify plots however they like. I do this in my ternary plotting library with a wrapper object, see [here](https://github.com/marcharper/python-ternary/blob/master/ternary/ternary_axes_subplot.py).

**Comment by drvinceknight** [comment]
That sounds ideal.

**Comment by drvinceknight** [comment]
@Nikoleta-v3 this could be a nice one to pick up if you wanted it.

**Comment by Nikoleta-v3** [comment]
Will do!
