### ISSUE TITLE
Expand Default Tournment

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#780]
We have a lot of parameterized strategies, it would be nice to include some variants in our standard tournament, such as:
* Random(0.9)
* Random(0.3)
* GTFT(0.1)

and also to take better advantage of the strategy transformers. We have a lot of "cooperative" strategies and it would be good to have more of a mix.

**Comment by drvinceknight** [comment]
Sure, we could add in a few, with the strategy transformers we could potentially add a transformed version of every strategy... (This would swiftly increase the size of our tournament).

As well as those three, do you have any other suggestions (I could add them all in for the next tournament run I do)?

**Comment by marcharper** [comment]
I don't have a big list but more variation is good. I'd like to have more random strategies, or just to take advantage of our parametrized strategies. With the new meta strategies there are a lot of "cooperative" strategies and maintaining a diverse collection is healthy.

**Comment by drvinceknight** [comment]
I'll put something together on the next run/release. We can always add more
after. :)  :+1:

**Comment by drvinceknight** [comment]
Have just pushed new results with 8 extra strategies. You can see this in the `player.py` script in the tournament repo <https://github.com/Axelrod-Python/tournament/blob/gh-pages/players.py>:

```
# Include a list of parametrized strategies
parametrized_players = [axl.Random(0.1),
                        axl.Random(0.3),
                        axl.Random(0.7),
                        axl.Random(0.9),
                        axl.GTFT(0.1),
                        axl.GTFT(0.3),
                        axl.GTFT(0.7),
                        axl.GTFT(0.9)]

players = [s() for s in axl.strategies] + parametrized_players
players.sort(key=lambda p:p.__repr__())
```

I'm going to close this issue, but we can add more there :)
