### ISSUE TITLE
Random strategy does not change it's classification

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#781]
We need to include something similar to the setup in memory one strategies that overwrite the stochastic classifier upon initialisation:

```
>>> p1 = axl.Random(0)
>>> p2 = axl.Random(1)
>>> p1.classifier['stochastic'], p2.classifier['stochastic']
(True, True)
```

Mildly connected to #779 (found it whilst working on that).

**Comment by marcharper** [comment]
Good catch
