### ISSUE TITLE
Python 3.6

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#798]
Python 3.6 was released over the Christmas break (https://docs.python.org/3/whatsnew/3.6.html).

We have discussed "supporting the latest two versions of py3" as a general policy. 

On a branch ([`py3.6`](https://github.com/Axelrod-Python/Axelrod/commits/py3.6)) I've pushed the simple change to our travis build config: removing py 3.4 and adding py 3.6 (and a minor doctest compatibility fix).

One of the motivations for dropping 3.4 is that we can tackle #347 by using type annotations (which are available in both 3.5 and 3.6 but **not** 3.4).

Assuming that's all fine, I'll open a PR with that branch but one **question**: what do we do with releases (`x.y.z`)? I would be happy to simply bump `y`.

FYI, here's the travis build with 3.5 and 3.6: https://travis-ci.org/Axelrod-Python/Axelrod/builds/187938394

CC: @marcharper @meatballs 

:) :+1:

**Comment by marcharper** [comment]
Sounds good to me. We should also look into using [enums](https://docs.python.org/3/library/enum.html), introduced in Python 3.4, and a sweep of the library removing anything keep around for Python 2.7 compatibility.
