### ISSUE TITLE
History class

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/Axelrod#806]
I added a preliminary implementation of a history class [here](https://github.com/Axelrod-Python/Axelrod/blob/history_class/axelrod/history.py). I'm curious for feedback @meatballs @drvinceknight before I progress any further. The idea is that by abstracting the history into a class we can:

* compute features in the history class rather than having strategies duplicate it
* enforce some boundaries between the player class and the history (like having the history store its cooperation counts rather than as attributes in the player class)
* opens up experimentation for the history to be implemented as a string, bitvector, integer, etc. for computational and memory efficiency

I'm also thinking about a joint history class (storing the match history) so that the state distribution and other features can be encapsulated, scoring could act on the joint history, etc. We could make some of the strategy methods into staticmethods if each player has a copy of the joint history.

**Comment by drvinceknight** [comment]
Sounds good to me.

**Comment by marcharper** [comment]
I'm going to close this one. If anyone wants to attempt this in the future feel free to reopen. My implementations had a big performance hit for e.g. copying shared histories in the metaplayers.
