### ISSUE TITLE
Discussing the dynamically created classes

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#845]
The dynamically created classes are creating very minor issues with type checking (and also causing slight issues with hashing in the fingerprinting repo but that's not a big deal). Is it worth perhaps revisiting whether or not they are necessary?

Perhaps we could include the data in the corresponding modules themselves (as a class attribute for each given class). This has the negative side effect of a bit more manual work to update the classes but it simplifies things (like with type checking and also removes the need for the `read_data` module).

Any thoughts?

**Comment by marcharper** [comment]
Dynamic generation isn't necessary, though it could be useful in some situation. We can leave the data loading as is and just name the classes explicitly.

**Comment by drvinceknight** [comment]
> Dynamic generation isn't necessary, though it could be useful in some situation. 

Is there a particular situation you have in mind? 

> We can leave the data loading as is and just name the classes explicitly.

Good idea, it will keep things a bit tidier. I'm happy to have a go at this.

**Comment by marcharper** [comment]
If you wanted to study a tournament of randomly generated FSM strategies, for instance, it would be a huge pain to do if the classes were not dynamically generated. So if we remove that example from the main library, an advanced tutorial would be nice.

Also, before you remove those guys I'd check that the strategy transformers don't cause the same problem

**Comment by drvinceknight** [comment]
> If you wanted to study a tournament of randomly generated FSM strategies, for instance, it would be a huge pain to do if the classes were not dynamically generated. So if we remove that example from the main library, an advanced tutorial would be nice.
> 

I might be missing something but could this not be taken care of using inheritance from a parent FSM class? (like for the simpler memory one strategies for example)

> Also, before you remove those guys I'd check that the strategy transformers don't cause the same problem

Yeah, I was thinking that the PR should change travis to run `mypy` on everything anyway so it would see what this catches (or doesn't).

**Comment by marcharper** [comment]
Yeah maybe there is an easier way if the base strategies are parameterized, so maybe my example isn't very good.
