### ISSUE TITLE
Refactor all strategy tests

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#884]
With the merge of #875 we have a new method for testing strategies called `versus_test` (http://axelrod.readthedocs.io/en/latest/tutorials/contributing/strategy/writing_test_for_the_new_strategy.html). The goal is for this to eventually replace the currently used `responses_test`.

This will take a slow refactor of all strategy tests. Ideally any PRs towards this issue should only do a small number of modules at a time to ensure that nothing is missed during the review process.

EDIT: Once all of these are complete, we can refactor the `TestPlayer` class to remove unused methods.

**Comment by alajara** [comment]
Hi I would like to help with this. Its my first contribution, any guidance how to start, I will much appreciate it.

**Comment by drvinceknight** [comment]
Hi @alajara, welcome!

We have introduced a new testing framework for strategies, you can read about this here: http://axelrod.readthedocs.io/en/latest/tutorials/contributing/strategy/writing_test_for_the_new_strategy.html

So this issue is about rewriting the various tests that have already been written for strategies using the new framework.

Here are some PRs that I've written that do this:

- https://github.com/Axelrod-Python/Axelrod/pull/893/files
- https://github.com/Axelrod-Python/Axelrod/pull/909/files
- https://github.com/Axelrod-Python/Axelrod/pull/914/files

So the idea is to look at the files in `axelrod/tests/strategies/` and modify them as you can see in those PRs. 

I've assumed there that you're ok with the notion of automated testing but please let me know if you're not and I'd be happy to walk you through anything/everything :)

To help coordinate (I'm slowly working on these myself) perhaps once you're ready to go, comment on this issue when you start working on a particular test file (just so we don't work on the same one). Also, to help keep the reviews simple: let's stick to just one file per PR.

Let me know if anything I've said is unclear :) Looking forward to your first contribution!

**Comment by alajara** [comment]
Hey Mr. Knight,


Thank you for the email response explaining how to get started. A little background on me, I recently got out of the military, 6 years , and this past year I have been attending college for Computer Systems and have been learning Python and Java.  I have been doing different types of projects to teach myself more and i have gotten to the point where I can read and write my own code. I still have a lot of work and things to learn, but I am motivated.  Again sir thank you for the opportunity to help, as soon as I have a chance today, I will get started.



Best

Armando, Lajara

________________________________

**Comment by eric-s-s** [comment]
Hello Dr Knight,

I'm also interested in helping with this.  should i simply write a comment on which strategy i'm doing? This is my first time contributing to someone else's project.  while trying to understand the process, i came across a possible issue with backstabber.py  The DoubleCrosser class does not follow its documentation and the test to demonstrate it doesn't seem to do anything. i'm not sure if this is the appropriate place for this, but here are code snippets.

backstabber.py 
`
@FinalTransformer((D, D), name_prefix=None) # End with two defections
class DoubleCrosser(Player):
    """
    Forgives the first 3 defections but on the fourth
    will defect forever. If the opponent did not defect
    in the first 6 rounds the player will cooperate until
    the 180th round. Defects on the last 2 rounds unconditionally.
    """
    def strategy(self, opponent: Player) -> Action:
        cutoff = 6

        if not opponent.history:
            return C
        if len(opponent.history) < 180:
            if len(opponent.history) > cutoff:
                if D not in opponent.history[:cutoff + 1]:
                    if opponent.history[-2:] != [D, D]:  # Fail safe
                        return C
        # a quick refactor so i can see what the author meant (not, i think, what was intended)
        # if cutoff < len(opponent.history) < 180:
        #     first_seven = opponent.history[:cutoff + 1]
        #     last_two = opponent.history[-2:]
        #     if D not in first_seven and last_two != [D, D]:
        #         return C
`
the test strategy doesn't seem to show this.  here's from test_backstabber.py 
`
        # If opponent did not defect in the first six rounds, cooperate until
        # round 180
        self.responses_test([C] * 174, [C] * 6, [C] * 6, length=200)
        self.responses_test([C] * 160, [C] * 12, [C] * 6 + [D] + [C] * 5,
                            length=200)
`
if i understand these tests correctly, DoubleCrosser will always return C vs a MockPlayer who always returns C (except for one D in round 7 on the second test).  This is no different from the other class BackStabber.

-Eric Shaw

**Comment by uglyfruitcake** [comment]
Hi @eric-s-s,
Welcome to the Axelrod-Python Project!
I'm Tom the original author of Backstabber and Doublecrosser. 
The current code for Doublecrosser is very old and was written when I was very new to Python. As far as I can tell your refactor does do exactly the same thing (and in a much more elegant way).
You say that due to the tests you have shown, Backstabber and Doublecrosser do the same thing. From the situation described in the tests, they are supposed to. The difference between the two strategies should only come to light when an opponent did not defect in the first 6 turns and then subsequently defects more than 3 times (not consecutively). In this very specific situation, Doublecrosser will continue to cooperate whereas Backstabber will register the 4 defects and defect in response.
The tests that you showed did not highlight this situation and hence made it look like they were doing the same thing (which in that situation they are).
Hope this helps to clear things up!
Tom.

**Comment by alajara** [comment]
Hey Dr. Knight I can begin working on worse and worse, if it's open.

**Comment by eric-s-s** [comment]
@uglyfruitcake excellent.  thank you very much.  while i'm changing from self.response_test to self.versus_test i'll put that test situation in there.  just to confirm for DoubleCrosser 

opponent = 6 * [C] + 4 * [D]  -> next move (and all other moves or will it revert if opponent cooperates?) = D
opponent = 6 * [C] + [D, C, D, D, D] -> next move = C
opponent = 6 * [C] + [D, C, D, D, D] + 171 * [C] -> next move = D

**Comment by uglyfruitcake** [comment]
@eric-s-s 

Not quite. Here's what the tests should be I think.

6 * [C] + 2 * [D] -> D
6 * [C] + 20* [D] -> D
6 * [C] + 2 * [D] + [C] - > C
6 * [C] + 20 * [D] + [C] - > C

Between round 7 - 180 it will only defect if the previous 2 were [D, D]. Nothing else is relevant. 

After 180 rounds it is EXACTLY like Backstabber. No difference.

Hope that helps.

Tom

**Comment by marcharper** [comment]
Since there are several people working on this issue please just state here which strategies you are handling. Feel free to get started wherever you like and open a PR when you think you are ready to merge.

**Comment by eric-s-s** [comment]
@uglyfruitcake that is clear.  thank you.  If you don't mind, i'll refactor backstabber.py in the process.

-eric

**Comment by eric-s-s** [comment]
working on backstabber

@uglyfruitcake thank you.  please review the PR i'll post later.  DoubleCrosser had an off-by-one error.  so i ?fixed? it and did a little refactor.

@marcharper sorry.  i am new to all this, so i'm not sure where/how to raise the issue of test coverage/bug on a specific strategy.  is there a protocol for doing so?

**Comment by drvinceknight** [comment]
> @marcharper sorry. i am new to all this, so i'm not sure where/how to raise the issue of test coverage/bug on a specific strategy. is there a protocol for doing so?

@eric-s-s you can just go ahead and address it in the PR under this issue (no need for a new issue). We'll discuss anything relevant on the PR itself :)

**Comment by drvinceknight** [comment]
> Hey Dr. Knight I can begin working on worse and worse, if it's open.

Please do @alajara! :)

**Comment by eric-s-s** [comment]
#924

**Comment by eric-s-s** [comment]
i'll work on the b's and c's.
better_and_better
calculator
cooperator
cycler

**Comment by eric-s-s** [comment]
i'll start on the D's
darwin
defector
doubler

**Comment by alajara** [comment]
I opened a PR on worse and worse, it was my first PR, if I made any mistake please let me know and I will correct it. Thanks.

**Comment by ebeweber** [comment]
Attempted strategies.very_bad here: https://github.com/Axelrod-Python/Axelrod/pull/928

**Comment by alajara** [comment]
doing shortmem, stalker, selfsteem

**Comment by eric-s-s** [comment]
finished so far (or being worked on)

- test_a* to test_d*
- test_headsup
- test_inverse
- test_rand
- test_s* to test_w* but NOT test_sequence_player

are these finished? they have no responses_test but also no versus_test

- test_hmm
- test_human
- test_mindcontrol
- test_mindreader
- test_negation
- test_qlearner
- test_random

**Comment by marcharper** [comment]
We're trying to test as much as possible with actual opponents (Cooperator, Defector, Alternator, etc.) so feel free to add tests if it seems appropriate.

**Comment by eric-s-s** [comment]
starting next four:
finite_state_machine
forgiver
gambler
geller

**Comment by MariosZoulias** [comment]
I would like to take the mutual.py ;)

**Comment by eric-s-s** [comment]
working on

lookerup.py

it's connected to gambler.

**Comment by eric-s-s** [comment]
next up. finish "g"

gobymajority
gradualkiller
grudger
grumpy

**Comment by drvinceknight** [comment]
I'm picking up handshake :)

**Comment by drvinceknight** [comment]
Picking up `sequence_player`.

**Comment by drvinceknight** [comment]
Picking up `test_retaliate`

**Comment by drvinceknight** [comment]
Picking up `test_qlearners`.

**Comment by drvinceknight** [comment]
Picking up `test_punisher`.

**Comment by drvinceknight** [comment]
Picking up `test_prober`.

**Comment by drvinceknight** [comment]
Picking up `test_oncebitten`.

**Comment by drvinceknight** [comment]
Picking up `test_negation`.

**Comment by drvinceknight** [comment]
My bad: nothing to be done for `test_negation`.

**Comment by drvinceknight** [comment]
Picking up `test_meta`

**Comment by drvinceknight** [comment]
Picking up `test_mathematicalconstants`.

**Comment by drvinceknight** [comment]
Picking up `test_memorytwo`.

**Comment by drvinceknight** [comment]
Picking up `test_memoryone`.

**Comment by drvinceknight** [comment]
Picking up `test_hunter`.

**Comment by drvinceknight** [comment]
I believe #1035 might be the last of them. Will wait to adjust as required and get them all merged before taking stock :+1:

**Comment by drvinceknight** [comment]
All the strategy tests have been refactored. I'm going to refactor some of the boiler plate code in `test_player` to remove what is no longer needed. We still use `responses_test` for `first_play_test` and `second_play_test` but I'll take a look at if anything can be simplified there. That should close this issue.

**Comment by drvinceknight** [comment]
Thanks to everyone for your efforts on this! Closed by #1036
