### ISSUE TITLE
Implement an `__eq__` method for players

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#885]
A way to test equality of players. This should not only check the class, str but also that all attributes are equal.

That sort of check is currently used in the `TestPlayer` class so as well as implemented an `__eq__` metho a very minor refactor of the `TestPlayer` class can be carried out.

**Comment by YetiYetYet** [comment]
Can i try to do it ?

> drvinceknight : Of course you can do it.

Thanks bro.

**Comment by drvinceknight** [comment]
?

**Comment by YetiYetYet** [comment]
So, with a **lot of love** i do this : 

```
    def __eq__(self, other):
        #This method checks that all the attributes of `self` and `other`
        for attribute, reset_value in self.__dict__.items():
            original_value = getattr(other, attribute)

            if isinstance(reset_value, np.ndarray):
                if not (np.array_equal(reset_value, original_value)):
                    return False
            elif isinstance(reset_value, types.GeneratorType):
                for _ in range(10):
                    if next(reset_value) != next(original_value):
                        return False
            else:
                if reset_value != original_value:
                    return False

        if str(self) != str(other):
            return False

        if str(self) in ["Darwin", "Human"]:
            # Known exceptions
            return True

        turns = 50
        r = random.random()
        for op in [axelrod.Cooperator(), axelrod.Defector(),
                   axelrod.TitForTat(), axelrod.Random(r)]:
            self.reset()
            other.reset()
            seed = random.randint(0, 10 ** 6)
            for p in [self, other]:
                axelrod.seed(seed)
                m = axelrod.Match((p, op), turns=turns)
                m.play()
            if not self.history == other.history:
                return False 
        return True
```

When i try it, it's work, it's make me feel verry happy. But there is still a problem.
I need to import all Axelrod or it's doesn't work. I mean :
```
        for op in [axelrod.Cooperator(), axelrod.Defector(),
                   axelrod.TitForTat(), axelrod.Random(r)]:
```
These strategies need the player class and i can't import just the strategies.
So my spirit say "You should use a mock_player" and i said to my spirit "Ho yes, i will try to use it !"
But Axelrod say : "No, mockplayer use player too" and he broke my Heart.

Do you have an idea for making the code cleaner and use a method who doesn't need player and purge this import axelrod ?

By the way :
In test_player for test it i do this (And it's work !) :
```
    def test_equal(self):
        player1 = TitForTat()
        player2 = Cooperator()
        player3 = Defector()
        self.assertEqual(player1, player1)
        self.assertNotEqual(player1, player2)
        self.assertNotEqual(player1, player3)
```
Also I remove the import axelrod, and import only the needed import and change all method:
```
from axelrod import Match, DefaultGame, MockPlayer, Player, simulate_play
from axelrod import seed as axlseed
from axelrod.strategies import TitForTat, Cooperator, Defector, Random
from axelrod.actions import Actions
```
And it's work !

_I know what you think after you read this : "omg RIP English"_

**Comment by drvinceknight** [comment]
Hi @YetiYetYet thanks for your efforts but here is the kind of thing that is required for this PR:

```
    def __eq__(self, other):
        """
        Test if two players are equal.
        """
        check = self.__repr__() == other.__repr__()
        for attribute, value in self.__dict__.items():
            other_value = getattr(other, attribute)

            if isinstance(value, np.ndarray):
                check = check and np.array_equal(value, other_value)

            elif isinstance(value, types.GeneratorType) or isinstance(value, itertools.cycle):
                check = check and all(next(value) == next(other_value)
                                      for _ in range(10))
            else:
                check = check and value == other_value
        return check
```

As you can see there I'm doing this:

> That sort of check is currently used in the TestPlayer class so as well as implemented an __eq__ metho a very minor refactor of the TestPlayer class can be carried out.

and just lifting the things out of the `TestPlayer`. 

I see that in your attempt you're actually trying to test if the players do the same thing, I'm afraid that's a completely different problem and not one we're trying to solve here. Here we just want to know if they're of the same class and have all the same values for their attributes.

The code I've written above is more or less what is needed. For this issue you should:

- Implement that in the player class;
- Include some tests;
- If possible refactor the `TestPlayer` to be remove the checks currently being undertaken there and replace them with simple equality between two players after a reset.

**Comment by drvinceknight** [comment]
(My code snippet can improved by doing what you were doing which is returning `False` when it first occurs otherwise returning `True` at the end.)
