### ISSUE TITLE
Bug and Testing of plot.py

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/Axelrod#894]
There is no unit test for the `default_cmap` function and, as a result, there's a bug in the case of matplotlib not being installed.

The coverage report is also showing several other lines in `plot.py` which are not covered by tests.

**Comment by meatballs** [comment]
Also a bug if matplotlib version is 2.0 or greater

**Comment by meatballs** [comment]
I could do with some help on this one as I don't know matplotlib terribly well.

There are two similar lines which are covered by tests: 51 and 221. They both deal with axes being passed to the plot but we only ever call the functions with that parameter set to None.

Could somebody add to this PR with whatever is needed in test_boxplot to specify ax properly and test the result?

**Comment by drvinceknight** [comment]
> Also a bug if matplotlib version is 2.0 or greater

Could you give some more details about this: I'm running matplotlib 2.0 and tests pass (on master). What's the issue here?

**Comment by drvinceknight** [comment]
> There are two similar lines which are covered by tests: 51 and 221. They both deal with axes being passed to the plot but we only ever call the functions with that parameter set to None.

Have opened #896 about those.

**Comment by drvinceknight** [comment]
That's fixed on this branch I believe @meatballs: 90be7caad1e8ee343389fa82baccf92cedc6d526

**Comment by meatballs** [comment]
> Could you give some more details about this: I'm running matplotlib 2.0 and tests pass (on master). What's the issue here?

The tests pass because there is no test for the default_cmap function.

If you start to write a test, you discover that the existing function has two problems:

1) It hits matplotlib internally, so it crashes if matplotlib is not installed
2) The existing condition looks for major version >= 1 AND minor version >=5, and so fails for 2.0-2.4
