### ISSUE TITLE
Should Player class dynamically add init arguments in name ?

### ISSUE THREAD

**Issue by Chadys** [Axelrod-Python/Axelrod#920]
Following discussion started at Axelrod-Python/Axelrod#802 :

 >**Chadys commented 14 hours ago • edited** 
>Instead of making it the strategy responsibility to change its __repr__ method according to its parameters like Random does, wouldn't it be more efficient to change Player.__repr__ to something like this :
>
>```python
>def __repr__(self):
>     name = self.name
>     sig = inspect.signature(self.__init__)
>     prefix = ': '
>     for param in sig.parameters:
>         if param != 'self':
>             name += prefix+str(getattr(self,param, ''))
>             prefix = ', '
>     return name
>```
>Tested on Random, returns Random: 0.5
>
>**marcharper commented 8 hours ago**
>
>Interesting idea! For some strategies this could produce very long names depending on the parameters. I think we need to check that this produces good results for all strategies. We'd also need to document the automatic name generation and give instructions on how to override.
>
>I recommend rewriting the function a bit to use the stored __init__ parameters that Player.__new__ places in self.init_args and self.kwargs, which I think eliminates the need for inspect in this case. The parameter extraction should have already been done before __repr__ is called. We should also probably check that class.name makes sense for unsubstantiated players.
>
>**drvinceknight commented 6 hours ago**
>
>    Interesting idea! For some strategies this could produce very long names depending on the parameters. I think we need to check that this produces good results for all strategies. We'd also need to document the automatic name generation and give instructions on how to override.
>
>I really like this idea and @marcharper's suggestions too. :+1:
>
>**Chadys commented an hour ago**
>
>Using self.init_args is even better yes, but it only store the specified parameters we use to call the constructor ; so, not default ones. So we need to choose if the expected behavior is to have __repr__ of Random() return "Random" and __repr__ of Random(0.5) return "Random: 0.5" , or if we want "Random: 0.5" for the first one also. Then we'd need to use inspect or to store also default arguments in self.init_args, but right now I don't see a good way to do that since __new__ only receive the parameter we specify.

**Comment by drvinceknight** [comment]
@Chadys I think it's ok to keep this discussion in #802, I'm going to close this issue (so that the discussion doesn't fragment) but if I've misunderstood something we can reopen.
