### ISSUE TITLE
Delete parameters from GoByMajority variants

### ISSUE THREAD

**Issue by Chadys** [Axelrod-Python/Axelrod#921]
For all the GoByMajority variants, I don't think we should have parameters. Because, for example, if you call `HardGoByMajority5(10, True)`, it's not a `HardGoByMajority5` anymore but a `GoByMajority10`. I suggest that only GoByMajority should have parameters, and the variants should only call GoByMajority with their defining parameters. If that's ok, I'll make the modification.

**Comment by drvinceknight** [comment]
Seems sensible to me. Please open a PR :) :+1:

**Comment by drvinceknight** [comment]
Closed by #922
