### ISSUE TITLE
Remove init_args

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/Axelrod#945]
Now that all strategies are using kwargs instead of args, we can remove init_args from the Player class.

**Comment by Chadys** [comment]
But that means that a user of Axelrod won't be able to use `clone` if they instantiated a player like this `axl.Random(0.5)` ?

**Comment by Chadys** [comment]
But that means that a user of Axelrod won't be able to use `clone` if they instantiated a player like this `axl.Random(0.5)` ?

**Comment by meatballs** [comment]
Yes - they would have to use `axl.Random(p=0.5)`

**Comment by drvinceknight** [comment]
> Yes - they would have to use axl.Random(p=0.5)

Which is more verbose :+1: :)

**Comment by drvinceknight** [comment]
Although it's not ideal if you can create the player but then it won't run/work... We should think about a good error message of some sort. Perhaps even in the init itself?

**Comment by Chadys** [comment]
I though the same thing, if you only permit the use of kwargs (for which I am still skeptical but no matter), the init should fail if args isn't empty

**Comment by drvinceknight** [comment]
This might be relevant:

```
>>> def foo(*, bar=False):
...    print('foo')
>>> foo(5)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-221-7ac5ef7ffdb6> in <module>()
----> 1 foo(5)

TypeError: foo() takes 0 positional arguments but 1 was given
```

**Comment by drvinceknight** [comment]
Question: we would still be able to do `axl.Random()` right? Ie this is not throwing away the ability to have defaults?

**Comment by meatballs** [comment]
> Question: we would still be able to do axl.Random() right? Ie this is not throwing away the ability to have defaults?

Yes we would. No it is not throwing anything away other than positional arguments

**Comment by meatballs** [comment]
I'm re-opening this but the suggestion now is that we use kwargs throughout the library but we don't remove `init_args` Thus, positional arguments are allowed and will work, but we don't use them ourselves.
