### ISSUE TITLE
A script to automatically detect if all strategy modules are listed in `docs/reference/all_strategies.rst`

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#957]
Currently, whenever a new strategy module (file) is added to `axelrod/strategies` it needs to be also added to `docs/reference/all_strategies.rst` to ensure that an index of all strategies is built as can be seen here: http://axelrod.readthedocs.io/en/latest/reference/all_strategies.html

This needs to be checked during the review process but it would be helpful to have a script that could be run (by travis) to indicate that all the modules have been listed. So for example it would look like follows if all were listed (no output):

```
$ python check_strategy_index.py
$ 
```

Of if the `axelrod/strategies/tit_for_tat.py` file was not listed it would return ` sys.exit(1)` (so that it's recognised as a failure):

```
$ python check_strategy_index.py
ERROR: `axelrod/strategies/tit_for_tat.py` is not included in the index.
```

This could be done with an inspection of the `axelrod/strategies` directory as well as using some regex on the `docs/reference/all_strategies.rst` file.

Note that we have explored automatically generating the `all_strategies.rst` file and came to a dead end (we can't get read the docs to do that for us for example).

**Comment by drvinceknight** [comment]
@MariosZoulias perhaps you would like to take this one?

**Comment by drvinceknight** [comment]
Unless you want this @MariosZoulias I might pick it up tomorrow :)

**Comment by MariosZoulias** [comment]
Hi .
I already have the little issue of refactoring mutal.py , and the one i would like to work on about the "stein and rapoport" strategy.
I would love to work on this as well .
I have scheduled my program and i will work on my issues during the Easter as it is a free-of-lectures period.

Sorry for answering so late .

**Comment by drvinceknight** [comment]
> I have scheduled my program and i will work on my issues during the Easter as it is a free-of-lectures period.

Ok sounds good, no problem about the late reply: good to know you want this issue :) :+1:

**Comment by drvinceknight** [comment]
@MariosZoulias I had a couple of minutes spare so I've picked this one up (#980) : hope that's ok :)
