### ISSUE TITLE
The `__repr__` for the human strategy includes an extra `C` and `D`.

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/Axelrod#958]
This is a result of #953 which now automatically add the various attributes to the players so it looks like:

```python
>>>vince = axl.Human()
>>> vince
Human: human, C, D
```

You can pass different symbols for the `C` and `D`:

```python
>>> vince = axl.Human(name="Vince", c_symbol=":)", d_symbol=":(")
>>> vince
Human: Vince, :), :(
```

I suggest that in this case we can override the `repr` to not display the `c_symbol` and the `d_symbol`. I think that as the Human player is only going to be used at a repl so it's ok to clear it up a bit (whereas normally we want the `__repr__` to be precise).

**Comment by Chadys** [comment]
Should it still display 'Human: Vince" or just keep "Vince" ? Adding 'Human' doesn't seems necessary for the reason you gave above

**Comment by drvinceknight** [comment]
Sure. I'm easy here, whatever is preferred :)
