### ISSUE TITLE
some ideas on refactoring fingerprint

### ISSUE THREAD

**Issue by eric-s-s** [Axelrod-Python/Axelrod#969]
@drvinceknight 

here are some thoughts on refactoring fingerprint.py

- move most of the staticmethods to private functions.  it seems that their main point is to aid in the fingerprint or plot methods, and not be of use by themselves.
- use those private methods to make a set of instance variables.  thus, at instantiation, call methods to create self._probe_list, self._points, self._cheap_to_generate_variables.
- use property decorator and setter decorator so that when a new step or probe is created, can reset all the instance variable that rely on them (nothing that requires playing a tournament, just the edges/points/probes)
- move the data reshaping and plotting to a separate class that can be easily re-used if/when other fingerprinting methods come along.  also, will aid in adding functionality of comparing two data sets to see if fingerprints are a match.  (no idea HOW to do that, but with a separate DataManipulation class it would be easier to write/change).  The fingerprint class can easily instantiate and call the plot method.  (also, more freedom to create different plot methods)

hope these are useful ideas.

bonus: type hinting

**Comment by drvinceknight** [comment]
> move most of the staticmethods to private functions. it seems that their main point is to aid in the fingerprint or plot methods, and not be of use by themselves.
> use those private methods to make a set of instance variables. thus, at instantiation, call methods to create self._probe_list, self._points, self._cheap_to_generate_variables.

This was something we discussed quite a lot and that @meatballs is in favour of. So :+1: from me.

> use property decorator and setter decorator so that when a new step or probe is created, can reset all the instance variable that rely on them (nothing that requires playing a tournament, just the edges/points/probes)

Sounds good :+1: 

> move the data reshaping and plotting to a separate class that can be easily re-used if/when other fingerprinting methods come along. also, will aid in adding functionality of comparing two data sets to see if fingerprints are a match. (no idea HOW to do that, but with a separate DataManipulation class it would be easier to write/change). The fingerprint class can easily instantiate and call the plot method. (also, more freedom to create different plot methods)

I'm not sure about this one. Comparing fingerprint data is actually straightforward the fp class has a dictionary attribute so you can just compare those directly (the main reason it was awkward on #966 is because I had to checkout different branches so needed to write the data to file). 

I suggest leaving this one on hold until /if there is a need for it?

**Comment by eric-s-s** [comment]
thank you.  will get to work on it.

**Comment by drvinceknight** [comment]
> will get to work on it.

Cool :) One thing the refactoring of those static methods to functions should help with is clearing up the unit tests a bit (this is Owen's point but he's away right now so I'm doing my best to represent him :)). A lot of the unit tests currently need the creation of a fp, if they're true functions then we can unit test them properly based on io. :+1:

**Comment by meatballs** [comment]
> move most of the staticmethods to private functions. it seems that their main point is to aid in the fingerprint or plot methods, and not be of use by themselves.

A big 👍  from me for that one!

**Comment by eric-s-s** [comment]
okay, i would like a decision on something, please.

**step**: it's both a variable of the fingerprint() method and a property of the class.

currently, AshlockFingerprint creates `self.step` outside of the __init__ . If `step` is part of the class, it seems intuitive to be set at the __init__ and not be re-settable in fingerprint method.  instead have it be independently called/set by `@property` and `@step.setter`.  

or

make it a variable of fingerprint() and not be callable in the class.

or 

other idea?

**Comment by drvinceknight** [comment]
My preference would be a variable of fingerprint.

**Comment by eric-s-s** [comment]
while  i think of it, is there a need for `self.spatial_tournament` ?  it's already in `self.data` and `self.interactions`.  `self.spatial_tournament` and `self.step`  were the cause of me trying to refactor this as a specialized tournament that sets up the probes at instantiation.

**Comment by drvinceknight** [comment]
Removing it sounds sensible.

**Comment by drvinceknight** [comment]
Closed by suggestion on #970 :+1:
